
<div class="uk-grid-small" uk-grid>
    <div class="uk-width-medium@s">

        <ul class="uk-tab uk-tab-left uk-visible@s">
            <li class="uk-active"><a href="#">Info. do cliente</a></li>
                <li><a href="/admin/contract-item?id_company=<?php echo $_GET['id_company'] ?>">Módulos</a></li>
            
        </ul>

    </div>
    <div class="uk-width-expand@s">


        <ul class="uk-tab uk-hidden@s">
            <li class="uk-active"><a href="#">Info. do cliente</a></li>
            <li><a href="/admin/contract-item?id_company=<?php echo $_GET['id_company'] ?>">Módulos</a></li>
            
        </ul>

        <div class="uk-card uk-card-body uk-card-default uk-card-small">
            <form class="ui form" autocomplete="off">
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1">
                        <div class="field">
                            <label>Documento</label>
                            <input type="text" name="document_company" />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-2-3@s">
                        <div class="field">
                            <label>Nome completo</label>
                            <input type="text" name="name_company" />
                        </div>
                    </div>
                    <div class="uk-width-1-3@s">
                        <div class="field">
                            <label>Apelido</label>
                            <input type="text" name="nickname_company" />
                        </div>
                    </div>
                </div>
                <hr class="uk-divider-small" />
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-2@s">
                        <div class="field">
                            <label>CEP</label>
                            <input type="text" name="zipcode_company" class="on-viacep-zipcode on-mask-zipcode" />
                            <p class="uk-text-small uk-text-warning uk-margin-remove">Preenchimento automático</p>
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-2-3@s">
                        <div class="field">
                            <label>Logradouro</label>
                            <input type="text" name="public_place_company" class="on-viacep-public-place" />
                        </div>
                    </div>
                    <div class="uk-width-1-3@s">
                        <div class="field">
                            <label>Número</label>
                            <input type="text" name="number_company" />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1@s">
                        <div class="field">
                            <label>Complemento</label>
                            <input type="text" name="complement_company" />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-2-5@s">
                        <div class="field">
                            <label>Bairro</label>
                            <input type="text" name="district_company" class="on-viacep-district" />
                        </div>
                    </div>
                    <div class="uk-width-2-5@s">
                        <div class="field">
                            <label>Cidade</label>
                            <input type="text" name="city_company" class="on-viacep-city" />
                        </div>
                    </div>
                    <div class="uk-width-1-5@s">
                        <div class="field">
                            <label>UF</label>
                            <input type="text" name="state_company" class="on-viacep-state" />
                        </div>
                    </div>
                </div>
                <hr class="uk-divider-small" />
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-2@s">
                        <div class="field">
                            <label>Telefone 1</label>
                            <input type="text" name="phone_primary_company" class="on-mask-phone" />
                        </div>
                    </div>
                    <div class="uk-width-1-2@s">
                        <div class="field">
                            <label>Telefone 2</label>
                            <input type="text" name="phone_secondary_company" class="on-mask-phone" />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-2@s">
                        <div class="field">
                            <label>Website</label>
                            <input type="text" name="website_company" />
                        </div>
                    </div>
                    <div class="uk-width-1-2@s">
                        <div class="field">
                            <label>E-mail</label>
                            <input type="text" name="email_company" />
                        </div>
                    </div>
                </div>
                <hr class="uk-divider-small" />
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1@s">
                        <div class="field">
                            <label>Observação</label>
                            <textarea name="observation_company" rows="4"></textarea>
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1@s">
                        <div class="field">
                            <button class="ui right labeled icon small primary ok button"><i class="ui save icon"></i> Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
