<div class="uk-panel uk-margin-bottom">
    <ul class="uk-breadcrumb uk-light">
        <li><a href="/account/dashboard">Início</a></li>
        <li><span><?php echo $this->title_page ?></span></li>
    </ul>
</div>

<div class="uk-panel uk-margin-bottom">
    <button class="ui primary button on-button-insert">Novo Registro</button>
</div>

<div class="uk-card uk-card-body uk-card-muted uk-card-small">
    <table class="ui inverted basic very compact table on-table-company">
        <thead>
            <tr>
                <th>ID</th>
                <th>Apelido / Nome Fantasia</th>
                <th>CPF / CNPJ</th>
                <th>Telefone</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

<div class="ui small modal on-modal-insert">
    <div class="header">
        <h4 class="uk-h4">Cadastrar Empresa</h4>
    </div>
    <div class="content">
        <form class="ui form on-form-insert">
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label class="on-label-document-company">Documento (CPF/CNPJ)</label>
                        <input type="text" name="document_company" class="on-mask-document" />
                    </div>
                </div>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label class="on-label-document-company">Telefone</label>
                        <input type="text" name="phone_primary_company" class="on-mask-phone" />
                    </div>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-3@s">
                    <div class="field required">
                        <label class="on-label-nickname-company">Apelido / Nome Fantasia</label>
                        <input type="text" name="nickname_company" />
                    </div>
                </div>
                <div class="uk-width-2-3@s">
                    <div class="field required">
                        <label class="on-label-name-company">Nome completo / Razão Social</label>
                        <input type="text" name="name_company" />
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon small secondary deny button"><i class="ui close icon"></i> Cancelar</button>
        <button class="ui right labeled icon small primary ok button"><i class="ui save icon"></i> Salvar</button>
    </div>
</div>