
<header class="uk-section on-bg-header-1" id="inicio">

    <div class="uk-container">

        <div uk-grid>
            <div class="uk-width-1-1 uk-flex uk-flex-center">
                <ul class="uk-breadcrumb">
                    <li><a href="/servicos">Serviços</a></li>
                    <li><span class="uk-text-primary">Automação 360</span></li>
                </ul>
            </div>
        </div>
        <div class="uk-flex uk-flex-center uk-text-center uk-text-left@s" uk-grid>
            <div class="uk-width-2-3@s uk-text-center">
                <p class="uk-text-meta uk-margin-remove-bottom uk-text-primary">on360</p>
                <h1 class="uk-h1 uk-margin-remove-top"> <span class="uk-text-primary">Acelere suas vendas</span> e faça seu negócio crescer</h1>

                <p class="uk-text-lead">Tenha todas as ferramentas de e-mail marketing, CRM e automação que você precisa para aumentar os seus lucros, melhorar os fluxos de trabalho e ter clientes mais felizes</p>
                <button class="uk-button uk-button-primary">clique aqui</button>
            </div>
        </div>
    </div>
</header>

<section class="uk-section" id="contato">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-2-3@s">
                <div class="uk-card uk-card-body uk-card-primary uk-border-rounded">
                    <h2 class="uk-h2">Ficou Interessado?</h2>
                    <p class="uk-text-lead">Preencha o formulário para analisarmos a sua necessidade juntos, teremos uma equipe pronta para orientar e mostrar as melhores opções do mercado.</p>
                </div>
            </div>
        </div>
    </div>
</section>
