<header class="uk-section on-bg-header-1" id="inicio">
    <div class="uk-container">
        <div uk-grid>
            <div class="uk-width-1-1 uk-flex uk-flex-center">
                <ul class="uk-breadcrumb">
                    <li><span class="uk-text-primary">Serviços</span></li>
                </ul>
            </div>
        </div>
        <div class="uk-flex uk-flex-center uk-text-center uk-text-left@s" uk-grid>
            <div class="uk-width-2-3@s uk-text-center">
                <h1 class="uk-h1 uk-margin-remove-top">Nossos <span class="uk-text-primary">Serviços</span></h1>
                <p class="uk-text-lead">Destaque-se online com um site profissional, loja online ou portfólio. Com nossa expertise, você pode transformar qualquer ideia em realidade.</p>
                <a class="uk-button uk-button-primary" href="#read-more" uk-scroll><span uk-icon="icon: arrow-down"></span> Saiba mais</a>
            </div>
        </div>
    </div>
</header>


<section class="uk-section on-bg-shape-1" id="read-more">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-2-3@s uk-text-center">
                <p class="uk-heading-line uk-text-center"><span>01 · Como trabalhamos</span></p>
                <h2 class="uk-h2">Fluxo de Trabalho</h2>
                <p class="uk-text-lead">Nosso fluxo de trabalho simples e flexível para atender os mais diversos problemas e entregar no melhor tempo possível.</p>
            </div>
        </div>
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-1-3@s">
                <div class="uk-card uk-card-body uk-card-secondary uk-border-rounded">
                    <p class="uk-text-lead">01.</p>

                    <h3 class="uk-h3">Análise</h3>
                    <p class="uk-text-meta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                </div>
            </div>
            <div class="uk-width-1-3@s">
                <div class="uk-card uk-card-body uk-card-secondary uk-border-rounded">
                    <p class="uk-text-lead">02.</p>

                    <h3 class="uk-h3">Estratégia</h3>
                    <p class="uk-text-meta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                </div>
            </div>
            <div class="uk-width-1-3@s">
                <div class="uk-card uk-card-body uk-card-secondary uk-border-rounded">
                    <p class="uk-text-lead">03.</p>

                    <h3 class="uk-h3">Produção</h3>
                    <p class="uk-text-meta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="uk-section">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-2@s">
                <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d107ea8f688_Rectangle-8.jpg" />
            </div>
            <div class="uk-width-1-2@s on-shape-radial-pink">
                <p class="uk-heading-line uk-text-left"><span>Serviços · 02</span></p>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-auto">
                        <div class="on-circle-icon">
                            <span uk-icon="icon: cog; ratio: 1.5"></span>
                        </div>
                    </div>
                    <div class="uk-width-expand">
                        <h2 class="uk-h2 uk-margin-remove-bottom">Automação 360</h2>
                        <p class="uk-text-meta uk-margin-remove-top">Tenha todas as ferramentas de e-mail marketing, CRM e automação que você precisa para aumentar os seus lucros, melhorar os fluxos de trabalho e ter clientes mais felizes.</p>

                    </div>
                </div>
                <table class="uk-table uk-table-divider">
                    <tbody>
                        <tr>
                            <td>
                                <p class="uk-text-meta">E-mail Marketing</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">SMS</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Chatbots</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">CRM</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="uk-section">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-2@s on-shape-radial-pink">
                <p class="uk-heading-line uk-text-left"><span>Serviços · 03</span></p>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-auto">
                        <div class="on-circle-icon">
                            <span uk-icon="icon: code; ratio: 1.5"></span>
                        </div>
                    </div>
                    <div class="uk-width-expand">
                        <h2 class="uk-h2 uk-margin-remove-bottom">Criação de Sites</h2>
                        <p class="uk-text-meta uk-margin-remove-top">Tenha todas as ferramentas de e-mail marketing, CRM e automação que você precisa para aumentar os seus lucros, melhorar os fluxos de trabalho e ter clientes mais felizes.</p>

                    </div>
                </div>
                <table class="uk-table uk-table-divider">
                    <tbody>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Landing Pages</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Site Institucional</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Loja Virtual</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Sistemas Web</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="uk-width-1-2@s">
                <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d3e4ca8f66e_Rectangle-9-p-800.jpeg" />
            </div>
        </div>
    </div>
</section>

<section class="uk-section">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-2@s">
                <img class="uk-border-rounded" src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d107ea8f688_Rectangle-8.jpg" />
            </div>
            <div class="uk-width-1-2@s on-shape-radial-pink">
                <p class="uk-heading-line uk-text-left"><span>Serviços · 04</span></p>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-auto">
                        <div class="on-circle-icon">
                            <span uk-icon="icon: search; ratio: 1.5"></span>
                        </div>
                    </div>
                    <div class="uk-width-expand">
                        <h2 class="uk-h2 uk-margin-remove-bottom">Tráfego Pago</h2>
                        <p class="uk-text-meta uk-margin-remove-top">Tenha todas as ferramentas de e-mail marketing, CRM e automação que você precisa para aumentar os seus lucros, melhorar os fluxos de trabalho e ter clientes mais felizes.</p>

                    </div>
                </div>
                <table class="uk-table uk-table-divider">
                    <tbody>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Google Ads</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Meta  Ads</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">LinkedIn Ads</p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="uk-text-meta">Pinterest Ads</p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>


<section class="uk-section uk-section-secondary on-bg-shape-1">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle uk-margin-large-top uk-margin-large-bottom" uk-grid>
            <div class="uk-width-1-2@s">
                <div class="uk-child-width-auto uk-grid-small uk-flex uk-flex-center" uk-grid>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949dbd87a8f64c_chrome_os.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d0a85a8f64f_loom.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d92e7a8f64a_mailchimp.svg" />
                        </div>
                    </div>
                </div>
                <div class="uk-child-width-auto uk-grid-small uk-flex uk-flex-center" uk-grid>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949dbd1ca8f656_evernote.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d5a60a8f633_ubuntu.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d521ca8f649_dropbox.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d58fba8f651_github.svg" />
                        </div>
                    </div>
                </div>
                <div class="uk-child-width-auto uk-grid-small uk-flex uk-flex-center" uk-grid>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d2671a8f64b_trello.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949db727a8f655_jira.svg" />
                        </div>
                    </div>
                    <div>
                        <div class="uk-card uk-card-body uk-card-default uk-border-circle">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d263ba8f632_basecamp.svg" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="uk-width-1-2@s">
                <p class="uk-heading-line uk-text-left"><span>05 · Tecnologias</span></p>
                <h2 class="uk-h2">As melhores soluções do mercado</h2>
                <p class="uk-text-meta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
            </div>
        </div>
    </div>
</section>


<section class="uk-section">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-1-1@s">
                <div class="uk-card uk-card-body uk-card-primary uk-border-rounded uk-text-center" style="margin-top: -150px">
                    <h2 class="uk-h2">Ficou Interessado?</h2>
                    <p class="uk-text-lead">Preencha o formulário para analisarmos a sua necessidade juntos, teremos uma equipe pronta para orientar e mostrar as melhores opções do mercado.</p>
                    <a class="uk-button uk-button-primary" href="#"><span uk-icon="icon: bolt"></span> Iniciar atendimento</a>
                    <a class="uk-button uk-button-default" href="/contato"><span uk-icon="icon: more"></span> Outros contatos</a>
                </div>
            </div>
        </div>
    </div>
</section>
