<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
<style>
    #panorama {
        width: 100%;
        height: 100%;
    }
</style>

<script>
    pannellum.viewer('panorama', {
        "type": "equirectangular",
        "panorama": "/background.jpg",
        "autoLoad": true
    });
</script>

<div class"uk-position-absolute uk-position-cover" id="panorama"></div>
<div class="uk-position-center uk-position-z-index">
    <div class="uk-container uk-container-small">
        <div class="uk-child-width-1-3@s" uk-grid>
            <div>
                <div class="uk-card uk-card-body uk-border-rounded uk-height-large" style="background-image: url(https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed44d9ea0977f84cc4cc79e_denys-nevozhai-guNIjIuUcgY-unsplash%20(1).jpg)">

                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-border-rounded uk-height-large" style="background-image: url(https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed44d9ea0977f84cc4cc79e_denys-nevozhai-guNIjIuUcgY-unsplash%20(1).jpg)">

                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-border-rounded uk-height-large" style="background-image: url(https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed44d9ea0977f84cc4cc79e_denys-nevozhai-guNIjIuUcgY-unsplash%20(1).jpg)">

                </div>
            </div>
        </div>
    </div>
</div>