<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"></script>
<style>
    #panorama {
        width: 100%;
        height: 100%;
    }
</style>

<div class="uk-position-absolute uk-position-cover" id="panorama"></div>
<script>
    pannellum.viewer('panorama', {
        "type": "equirectangular",
        "panorama": "/background.jpg",
        "autoLoad": true
    });
</script>

<div class="uk-position-center uk-position-z-index">
    <div class="uk-container uk-container-small">
        <div class="uk-child-width-1-1@s uk-text-center" uk-grid>
            <div>
            <img src="/public/assets/images/logotipo.png" width="111" sizes="(max-width: 479px) 27vw, (max-width: 767px) 88.796875px, 111px" srcset="
                /public/assets/images/logotipo.png  500w,
                /public/assets/images/logotipo.png  800w,
                /public/assets/images/logotipo.png       1034w
                        " alt="" class="light_logo on-home-page" />
            </div>
        </div>
        <div class="uk-child-width-1-3@s" uk-grid>
            <div>
                <div class="uk-card uk-card-body uk-border-rounded uk-height-large uk-background-cover" style="background-image: url(https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg)">
<h2>Já fiz intercâmbio</h2>
                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-border-rounded uk-height-large uk-background-cover" style="background-image: url(https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed607afba2aedb76aa630e4_david-gavi-AdIJ9S-kbrc-unsplash.jpg)">
                <h2>Estou pesquisando</h2>
                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-border-rounded uk-height-large uk-background-cover" style="background-image: url(https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg)">
<h2>Já estou de malas prontas</h2>
                </div>
            </div>
        </div>
    </div>
</div>