
<div class="uk-section uk-section-muted uk-padding-small">
    <div class="uk-container">
        <div uk-grid>
            <div class="uk-width-1-1 uk-flex uk-flex-center">
                <ul class="uk-breadcrumb">
                    <li><a href="/servicos">Serviços</a></li>
                    <li><span class="uk-text-primary">Gestão de Tráfego Pago</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<header class="uk-section uk-section-muted" id="inicio">

    <div class="uk-container">
        <div class="uk-flex uk-flex-middle uk-text-center uk-text-left@s" uk-grid>
            <div class="uk-width-1-2@s">
                <p class="uk-text-meta uk-text-primary uk-margin-remove-bottom">onAds</p>
                <h1 class="uk-h1 uk-margin-remove-top">Gestão de <br /> Tráfego Pago</h1>
                <p class="uk-text-lead">Com nossa experiência e estratégia criamos sites profissionais com layout exclusivo e otimizado, para todos os tipos de segmentos e empresas.</p>
                <a class="uk-button uk-button-primary" href="#servicos">Saiba Mais <span uk-icon="icon: arrow-down"></span></a>
            </div>
            <div class="uk-width-1-2@s uk-text-center">
                <div class="uk-card uk-card-body uk-card-default uk-border-rounded uk-height-large">
                    
                </div>
            </div>
        </div>
    </div>
</header>

<section class="uk-section uk-section-muted">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-5@s">
                <h4 class="uk-h4">Principais tecnologias</h4>
            </div>
            <div class="uk-width-4-5@s">
                <div class="uk-position-relative" uk-slider="draggable: false">
                    <ul class="uk-child-width-1-4 uk-slider-items uk-grid">
                        <li >
                            <div class="uk-uk-card uk-card-body uk-card-default uk-border-rounded uk-height-small">
                                <!--<img src="https://www.php.net/images/logos/php-logo.svg" alt="">-->
                            </div>
                        </li>
                        <li>
                            <div class="uk-uk-card uk-card-body uk-card-default uk-border-rounded uk-height-small">
                                <!--<img src="https://www.php.net/images/logos/php-logo.svg" alt="">-->
                            </div>
                        </li>
                        <li>
                            <div class="uk-uk-card uk-card-body uk-card-default uk-border-rounded uk-height-small">
                                <!--<img src="https://www.php.net/images/logos/php-logo.svg" alt="">-->
                            </div>
                        </li>
                        <li>
                            <div class="uk-uk-card uk-card-body uk-card-default uk-border-rounded uk-height-small">
                                <!--<img src="https://www.php.net/images/logos/php-logo.svg" alt="">-->
                            </div>
                        </li>
                        <li>
                            <div class="uk-uk-card uk-card-body uk-card-default uk-border-rounded uk-height-small">
                                <!--<img src="https://www.php.net/images/logos/php-logo.svg" alt="">-->
                            </div>
                        </li>
                        <li>
                            <div class="uk-uk-card uk-card-body uk-card-default uk-border-rounded uk-height-small">
                                <!--<img src="https://www.php.net/images/logos/php-logo.svg" alt="">-->
                            </div>
                        </li>
                    </ul>
                    <a class="uk-position-center-left" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
                </div>
            </div>
        </div>
    </div>
</section>



<section class="uk-section" id="servicos">
    <div class="uk-container">
        <div uk-grid>
            <div class="uk-width-1-1@s">
                <h2 class="uk-h2">Serviços oferecidos</h2>
                <p class="uk-text-lead">Conheça alguns dos serviços que oferecemos para nossos clientes.</p>
            </div>
            <div class="uk-child-width-1-3@s uk-grid-small uk-grid-match" uk-grid>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/design.png);"></div>
                        <h3 class="uk-h3">Reconhecimento de Marca</h3>
                        <p class="uk-text-meta">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/code.png);"></div>
                        <h3 class="uk-h3">Conversão de leads</h3>
                        <p class="uk-text-meta">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/social.png);"></div>
                        <h3 class="uk-h3">Venda de Produtos</h3>
                        <p class="uk-text-meta">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="uk-section uk-section-primary uk-padding-remove" id="projetos">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-3@s uk-padding">
                <h3 class="uk-h2">Projetos</h3>
                <p class="uk-text-lead">Conheça alguns dos nossos projetos concluídos.</p>
                <div class="uk-child-width-1-1@s" uk-grid>
                    <div>
                        <h4 class="uk-h4 uk-text-large uk-text-primary uk-margin-remove">+ 100</h4>
                        <p class="uk-text-meta uk-margin-remove">Projetos Concluídos</p>

                    </div>
                    <div>
                        <h4 class="uk-h4 uk-text-large uk-text-primary uk-margin-remove">+ 6</h4>
                        <p class="uk-text-meta uk-margin-remove">Anos de Experiência</p>

                    </div>
                    <div>
                        <h4 class="uk-h4 uk-text-large uk-text-primary uk-margin-remove">+ 71.293.331</h4>
                        <p class="uk-text-meta uk-margin-remove">Leads Geradas</p>

                    </div>
                </div>

            </div>
            <div class="uk-width-2-3@s" style="overflow: hidden; z-index: 999; height: 500px;">
                <div>
                    <div style="position: relative; perspective: 1700px; transform: perspective(1000px);">
                        <div class="uk-child-width-1-2@s uk-child-width-1-3@m" uk-grid="parallax: 150;" style="transform: translate(10%, 0px) rotateX(34deg) rotateY(-9deg) rotateZ(26deg); transform-style: preserve-3d; position: absolute">
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
    <div>
        <div class="uk-card uk-card-default uk-flex uk-flex-center uk-flex-middle" style="height: 200px">Item</div>
    </div>
</div>
                    </div>
                </div>
<!--                <div class="uk-position-relative" uk-slider="draggable: false">
                    <ul class="uk-slider-items uk-grid on-slider-portfolio">
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/absafe.com.br.webp" alt="">
                                 <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> 
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/myrental.com.br.webp" alt="">
                                 <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> 
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/absafe.com.br.webp" alt="">
                                 <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> 
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/myrental.com.br.webp" alt="">
                                 <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> 
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/absafe.com.br.webp" alt="">
                                 <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> 
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/myrental.com.br.webp" alt="">
                                 <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> 
                            </div>
                        </li>
                    </ul>
                    <a class="uk-position-center-left" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
                </div>-->
            </div>
        </div>
    </div>
</section>

<section class="uk-section on-border-bottom" id="contato">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-2@s">
                <h2 class="uk-h2">Ficou Interessado?</h2>
                <p class="uk-text-lead">Preencha o formulário para analisarmos a sua necessidade juntos, teremos uma equipe pronta para orientar e mostrar as melhores opções do mercado.</p>
                
            </div>
            <div class="uk-width-1-2@s">
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <form class="ui form on-form-contact">
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field required">
                                    <label>Nome</label>
                                    <input type="text" name="name" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field required">
                                    <label>Telefone</label>
                                    <input type="text" name="phone" class="on-mask-phone" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field required">
                                    <label>E-mail</label>
                                    <input type="text" name="email" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field">
                                    <button class="uk-button uk-button-primary">Enviar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
