
<header class="uk-section on-bg-header-1" id="inicio">

    <div class="uk-container">

        <div uk-grid>
            <div class="uk-width-1-1 uk-flex uk-flex-center">
                <ul class="uk-breadcrumb">
                    <li><span class="uk-text-primary">Sobre</span></li>
                </ul>
            </div>
        </div>
        <div class="uk-flex uk-flex-center uk-text-center uk-text-left@s" uk-grid>
            <div class="uk-width-2-3@s uk-text-center">
                <h1 class="uk-h1 uk-margin-remove-top">Somos uma <br /><span class="uk-text-primary">Agência Digital</span></h1>

                <p class="uk-text-lead">especializada em <strong>Criar e Gerenciar Sites</strong> que ajudam no processo de coleta, organização, análise, compartilhamento e monitoramento de informações para divulgação e venda de produtos ou serviços.</p>
                <a class="uk-button uk-button-primary" href="#read-more" uk-scroll><span uk-icon="icon: arrow-down"></span> Saiba mais</a>
            </div>
        </div>
    </div>
</header>


<section class="uk-section bg-tile-top bg-neutral-600" id="read-more">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-1-1@s">
                <div class="uk-card uk-card-body uk-card-secondary uk-border-rounded on-bg-shape-1">
                    <div class="uk-child-width-1-3@s uk-text-center" uk-grid>
                        <div>
                            <h3 class="uk-h1">+200</h3>
                            <p class="uk-text-lead">Sites <br />Produzidos</p>
                        </div>
                        <div>
                            <h3 class="uk-h1">+10Mi</h3>
                            <p class="uk-text-lead">Conversão <br />em Leads</p>
                        </div>
                        <div>
                            <h3 class="uk-h1">+7</h3>
                            <p class="uk-text-lead">Anos de <br />Experiência</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="uk-section"  id="read-more">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-2@s">

                <p class="uk-heading-line uk-text-left"><span>01 · Começo</span></p>
                <h2 class="uk-h2">Um pouco de <span class="uk-text-secondary">história</span></h2>
                <p class="uk-text-lead">A ideia de criar uma empresa foi constituída em 2013 quando o seu criador finalizava sua formação academica.</p>
                <p class="uk-text-lead">A empresa se formou em Marília - SP em parceria com alguns colegas de acadêmicos e em seguida migrou para Belém - PA.</p>
                <p class="uk-text-lead">A ONDS sempre caminhou visando custos baixos com sua estratégia home office, sempre prezando agilidade no atendimento e qualidade nas suas entregas.</p>

            </div>
            <div class="uk-width-1-2@s">
                <div class="uk-grid-small uk-grid-match" uk-grid>
                    <div class="uk-width-2-3">

                        <div class="uk-cover-container uk-height-medium uk-border-rounded">
                            <img src="https://img.freepik.com/free-photo/team-meeting-online-conference-call-laptop_23-2148890424.jpg?t=st=1649999551~exp=1650000151~hmac=557335575ac1b32e582da68238507cc798cdc514e58500788b44f5c4b03be173&w=740" alt="" uk-cover>
                        </div>
                        <div class="uk-cover-container uk-height-medium uk-border-rounded">
                            <img src="https://img.freepik.com/free-photo/empty-start-up-company-office-with-nobody-it-waiting-people-start-working-financial-documents-during-business-meeting-workplace-with-modern-furniture-management-graphs-computer_482257-30560.jpg?w=826" alt="" uk-cover>
                        </div>
                    </div>
                    <div class="uk-width-1-3">
                        <div class="uk-cover-container uk-border-rounded">
                            <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d7e13a8f625_redd-5U_28ojjgms-unsplash-p-1600.jpeg" alt="" uk-cover>
                        </div>
                        <!--                        <div class="uk-card uk-card-secondary uk-grid-collapse uk-child-width-1-1@s uk-margin uk-border-rounded" uk-grid>
                                                    <div class="uk-card-media-left uk-cover-container">
                                                        <img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949d7e13a8f625_redd-5U_28ojjgms-unsplash-p-1600.jpeg" alt="" uk-cover />
                                                        <canvas width="600" height="400"></canvas>
                                                    </div>
                                                </div>-->

                    </div>
                </div>



            </div>
        </div>
    </div>
</section>

<section class="uk-section" id="contato">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-2-3@s uk-text-center">
                <p class="uk-heading-line uk-text-center"><span>02 · Localização e Atendimento</span></p>
                <h2 class="uk-h2">Nossa <span class="uk-text-secondary">abrangência</span></h2>
                <p class="uk-text-lead">Apesar de concentrarmos nossa carteira de clientes principalmente no estado de São Paulo, nossa área de atendimento vai além do território nacional, já produzimos sites para diversos países no continente Americano e Europa.</p>
            </div>
        </div>
        <div uk-grid>
            <div class="uk-width-1-1@s"><img src="https://assets.website-files.com/6239c2cd52949d0f76a8f421/6239c2ce52949daeb0a8f6af_world-map.png" />
            </div>
        </div>
    </div>
</section>


<section class="uk-section uk-section-secondary on-bg-shape-1">
    <div class="uk-container">

        <div class="uk-flex uk-flex-center uk-margin-large-top" uk-grid>
            <div class="uk-width-1-2@s uk-text-center">
                <p class="uk-heading-line uk-text-center"><span>03 · Saiba Mais</span></p>
                <h2 class="uk-h2">Conheça mais sobre nossa Agência</h2>
                <p class="uk-text-meta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>

            </div>
        </diV>
        <div class="uk-margin-large-bottom" uk-grid>
            <div class="uk-width-1-2@s">

                <div class="uk-cover-container uk-height-medium uk-border-rounded">
                    <img src="https://assets.website-files.com/6239c2ce52949d0196a8f42c/6239c2ce52949d2793a8f49c_studio-republic-qeij_dhDhGg.jpg" alt="" uk-cover />
                    <div class="uk-position-cover uk-overlay uk-flex uk-flex-center uk-flex-middle uk-text-center">
                        <a class="uk-button uk-button-primary" href="/servicos" uk-scroll><span uk-icon="icon: arrow-right"></span> Nossos Serviços</a>
                    </div>

                </div>
            </div>
            <div class="uk-width-1-2@s">

                <div class="uk-cover-container uk-height-medium uk-border-rounded">
                    <img src="https://assets.website-files.com/6239c2ce52949d0196a8f42c/6239c2ce52949dab72a8f48a_copernico-yfmU1uL_mp8.jpg" alt="" uk-cover>
                    <div class="uk-position-cover uk-overlay uk-flex uk-flex-center uk-flex-middle uk-text-center">
                        <a class="uk-button uk-button-primary" href="/portfolio"><span uk-icon="icon: arrow-right"></span> Nossos Portfólio</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<section class="uk-section">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-1-1@s">
                <div class="uk-card uk-card-body uk-card-primary uk-border-rounded uk-text-center" style="margin-top: -150px">
                    <h2 class="uk-h2">Ficou Interessado?</h2>
                    <p class="uk-text-lead">Preencha o formulário para analisarmos a sua necessidade juntos, teremos uma equipe pronta para orientar e mostrar as melhores opções do mercado.</p>
                    <a class="uk-button uk-button-primary" href="#"><span uk-icon="icon: bolt"></span> Iniciar atendimento</a>
                    <a class="uk-button uk-button-default" href="/contato"><span uk-icon="icon: more"></span> Outros contatos</a>
                </div>
            </div>
        </div>
    </div>
</section>
