<div class="uk-visible@s" uk-grid>
    <div class="uk-width-expand@s">
        <ul class="uk-breadcrumb">
            <li><a href="<?php echo $this->baseUrl('account') ?>"><span class="uk-margin-right" uk-icon="icon: reply"></span> Ir para o site</a></li>
            <li><span><?php echo $this->title ?></span></li>
        </ul>
    </div>
</div>
<hr class="uk-divider-small uk-visible@s" />
<div uk-grid>
    <div class="uk-width-medium@s uk-visible@m">
        <div class="uk-card uk-card-default uk-card-body uk-border-rounded uk-margin-bottom">
            <div style="background-color: rgba(0, 0, 0, .8); width: 60px; height: 60px; border-radius: 50%; color: #ffffff; font-size: 20px; padding: 20px; margin: 0 auto;">AC</div>
            <h4 class="uk-h4 uk-text-center uk-margin-top">Alberto Cruz</h4>
        </div>
    </div>
    <div class="uk-width-expand@s">
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded">
            <pre>
                <code class="fields">

                </code>
            </pre>

<!--            <table class="uk-table uk-table-divider uk-table-hover">
    <thead>
        <tr>
            <th><span uk-icon="icon: hashtag"></span></th>
            <th>Nome</th>
            <th>Enviado Há</th>
            <th>Status</th>
        </tr>
    </thead>
</table>-->
        </div>
    </div>
    <div class="uk-width-medium@s uk-visible@s">
        <div class="uk-card uk-card-primary uk-card-body uk-card-small uk-border-rounded">
            <h5 class="uk-h5 uk-margin-remove-bottom">Projeto:</h5>
            <p class="uk-text-meta uk-margin-remove-top site">...</p>
        </div>
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded uk-margin-top">
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Status:</h5>
            <p class="uk-text-meta uk-margin-remove-top status">...</p>
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Criado há:</h5>
            <p class="uk-text-meta uk-margin-remove-top data_hora">...</p>
        </div>
    </div>
</div>