<div class="uk-visible@s" uk-grid>
    <div class="uk-width-expand@s">
        <ul class="uk-breadcrumb">
            <li><a href="<?php echo $this->baseUrl('account') ?>">Início</a></li>
            <li><a href="<?php echo $this->baseUrl('project') ?>">Projeto: <b class="site">...</b></a></li>
            <li><span><?php echo $this->title ?></span></li>
        </ul>
    </div>
</div>
<hr class="uk-divider-small uk-visible@s" />
<div uk-grid>
    <div class="uk-width-medium@s uk-visible@m">
        <div class="uk-card uk-card-default uk-card-body uk-border-rounded">
            <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
                <?php echo $this->menu($this->title, 1) ?>
            </ul>
        </div>
    </div>
    <div class="uk-width-expand@s">
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded">
            <pre>
                <code class="fields">

                </code>
            </pre>

<!--            <table class="uk-table uk-table-divider uk-table-hover">
    <thead>
        <tr>
            <th><span uk-icon="icon: hashtag"></span></th>
            <th>Nome</th>
            <th>Enviado Há</th>
            <th>Status</th>
        </tr>
    </thead>
</table>-->
        </div>
    </div>
    <div class="uk-width-medium@s uk-visible@s">
        <div class="uk-card uk-card-primary uk-card-body uk-card-small uk-border-rounded">
            <h5 class="uk-h5 uk-margin-remove-bottom">Projeto:</h5>
            <p class="uk-text-meta uk-margin-remove-top site">...</p>
        </div>
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded uk-margin-top">
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Status:</h5>
            <p class="uk-text-meta uk-margin-remove-top status">...</p>
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Criado há:</h5>
            <p class="uk-text-meta uk-margin-remove-top data_hora">...</p>
        </div>
    </div>
</div>