<div class="uk-visible@s" uk-grid>
    <div class="uk-width-expand@s">
        <ul class="uk-breadcrumb">
            <li><a class="on-site-link" target="_blank" href="<?php echo $this->baseUrl('account') ?>">Ir para o site</a></li>
            <li><span><?php echo $this->title ?></span></li>
        </ul>
    </div>
</div>
<hr class="uk-divider-small uk-visible@s" />
<div uk-grid>
    <div class="uk-width-1-3@s">
        <div class="uk-card uk-card-default uk-card-body uk-border-rounded uk-margin-bottom">
            <div class="nome_sobrenome_chars" style="background-color: rgba(0, 0, 0, .8); width: 60px; height: 60px; border-radius: 50%; color: #ffffff; font-size: 20px; padding: 20px; margin: 0 auto;">...</div>
            <h4 class="uk-h4 uk-text-center uk-margin-top nome_sobrenome">...</h4>
        </div>
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded">
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Status:</h5>
            <p class="uk-text-meta uk-margin-remove-top descricao_status">...</p>
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Enviado há:</h5>
            <p class="uk-text-meta uk-margin-remove-top data_hora">...</p>
        </div>
    </div>
    <div class="uk-width-2-3@s">
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded">
            <button class="uk-button uk-button-primary uk-border-rounded b-ins">Criar Mensagem</button>
        </div>
        <hr class="uk-divider-small uk-visible@s" />
        <table class="uk-table uk-table-justify">
            <thead >
                <tr>
                    <th><span uk-icon="icon: hashtag"></span></th>
                    <th>Historico de Mensagens</th>
                    <th>Enviado Há</th>
                </tr>
            </thead>
        </table>
    </div>
</div>