<div class="uk-visible@s" uk-grid>
    <div class="uk-width-expand@s">
        <ul class="uk-breadcrumb">
            <li><a href="<?php echo $this->baseUrl('account') ?>">Início</a></li>
            <li><span><?php echo $this->title ?></span></li>
        </ul>
    </div>
</div>
<hr class="uk-divider-small uk-visible@s" />
<div uk-grid>
    <div class="uk-width-medium@s uk-visible@m">
        <div class="uk-card uk-card-secondary uk-card-body uk-border-rounded">
            <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
                <?php echo $this->menu($this->title, 1) ?>
            </ul>
        </div>
    </div>
    <div class="uk-width-expand@s">
        <div class="uk-card uk-card-secondary uk-card-body uk-card-small uk-border-rounded uk-margin-bottom">
            
<figure class="highcharts-figure">
    <div id="container"></div>
</figure>
            </div>
        <div class="uk-card uk-card-secondary uk-card-body uk-card-small uk-border-rounded">
            <table class="ui celled inverted table">
                <thead>
                    <tr>
                        <th><span uk-icon="icon: hashtag"></span></th>
                        <th>Nome</th>
                        <th>Cidade - UF</th>
                        <th>Visitado há</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>