<div class="section hero wf-section">
    <!-- <div class="hero_slider_contain">
        <div data-delay="6000" data-animation="fade" class="hero_slider w-slider" data-autoplay="true" data-easing="ease" data-hide-arrows="false" data-disable-swipe="false" data-autoplay-limit="0" data-nav-spacing="3" data-duration="800" data-infinite="true">
            <div class="w-slider-mask">
                <div data-w-id="d6d66d08-e21b-2d0f-ad10-141922c11985" class="slide w-slide">
                    <div class="collection-list-wrapper-contry-slider w-dyn-list">
                        <div role="list" class="collection-list-country-slider w-dyn-items">
                            <div role="listitem" class="collection-item-country-slider w-dyn-item">
                                <div class="country_slider_content_wrap">
                                    <a href="#" class="video_play_link w-inline-block w-lightbox">
                                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                        <script type="application/json" class="w-json">
                                            {
                                                "items": [{
                                                    "url": "https://www.youtube.com/watch?v=brLBCpUPvHA&feature=youtu.be/autoplay=1",
                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FbrLBCpUPvHA%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DbrLBCpUPvHA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FbrLBCpUPvHA%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                    "height": 480,
                                                    "width": 854,
                                                    "thumbnailUrl": "https://i.ytimg.com/vi/brLBCpUPvHA/hqdefault.jpg",
                                                    "type": "video"
                                                }],
                                                "group": ""
                                            }
                                        </script>
                                    </a>
                                    <h3 class="white_h3">Ko Samui, Tailândia</h3>
                                    <p class="white_p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
                                    <div class="_50px-div-block"></div>
                                    <a href="/places/place" class="link-block white w-inline-block">
                                        <div>leia mais</div>
                                        <div class="link_block_arrow_wrap white"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
                                    </a>
                                </div>
                                <div data-w-id="1679749b-e45b-9f8d-fc4a-0948d4b16ee9" style="
                                                background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed44d9ea0977f84cc4cc79e_denys-nevozhai-guNIjIuUcgY-unsplash%20(1).jpg');
                                                -webkit-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -moz-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -ms-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                width: 0vw;
                                            " class="conutry_slider_image"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-w-id="d6d66d08-e21b-2d0f-ad10-141922c11986" class="w-slide">
                    <div class="collection-list-wrapper-contry-slider w-dyn-list">
                        <div role="list" class="collection-list-country-slider w-dyn-items">
                            <div role="listitem" class="collection-item-country-slider w-dyn-item">
                                <div class="country_slider_content_wrap">
                                    <a href="#" class="video_play_link w-inline-block w-lightbox">
                                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                        <script type="application/json" class="w-json">
                                            {
                                                "items": [{
                                                    "url": "https://www.youtube.com/watch?v=eSrNs56ax2k&feature=youtu.be/autoplay=1",
                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FeSrNs56ax2k%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DeSrNs56ax2k&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FeSrNs56ax2k%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                    "height": 480,
                                                    "width": 854,
                                                    "thumbnailUrl": "https://i.ytimg.com/vi/eSrNs56ax2k/hqdefault.jpg",
                                                    "type": "video"
                                                }],
                                                "group": ""
                                            }
                                        </script>
                                    </a>
                                    <h3 class="white_h3">Oásis de Siuá, Egito</h3>
                                    <p class="white_p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius.</p>
                                    <div class="_50px-div-block"></div>
                                    <a href="/places/place" class="link-block white w-inline-block">
                                        <div>leia mais</div>
                                        <div class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
                                    </a>
                                </div>
                                <div style="
                                                background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed607afba2aedb76aa630e4_david-gavi-AdIJ9S-kbrc-unsplash.jpg');
                                                -webkit-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -moz-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -ms-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                            " class="conutry_slider_image"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-w-id="c638f565-8dc9-7052-22fc-9fca320cdffa" class="w-slide">
                    <div class="collection-list-wrapper-contry-slider w-dyn-list">
                        <div role="list" class="collection-list-country-slider w-dyn-items">
                            <div role="listitem" class="collection-item-country-slider w-dyn-item">
                                <div class="country_slider_content_wrap">
                                    <a href="#" class="video_play_link w-inline-block w-lightbox">
                                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                        <script type="application/json" class="w-json">
                                            {
                                                "items": [{
                                                    "url": "https://www.youtube.com/watch?v=_IRzv5UN1rU&feature=youtu.be/autoplay=1",
                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F_IRzv5UN1rU%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_IRzv5UN1rU&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F_IRzv5UN1rU%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                    "height": 480,
                                                    "width": 854,
                                                    "thumbnailUrl": "https://i.ytimg.com/vi/_IRzv5UN1rU/hqdefault.jpg",
                                                    "type": "video"
                                                }],
                                                "group": ""
                                            }
                                        </script>
                                    </a>
                                    <h3 class="white_h3">Sydney, Austrália</h3>
                                    <p class="white_p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Elementum tristique.</p>
                                    <div class="_50px-div-block"></div>
                                    <a href="/places/place" class="link-block white w-inline-block">
                                        <div>leia mais</div>
                                        <div class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
                                    </a>
                                </div>
                                <div style="
                                                background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed608592e00bf84ef793a33_paul-carmona-5UHgm0Q3n4Y-unsplash.jpg');
                                                -webkit-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -moz-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -ms-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                            " class="conutry_slider_image"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-w-id="70c13702-7615-ab3c-b710-9f091eb91346" class="w-slide">
                    <div class="collection-list-wrapper-contry-slider w-dyn-list">
                        <div role="list" class="collection-list-country-slider w-dyn-items">
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ee1e23130645f79e1439688_steven-lasry-8odmdG19pOY-unsplash.jpg');" role="listitem" class="collection-item-country-slider w-dyn-item">
                                <div class="country_slider_content_wrap">
                                    <a href="#" class="video_play_link w-inline-block w-lightbox">
                                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                        <script type="application/json" class="w-json">
                                            {
                                                "items": [{
                                                    "url": "https://www.youtube.com/watch?v=x7TAupYqN4A&feature=youtu.be/autoplay=1",
                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fx7TAupYqN4A%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dx7TAupYqN4A&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fx7TAupYqN4A%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                    "height": 480,
                                                    "width": 854,
                                                    "thumbnailUrl": "https://i.ytimg.com/vi/x7TAupYqN4A/hqdefault.jpg",
                                                    "type": "video"
                                                }],
                                                "group": ""
                                            }
                                        </script>
                                    </a>
                                    <h3 class="white_h3">Kashmir, Índia</h3>
                                    <p class="white_p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius.</p>
                                    <div class="_50px-div-block"></div>
                                    <a href="/places/place" class="link-block white w-inline-block">
                                        <div>leia mais</div>
                                        <div class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
                                    </a>
                                </div>
                                <div style="
                                                background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ee1e23130645f79e1439688_steven-lasry-8odmdG19pOY-unsplash.jpg');
                                                -webkit-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -moz-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                -ms-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                                transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                            " class="conutry_slider_image"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="left-arrow w-slider-arrow-left">
                <div class="w-icon-slider-left"></div>
            </div>
            <div class="right-arrow w-slider-arrow-right">
                <div class="w-icon-slider-right"></div>
            </div>
            <div class="slide-nav w-slider-nav w-round"></div>
        </div>
    </div> -->
    <div class="hero_content_right">
        <h1 data-w-id="c0b24185-dac0-57b4-8d4d-5298887ccbd1" style="opacity: 0;" class="max_500">A comunidade de viajantes e experiências</h1>
        <form action="/search" data-w-id="3ce17dd5-b26c-6647-fd00-bd8c01a229c3" style="opacity: 0;" class="search w-form">
            <input type="search" class="search-input w-input" maxlength="256" name="query" placeholder="O que está procurando?" id="search" required="" />
            <input type="submit" value="⌕" class="search-button w-button" />
        </form>
        <h5 data-w-id="a21895dd-411f-e4e4-4cae-4e4579e0883d" style="opacity: 0;">Últimas publicações</h5>
        <div data-w-id="65dfc437-3aff-146b-7404-d7993df99770" style="
                        -webkit-transform: translate3d(0, 100%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                        -moz-transform: translate3d(0, 100%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                        -ms-transform: translate3d(0, 100%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                        transform: translate3d(0, 100%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                        opacity: 0;
                    " class="feature_posts_contain">
            <div class="feature_posts_wrapper">
                <div class="w-dyn-list">
                    <div role="list" class="collection-list w-dyn-items">
                        <div role="listitem" class="collection-item w-dyn-item">
                            <div class="blog_cards_content">
                                <div class="top_content">
                                    <a style="background-color: #ff0149;" href="#" class="category small_on_mobile w-inline-block">
                                        <div>Experiência</div>
                                    </a>
                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="travelteller_circle on_card"></div>
                                </div>
                                <h5 class="card_title">Japão como você nunca viu</h5>
                                <a style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg');" href="/blog/post" class="card_image_hover_expand w-inline-block"></a>
                            </div>
                        </div>
                        <div role="listitem" class="collection-item w-dyn-item">
                            <div class="blog_cards_content">
                                <div class="top_content">
                                    <a style="background-color: hsla(186, 97.36%, 42.56%, 1);" href="#" class="category small_on_mobile w-inline-block">
                                        <div>Inspiração</div>
                                    </a>
                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle on_card"></div>
                                </div>
                                <h5 class="card_title">Povo e Cultura da África</h5>
                                <a style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed463e64b317b48197e2448_annie-spratt-cVEOh_JJmEE-unsplash.jpg');" href="/blog/post" class="card_image_hover_expand w-inline-block"></a>
                            </div>
                        </div>
                        <div role="listitem" class="collection-item w-dyn-item">
                            <div class="blog_cards_content">
                                <div class="top_content">
                                    <a style="background-color: #9502f3;" href="#" class="category small_on_mobile w-inline-block">
                                        <div>Cultura</div>
                                    </a>
                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');" class="travelteller_circle on_card"></div>
                                </div>
                                <h5 class="card_title">Pessoas, lugares e eventos da Índia</h5>
                                <a style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4643dec5df2a40dfcf30b_c-rayban-CIXoFys3gsw-unsplash.jpg');" href="/blog/post" class="card_image_hover_expand w-inline-block"></a>
                            </div>
                        </div>
                        <div role="listitem" class="collection-item w-dyn-item">
                            <div class="blog_cards_content">
                                <div class="top_content">
                                    <a style="background-color: #faaa04;" href="#" class="category small_on_mobile w-inline-block">
                                        <div>Lugares</div>
                                    </a>
                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle on_card"></div>
                                </div>
                                <h5 class="card_title">As diversas ilhas da Tailândia</h5>
                                <a style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');" href="/blog/post" class="card_image_hover_expand w-inline-block"></a>
                            </div>
                        </div>
                        <div role="listitem" class="collection-item w-dyn-item">
                            <div class="blog_cards_content">
                                <div class="top_content">
                                    <a style="background-color: #faaa04;" href="#" class="category small_on_mobile w-inline-block">
                                        <div>Lugares</div>
                                    </a>
                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="travelteller_circle on_card"></div>
                                </div>
                                <h5 class="card_title">Os melhores lugares do Peru para visitar</h5>
                                <a style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');" href="/blog/post" class="card_image_hover_expand w-inline-block"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div data-w-id="098da5c8-e758-47ae-168e-6b698de0cc47" style="opacity: 0;" class="confetti_contain">
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" data-w-id="a7cff586-59c8-b9f8-6957-d99b24252e05" alt="" class="image-7" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" data-w-id="fbbe3bb3-39bf-e31e-002c-35eee668f6f6" alt="" class="confetti_2" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" data-w-id="733e6ebc-4299-c5f6-8736-853dbb605ce1" alt="" class="confetti_3" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" data-w-id="eaa32421-c175-a8d7-ab09-f4d7b391194c" alt="" class="confetti_4" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" data-w-id="afc9a33d-b92b-2f44-ccce-278a4c1e1a69" alt="" class="confetti_5" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" data-w-id="88032074-eb00-ad7d-5434-ad93991f73e4" alt="" class="confetti_6" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" data-w-id="cf3cbd97-4f89-7190-030f-f6d1f3fcf31c" alt="" class="confetti_7" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" data-w-id="92e85721-d4ac-0667-87c4-cbec73ae22e5" alt="" class="confetti_17" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" data-w-id="e941a6a9-ec0e-d5bf-ed16-33d1363fbc4c" alt="" class="confetti_8" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" data-w-id="9f8ae5e5-9408-eda9-155f-fb25cd09c201" alt="" class="confetti_9" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" data-w-id="2fab8808-f26c-4ced-87a7-53170e9f5d27" alt="" class="confetti_10" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" data-w-id="75616927-e50b-58f2-15f0-991e3dc854c9" alt="" class="confetti_16" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" data-w-id="f3b38cee-899e-cec2-7edf-9fc00541e5e0" alt="" class="confetti_11" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" data-w-id="294dba0f-0e22-6c30-0b4a-b59edf4143c9" alt="" class="confetti_12" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" data-w-id="5fda1dc3-893a-dfe0-6550-0e276b480324" alt="" class="confetti_13" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" data-w-id="64d2550f-52ea-94a7-ce30-c900cc08947f" alt="" class="confetti_14" />
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" data-w-id="d8e14f27-3b19-4f24-3bb2-c7a7e4c72a3a" alt="" class="confetti_15" />
        </div>
    </div>
</div>
<!-- <div class="section light_grey wf-section">
    <div class="conatiner"></div>
    <div class="container">
        <h2 data-w-id="1b062139-faad-fee2-c02a-b49d1260ff8f">Experiências</h2>
        <div class="flex">
            <div data-duration-in="300" data-duration-out="100" data-current="Tab 2" data-easing="ease" class="tabs w-tabs">
                <div data-w-id="63335641-77b7-2165-c2c2-35dd0df72ec7" class="story-feed-tab-menu w-tab-menu">
                    <a data-w-tab="Tab 1" class="tab-link-tab-1 w-inline-block w-tab-link">
                        <div>Destaques</div>
                    </a>
                    <a data-w-tab="Tab 2" class="tab-link w-inline-block w-tab-link w--current">
                        <div>Recentes</div>
                    </a>
                </div>
                <div class="tabs-content w-tab-content">
                    <div data-w-tab="Tab 1" class="tab-pane-tab-1 w-tab-pane">
                        <div class="flex">
                            <div class="w-layout-grid grid">
                                <div class="blog-collection-list-wrapper w-dyn-list">
                                    <div role="list" class="w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/post" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');" class="story_image">
                                                    <div style="background-color: #faaa04;" class="category">
                                                        <div>Lugares</div>
                                                    </div>
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');" class="card_image_hover_expand"></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Os melhores lugares do Peru para visitar</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum.</p>
                                                    <div class="travelteller_wrap">
                                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="travelteller_circle"></div>
                                                        <h6>Lorem ipsum</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/post" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');" class="story_image">
                                                    <div style="background-color: #faaa04;" class="category">
                                                        <div>Lugares</div>
                                                    </div>
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');" class="card_image_hover_expand"></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>As diversas ilhas da Tailândia</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                                    <div class="travelteller_wrap">
                                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle"></div>
                                                        <h6>Lorem ipsum</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/post" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4643dec5df2a40dfcf30b_c-rayban-CIXoFys3gsw-unsplash.jpg');" class="story_image">
                                                    <div style="background-color: #9502f3;" class="category">
                                                        <div>Cultura</div>
                                                    </div>
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4643dec5df2a40dfcf30b_c-rayban-CIXoFys3gsw-unsplash.jpg');" class="card_image_hover_expand"></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Pessoas, lugares e eventos da Índia</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique antih.</p>
                                                    <div class="travelteller_wrap">
                                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');" class="travelteller_circle"></div>
                                                        <h6>Lorem ipsum</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/post" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed463e64b317b48197e2448_annie-spratt-cVEOh_JJmEE-unsplash.jpg');" class="story_image">
                                                    <div style="background-color: hsla(186, 97.36%, 42.56%, 1);" class="category">
                                                        <div>Inspiração</div>
                                                    </div>
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed463e64b317b48197e2448_annie-spratt-cVEOh_JJmEE-unsplash.jpg');" class="card_image_hover_expand"></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Povo e Cultura da África</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
                                                    <div class="travelteller_wrap">
                                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle"></div>
                                                        <h6>Lorem ipsum</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div data-w-tab="Tab 2" class="w-tab-pane w--tab-active">
                        <div class="w-layout-grid grid">
                            <div class="blog-collection-list-wrapper w-dyn-list">
                                <div role="list" class="w-dyn-items">
                                    <div role="listitem" class="w-dyn-item">
                                        <a data-w-id="c37d1e11-495d-e825-2cec-4af2927ec093" href="/blog/post" class="story_wrap w-inline-block">
                                            <div class="story_image">
                                                <div style="background-color: hsla(186, 97.36%, 42.56%, 1);" class="category">
                                                    <div>Inspiração</div>
                                                </div>
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed463e64b317b48197e2448_annie-spratt-cVEOh_JJmEE-unsplash.jpg');" class="card_image_hover_expand"></div>
                                            </div>
                                            <div class="story_content">
                                                <h4>Povo e Cultura da África</h4>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
                                                <div class="travelteller_wrap">
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle"></div>
                                                    <h6>Lorem ipsum</h6>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div role="listitem" class="w-dyn-item">
                                        <a data-w-id="c37d1e11-495d-e825-2cec-4af2927ec093" href="/blog/post" class="story_wrap w-inline-block">
                                            <div class="story_image">
                                                <div style="background-color: #9502f3;" class="category">
                                                    <div>Cultura</div>
                                                </div>
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4643dec5df2a40dfcf30b_c-rayban-CIXoFys3gsw-unsplash.jpg');" class="card_image_hover_expand"></div>
                                            </div>
                                            <div class="story_content">
                                                <h4>Pessoas, lugares e eventos da Índia</h4>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique antih.</p>
                                                <div class="travelteller_wrap">
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');" class="travelteller_circle"></div>
                                                    <h6>Lorem ipsum</h6>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div role="listitem" class="w-dyn-item">
                                        <a data-w-id="c37d1e11-495d-e825-2cec-4af2927ec093" href="/blog/post" class="story_wrap w-inline-block">
                                            <div class="story_image">
                                                <div style="background-color: #ff0149;" class="category">
                                                    <div>Experiência</div>
                                                </div>
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg');" class="card_image_hover_expand"></div>
                                            </div>
                                            <div class="story_content">
                                                <h4>Japão como você nunca viu</h4>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Lorem ipsum dolor sit amet.</p>
                                                <div class="travelteller_wrap">
                                                    <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="travelteller_circle"></div>
                                                    <h6>Lorem ipsum</h6>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div data-w-id="765215f1-1497-d971-58e3-e619476c727a" class="top_traveltellers">
                <h5>Viajantes</h5>
                <div class="line div"></div>
                <div class="top_traveltellers_collection-list-wrapper w-dyn-list">
                    <div role="list" class="top-travellers-collection-list w-dyn-items">
                        <div role="listitem" class="top-travellers-collection-item w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Rachelle Mindy</h5>
                                    <div class="text_block">New York, USA</div>
                                </div>
                            </a>
                        </div>
                        <div role="listitem" class="top-travellers-collection-item w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Mason Miller</h5>
                                    <div class="text_block">Amsterdam, Netherlands</div>
                                </div>
                            </a>
                        </div>
                        <div role="listitem" class="top-travellers-collection-item w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Natasha Miles</h5>
                                    <div class="text_block">Paris, France</div>
                                </div>
                            </a>
                        </div>
                        <div role="listitem" class="top-travellers-collection-item w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Michelle Worthy</h5>
                                    <div class="text_block">Melbourne, Australia</div>
                                </div>
                            </a>
                        </div>
                        <div role="listitem" class="top-travellers-collection-item w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Jason Maddock</h5>
                                    <div class="text_block">Chicago, USA</div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="_30px-div"></div>
                <h5>Categorias</h5>
                <div class="line div"></div>
                <div class="blog_categories_contain">
                    <div class="w-dyn-list">
                        <div role="list" class="category-tags-collection-list w-dyn-items">
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #faaa04;" href="/blog/category" class="category with-margin w-inline-block">
                                    <div>Lugares</div>
                                </a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #03c1d6;" href="/blog/category" class="category with-margin w-inline-block">
                                    <div>Inspiração</div>
                                </a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #9502f3;" href="/blog/category" class="category with-margin w-inline-block">
                                    <div>Cultura</div>
                                </a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #ff0149;" href="/blog/category" class="category with-margin w-inline-block">
                                    <div>Experiência</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="view_all_link">
            <div class="line"></div>
            <a data-w-id="7bac7109-c948-537b-e0f4-d6da12386726" href="/blog" class="link-block w-inline-block">
                <div>ver tudo</div>
                <div style="background-color: rgba(35, 34, 34, 0.2);" class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
            </a>
        </div>
    </div>
</div> -->
<div class="section videos wf-section" id="section-1">
    <div class="container">
        <div data-w-id="6f8a05ad-fbdc-08c0-7ff1-2a5ae3823967">
            <h2>Quero saber o que é intercâmbio</h2>
            <p class="max_550">
                Aqui você vai encontrar  tudo o que você precisa saber sobre o intercâmbio: o que é, para que serve e quem pode fazer.
            </p>
        </div>
        <a data-w-id="92b55dee-3ea0-cd49-b7fe-9cf4b45d25ef" href="#" class="link-block w-inline-block">
            <div>ver tudo</div>
            <div style="background-color: rgba(35, 34, 34, 0.2);" class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
        </a>
        <div class="w-layout-grid videos_display_grid">
            <div class="featured-videos-collection-list-wrapper w-dyn-list">
                <div role="list" class="videos-collection-list w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="4762d817-fbdf-2d04-25c4-4c577c7357b6" style="background-image: url('/public/assets/images/thumb/1.png');" class="story_image video">
                            <!-- <h5 class="card_title">New Zealand&#x27;s Vast Land</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                            <div class="featured_video">
                                <div class="text_block white">Destaque</div>
                            </div>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="4762d817-fbdf-2d04-25c4-4c577c7357b6" style="background-image: url('/public/assets/images/thumb/2.png');" class="story_image video">
                            <!-- <h5 class="card_title">New York City Views</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                            <div class="featured_video">
                                <div class="text_block white">Destaque</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="w-dyn-list">
                <div role="list" class="videos-collection-list row_2 w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/3.png');" class="story_image video">
                            <!-- <h5 class="card_title">Discovering Greece</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/4.png');" class="story_image video">
                            <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/5.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/6.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-w-id="23ef4960-f982-5bc0-827c-22bbdc3aedb7" style="opacity: 0;" class="confetti_contain fold-2">
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" alt="" class="image-7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" alt="" class="confetti_2" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" alt="" class="confetti_3" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" alt="" class="confetti_4" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" alt="" class="confetti_5" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_6" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" alt="" class="confetti_7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_17" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_8" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" alt="" class="confetti_9" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" alt="" class="confetti_10" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_16" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_11" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_12" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" alt="" class="confetti_13" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" alt="" class="confetti_14" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" alt="" class="confetti_15" />
    </div>
</div>

<div class="section videos wf-section" id="section-2">
    <div class="container">
        <div class="w-layout-grid videos_display_grid">
            <div class="featured-videos-collection-list-wrapper w-dyn-list">
                <div role="list" class="videos-collection-list w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div class="uk-padding">
                            <h2>Tenho dúvidas sobre intercâmbio</h2>
                            <p class="max_550">
                                Com nosso material gratuito, você pode tirar suas principais dúvidas sobre intercâmbio. É só se cadastrar para receber. 
                            </p>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="4762d817-fbdf-2d04-25c4-4c577c7357b6" style="background-image: url('/public/assets/images/thumb/7.png');" class="story_image video">
                            <!-- <h5 class="card_title">New Zealand&#x27;s Vast Land</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                            <div class="featured_video">
                                <div class="text_block white">Destaque</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="w-dyn-list">
                <div role="list" class="videos-collection-list row_2 w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/8.png');" class="story_image video">
                            <!-- <h5 class="card_title">Discovering Greece</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/9.png');" class="story_image video">
                            <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/10.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/11.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="w-dyn-list">
                <div role="list" class="videos-collection-list row_2 w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/12.png');" class="story_image video">
                            <!-- <h5 class="card_title">Discovering Greece</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/13.png');" class="story_image video">
                            <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/14.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/15.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/16.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/17.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/18.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-w-id="23ef4960-f982-5bc0-827c-22bbdc3aedb7" style="opacity: 0;" class="confetti_contain fold-2">
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" alt="" class="image-7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" alt="" class="confetti_2" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" alt="" class="confetti_3" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" alt="" class="confetti_4" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" alt="" class="confetti_5" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_6" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" alt="" class="confetti_7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_17" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_8" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" alt="" class="confetti_9" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" alt="" class="confetti_10" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_16" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_11" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_12" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" alt="" class="confetti_13" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" alt="" class="confetti_14" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" alt="" class="confetti_15" />
    </div>
</div>

<div class="section videos wf-section" id="section-3">
    <div class="container">
        <div data-w-id="6f8a05ad-fbdc-08c0-7ff1-2a5ae3823967">
            <h2>Qual o intercâmbio ideal</h2>
            <p class="max_550">
                Aqui, você vai entender qual é o programa de intercâmbio e o país que mais combina com você e com seus objetivos.
            </p>
        </div>
        <a data-w-id="92b55dee-3ea0-cd49-b7fe-9cf4b45d25ef" href="#" class="link-block w-inline-block">
            <div>ver tudo</div>
            <div style="background-color: rgba(35, 34, 34, 0.2);" class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
        </a>
        <br />
        <div class="uk-child-width-1-5@s" uk-grid>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/19.png');" class="story_image video">
                    <!-- <h5 class="card_title">Discovering Greece</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/20.png');" class="story_image video">
                    <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/21.png');" class="story_image video">
                    <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/1.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/2.png');" class="story_image video">
                    <!-- <h5 class="card_title">Discovering Greece</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/3.png');" class="story_image video">
                    <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/4.png');" class="story_image video">
                    <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/5.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/6.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/7.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/8.png');" class="story_image video">
                    <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/9.png');" class="story_image video">
                    <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/10.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/11.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
            <div>
                <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/12.png');" class="story_image video">
                    <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                    <a href="/blog/post" class="video_play_link w-inline-block">
                        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div data-w-id="23ef4960-f982-5bc0-827c-22bbdc3aedb7" style="opacity: 0;" class="confetti_contain fold-2">
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" alt="" class="image-7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" alt="" class="confetti_2" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" alt="" class="confetti_3" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" alt="" class="confetti_4" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" alt="" class="confetti_5" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_6" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" alt="" class="confetti_7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_17" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_8" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" alt="" class="confetti_9" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" alt="" class="confetti_10" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_16" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_11" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_12" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" alt="" class="confetti_13" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" alt="" class="confetti_14" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" alt="" class="confetti_15" />
    </div>
</div>

<div class="section videos wf-section" id="section-4">
    <div class="container">
        <div data-w-id="6f8a05ad-fbdc-08c0-7ff1-2a5ae3823967">
            <h2>Conheça de perto conteúdo<br /> de organizações internacionais</h2>
            <p class="max_550">
            Conheça de perto as escolas de idiomas ao redor do mundo. 
            </p>
        </div>
        <a data-w-id="92b55dee-3ea0-cd49-b7fe-9cf4b45d25ef" href="#" class="link-block w-inline-block">
            <div>ver tudo</div>
            <div style="background-color: rgba(35, 34, 34, 0.2);" class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
        </a>
<br />
        <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1" uk-slider>

            <ul class="uk-slider-items uk-child-width-1-2 uk-child-width-1-4@m uk-grid">
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/1.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/2.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/3.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/4.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/5.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/6.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/thumb/7.png" alt="" />
                    </div>
                </li>
            </ul>

            <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
            <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>

        </div>
    </div>
    <div data-w-id="23ef4960-f982-5bc0-827c-22bbdc3aedb7" style="opacity: 0;" class="confetti_contain fold-2">
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" alt="" class="image-7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" alt="" class="confetti_2" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" alt="" class="confetti_3" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" alt="" class="confetti_4" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" alt="" class="confetti_5" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_6" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" alt="" class="confetti_7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_17" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_8" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" alt="" class="confetti_9" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" alt="" class="confetti_10" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_16" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_11" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_12" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" alt="" class="confetti_13" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" alt="" class="confetti_14" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" alt="" class="confetti_15" />
    </div>
</div>

<div class="section videos wf-section" id="section-5">
    <div class="container">
        <div data-w-id="6f8a05ad-fbdc-08c0-7ff1-2a5ae3823967">
            <h2>Aprenda com quem já fez intercâmbio</h2>
            <p class="max_550">
            Conheça a experiência de quem já fez ou está fazendo intercâmbio e fique por dentro de tudo sobre intercâmbio.
            </p>
        </div>
        <a data-w-id="92b55dee-3ea0-cd49-b7fe-9cf4b45d25ef" href="#" class="link-block w-inline-block">
            <div>ver tudo</div>
            <div style="background-color: rgba(35, 34, 34, 0.2);" class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
        </a>
        <div class="w-layout-grid videos_display_grid">
            <div class="w-dyn-list">
                <div role="list" class="videos-collection-list row_2 w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/13.png');" class="story_image video">
                            <!-- <h5 class="card_title">Discovering Greece</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/14.png');" class="story_image video">
                            <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/15.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/16.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-w-id="23ef4960-f982-5bc0-827c-22bbdc3aedb7" style="opacity: 0;" class="confetti_contain fold-2">
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" alt="" class="image-7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" alt="" class="confetti_2" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" alt="" class="confetti_3" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" alt="" class="confetti_4" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" alt="" class="confetti_5" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_6" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" alt="" class="confetti_7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_17" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_8" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" alt="" class="confetti_9" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" alt="" class="confetti_10" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_16" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_11" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_12" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" alt="" class="confetti_13" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" alt="" class="confetti_14" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" alt="" class="confetti_15" />
    </div>
</div>

<div class="section videos wf-section" id="section-6">
    <div class="container">
        <div class="w-layout-grid videos_display_grid">
            <div class="featured-videos-collection-list-wrapper w-dyn-list">
                <div role="list" class="videos-collection-list w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div class="uk-padding">
                            <h2>Conhecer o mundo do intercâmbio virtualmente</h2>
                            <p class="max_550">
                                Assista vídeos em 360 graus com detalhes de cidades que podem ser o seu destino de intercâmbio.
                            </p>
                            <a data-w-id="92b55dee-3ea0-cd49-b7fe-9cf4b45d25ef" href="#" class="link-block w-inline-block">
                                <div>ver tudo</div>
                                <div style="background-color: rgba(35, 34, 34, 0.2);" class="link_block_arrow_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed454fe97a20a290890dc60_arrow.svg" width="5" alt="" /></div>
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="4762d817-fbdf-2d04-25c4-4c577c7357b6" style="background-image: url('/public/assets/images/thumb/17.png');" class="story_image video">
                            <!-- <h5 class="card_title">New Zealand&#x27;s Vast Land</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                            <div class="featured_video">
                                <div class="text_block white">Destaque</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="w-dyn-list">
                <div role="list" class="videos-collection-list row_2 w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/18.png');" class="story_image video">
                            <!-- <h5 class="card_title">Discovering Greece</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/19.png');" class="story_image video">
                            <!-- <h5 class="card_title">The Most Beautiful Island in the World</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/20.png');" class="story_image video">
                            <!-- <h5 class="card_title">My Vietnam Trip</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/21.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/1.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div data-w-id="39285704-a621-d710-7503-81cf37fd55dc" style="background-image: url('/public/assets/images/thumb/2.png');" class="story_image video">
                            <!-- <h5 class="card_title">A Castle On an Island</h5> -->
                            <a href="/blog/post" class="video_play_link w-inline-block">
                                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div data-w-id="23ef4960-f982-5bc0-827c-22bbdc3aedb7" style="opacity: 0;" class="confetti_contain fold-2">
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34fe669126b653cdba_blue%20arrow.svg" alt="" class="image-7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3466757f14b84074f5_yellow%20arrow.svg" alt="" class="confetti_2" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de347da4562e4d63d82b_pink%20arrow%20down.svg" alt="" class="confetti_3" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33b71cb4539b77ba4c_purple%20long.svg" alt="" class="confetti_4" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de337d47076f91a9863d_blue%20long.svg" alt="" class="confetti_5" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_6" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de3440ea6eec69d5b599_teal%20long.svg" alt="" class="confetti_7" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_17" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de349f823009f0dcc235_pink%20arrow%20up.svg" alt="" class="confetti_8" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de341f08218537c1879d_Teal%20arrow.svg" alt="" class="confetti_9" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" alt="" class="confetti_10" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_16" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de33bc35f7c70dc93732_yellow%20long.svg" alt="" class="confetti_11" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="11" alt="" class="confetti_12" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de34187c83699e66f403_purple%20arrow%20down.svg" alt="" class="confetti_13" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="6" alt="" class="confetti_14" />
        <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee5de324741102d8032e7ce_blue%20circle.svg" width="10" alt="" class="confetti_15" />
    </div>
</div>

<!-- <div class="section full_width wf-section">
    <div class="full_width_image-wrap">
        <div class="container signup_form">
            <div class="newsletter_h_contain">
                <h2 class="white_h2 newsletter_title">Inscreva-se para receber as novidades</h2>
                <p class="white_p newsletter_p">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo.
                </p>
            </div>
            <div class="form-block w-form">
                <form id="email-form" name="email-form" data-name="Email Form" method="get" class="form">
                    <input type="text" class="text-field w-input" maxlength="256" name="name" placeholder="Nome*" required="" />
                    <input type="text" class="text-field w-input" maxlength="256" name="phone" placeholder="Telefone*" required="" />
                    <input type="email" class="text-field w-input" maxlength="256" name="email" placeholder="E-mail*" id="Email-Address" required="" />
                    <input type="submit" value="Enviar inscrição" data-wait="Aguarde..." class="submit-button w-button" />
                </form>
                <div class="success-message w-form-done">
                    <div>Obrigado! Sua inscrição foi recebida!</div>
                </div>
                <div class="w-form-fail">
                    <div>Oops! Não conseguimos completar sua solicitação.</div>
                </div>
            </div>
        </div>
        <div data-w-id="76fd4d71-c047-80c2-5226-3a0e10fb1133" class="full_width_image"></div>
    </div>
</div> -->
<!-- <div class="section cta_section wf-section">
    <div class="container">
        <div class="w-layout-grid cta_with_parallex_imgs">
            <div data-w-id="981020ba-d567-d915-cbd1-8a938b4b546d" class="cta_left">
                <h3>Bem vindo viajantes</h3>
                <p class="max_400">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.
                    Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.
                </p>
                <a href="#" class="button w-button">Começar agora!</a>
                <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg" width="283" style="opacity: 0;" data-w-id="9053eb46-379e-6808-e5de-e1864ea46e61" alt="" class="cta_section_stencil" />
            </div>
            <div data-w-id="d4412a17-fb43-3c7d-81fa-c8600f8d1278" class="parallex_images_contain">
                <div data-w-id="3a594360-bc90-fe1d-3079-c88cb9e8a003" class="parallex_image _2"></div>
                <div data-w-id="3c8c4ab8-0561-8a75-611a-4e4c16f240a3" class="parallex_image"></div>
                <div data-w-id="d46dcf38-46f6-5fab-4245-85d4454ca480" class="parallex_image _4"></div>
                <div data-w-id="24f4efc7-3c14-8900-3eaa-328c0d644e0c" class="parallex_image _3"></div>
            </div>
        </div>
    </div>
</div> -->
</body>
</html>