<section class="uk-section on-border-bottom" id="inicio">

    <div class="uk-container">
        <div class="uk-flex uk-flex-middle uk-text-center uk-text-left@s" uk-grid>
            <div class="uk-width-1-2@s">
                <h1 class="uk-h1">Criamos <span class="uk-text-primary">Sites e Campanhas</span> incríveis</h1>
                <p class="uk-text-lead">Nosso objetivo é explorar o melhor de cada <strong>Projeto</strong> que criamos e entregar informações pertinentes para nossos clientes.</p>
                <a class="uk-button uk-button-default" href="#servicos">Saiba Mais <span uk-icon="icon: arrow-down"></span></a>
            </div>
            <div class="uk-width-1-2@s uk-text-center">
                <img src="/public/assets/images/logotipo/logotipo.svg" alt="Logotipo" />
            </div>
        </div>
    </div>
</section>

<section class="uk-section uk-section-secondary uk-padding-remove on-border-bottom">
    <div class="uk-container">
        <div class="uk-position-relative" uk-slider>

            <ul class="uk-slider-items uk-child-width-1-1 uk-child-width-1-4@m uk-grid uk-grid-divider">
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-dzae.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-bancadecriacao.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-publiclick.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-quality.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-wtech.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-giga.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-ss.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-pegpese.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-frugal.png" alt="" />
                    </div>
                </li>
                <li>
                    <div class="uk-panel">
                        <img src="/public/assets/images/client/client-hetros.png" alt="" />
                    </div>
                </li>
            </ul>

            <a class="uk-position-center-left uk-position-small" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
            <a class="uk-position-center-right uk-position-small" href="#" uk-slidenav-next uk-slider-item="next"></a>

        </div>
    </div>
</section>

<section class="uk-section on-border-bottom" id="servicos">
    <div class="uk-container">
        <div uk-grid>
            <div class="uk-width-1-1@s">
                <h2 class="uk-h2">Nossos Serviços</h2>
                <p class="uk-text-lead">Conheça alguns dos serviços que oferecemos para nossos clientes.</p>
            </div>
            <div class="uk-child-width-1-4@s uk-grid-small uk-grid-match" uk-grid>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/design.png);"></div>
                        <h3 class="uk-h3">Design Gráfico</h3>
                        <p class="uk-text-meta">Entendemos que o design gráfico é um processo único de criação onde encontramos a identidade da sua empresa, na qual definimos aonde você quer chegar!</p>
                    </div>
                </div>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/code.png);"></div>
                        <h3 class="uk-h3">Criação de Site</h3>
                        <p class="uk-text-meta">Com nossa experiência e estratégia criamos sites profissionais com layout exclusivo e otimizado, para segmentos como agências, varejo, ONGs, entre outros.</p>
                    </div>
                </div>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/social.png);"></div>
                        <h3 class="uk-h3">Gestão de Mídias</h3>
                        <p class="uk-text-meta">Gerenciamos conteúdo para as páginas de uma marca ou empresa nas redes sociais. Planejamos estratégias e analisamos resultados para alcançar um objetivo definido.</p>
                    </div>
                </div>
                <div>
                    <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                        <div class="on-card-icon uk-border-radius" style="background-image: url(/public/assets/images/icons/ad.png);"></div>
                        <h3 class="uk-h3">Gestão de Tráfego</h3>
                        <p class="uk-text-meta">Gerenciamos conteúdo para as páginas de uma marca ou empresa nas redes sociais. Planejamos estratégias e analisamos resultados para alcançar um objetivo definido.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="uk-section uk-section-secondary uk-preserve-color on-border-bottom" id="projetos">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-3@s">
                <h3 class="uk-h2">Projetos</h3>
                <p class="uk-text-lead">Conheça alguns dos nossos projetos concluídos.</p>
                <div class="uk-child-width-1-1@s" uk-grid>
                    <div>
                        <h4 class="uk-h4 uk-text-large uk-text-primary uk-margin-remove">+ 100</h4>
                        <p class="uk-text-meta uk-margin-remove">Projetos Concluídos</p>

                    </div>
                    <div>
                        <h4 class="uk-h4 uk-text-large uk-text-primary uk-margin-remove">+ 6</h4>
                        <p class="uk-text-meta uk-margin-remove">Anos de Experiência</p>

                    </div>
                    <div>
                        <h4 class="uk-h4 uk-text-large uk-text-primary uk-margin-remove">+ 71.293.331</h4>
                        <p class="uk-text-meta uk-margin-remove">Leads Geradas</p>

                    </div>
                </div>

            </div>
            <div class="uk-width-2-3@s">
                <div class="uk-position-relative" uk-slider="draggable: false">
                    <ul class="uk-slider-items uk-grid on-slider-portfolio">
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/absafe.com.br.webp" alt="">
                                <!-- <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> -->
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/myrental.com.br.webp" alt="">
                                <!-- <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> -->
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/absafe.com.br.webp" alt="">
                                <!-- <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> -->
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/myrental.com.br.webp" alt="">
                                <!-- <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> -->
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/absafe.com.br.webp" alt="">
                                <!-- <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> -->
                            </div>
                        </li>
                        <li class="uk-width-3-5">
                            <div class="uk-panel">
                                <img src="/public/assets/images/portfolio/myrental.com.br.webp" alt="">
                                <!-- <div class="uk-position-center uk-text-center">
                                        <h2 uk-slider-parallax="x: 100,-100">Heading</h2>
                                        <p uk-slider-parallax="x: 200,-200">Lorem ipsum dolor sit amet.</p>
                                    </div> -->
                            </div>
                        </li>
                    </ul>
                    <a class="uk-position-center-left" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="uk-section on-border-bottom" id="servicos">
    <div class="uk-container">
        <div uk-grid>
            <div class="uk-width-1-1@s">
                <h2 class="uk-h2">Blog</h2>
                <p class="uk-text-lead">Confira as últimas publicações da semana.</p>
            </div>
        </div>
        <div class="uk-child-width-1-3@s uk-grid-small uk-grid-match on-post-last" uk-grid>
            <div>
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <div class="ui inverted placeholder">
                        <div class="square image"></div>
                        <div class="header">
                            <div class="line"></div>
                        </div>
                        <div class="paragraph">
                            <div class="line"></div>
                            <div class="line"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <div class="ui inverted placeholder">
                        <div class="square image"></div>
                        <div class="header">
                            <div class="line"></div>
                        </div>
                        <div class="paragraph">
                            <div class="line"></div>
                            <div class="line"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <div class="ui inverted placeholder">
                        <div class="square image"></div>
                        <div class="header">
                            <div class="line"></div>
                        </div>
                        <div class="paragraph">
                            <div class="line"></div>
                            <div class="line"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="uk-section on-border-bottom" id="contato">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-2@s">
                <h2 class="uk-h2">Fale Conosco</h2>
                <p class="uk-text-lead">Estamos prontos para tirar suas dúvidas a qualquer hora, utilize um dos nossos canais de atendimento.</p>
                <hr class="uk-divider-small" />
                <div class="uk-card uk-card-body uk-card-default uk-border-radius uk-margin-bottom">
                    <h3 class="uk-h3">São Paulo - SP</h3>
                    <p class="uk-text-meta">Rua Elias Antonio Zogbi, 150. Santo Amaro. 04746-115</p>
                    <p class="uk-text-meta">+55 (11) 95327-0722</p>
                </div>
            </div>
            <div class="uk-width-1-2@s">
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <form class="ui form on-form-contact">
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field required">
                                    <label>Nome</label>
                                    <input type="text" name="name" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-2@s">
                                <div class="field required">
                                    <label>Telefone</label>
                                    <input type="text" name="phone" class="on-mask-phone" />
                                </div>
                            </div>
                            <div class="uk-width-1-2@s">
                                <div class="field required">
                                    <label>E-mail</label>
                                    <input type="text" name="email" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field">
                                    <label>Mensagem</label>
                                    <textarea name="message" rows="3"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field">
                                    <button class="uk-button uk-button-primary">Enviar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>