<div class="uk-visible@s" uk-grid>
    <div class="uk-width-expand@s">
        <ul class="uk-breadcrumb">
            <li><a href="<?php echo $this->baseUrl('account') ?>">Início</a></li>
            <li><a href="<?php echo $this->baseUrl('project') ?>">Projeto: <b class="site">...</b></a></li>
            <li><span><?php echo $this->title ?></span></li>
        </ul>
    </div>
</div>
<hr class="uk-divider-small uk-visible@s" />
<div uk-grid>
    <div class="uk-width-medium@s uk-visible@m">
        <div class="uk-card uk-card-default uk-card-body uk-border-rounded">
            <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
                <?php echo $this->menu($this->title, 1) ?>
            </ul>
        </div>
    </div>
    <div class="uk-width-expand@s">
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded">
            <button class="uk-button uk-button-primary uk-border-rounded b-ins transition hidden">Criar Mensagem</button>
            <button class="uk-button uk-button-primary uk-border-rounded b-up">Confirmar Dados</button>
        </div>
        <hr class="uk-divider-small uk-visible@s" />
        <table class="ui celled inverted table">
            <thead >
                <tr>
                    <th><span uk-icon="icon: hashtag"></span></th>
                    <th>Historico de Mensagens</th>
                    <th>Enviado Há</th>
                </tr>
            </thead>
        </table>
    </div>
    <div class="uk-width-medium@s uk-visible@s">
        <div class="uk-card uk-card-default uk-card-body uk-border-rounded uk-margin-bottom">
            <div class="nome_sobrenome_chars" style="background-color: rgba(0, 0, 0, .8); width: 60px; height: 60px; border-radius: 50%; color: #ffffff; font-size: 20px; padding: 20px; margin: 0 auto;">...</div>
            <h4 class="uk-h4 uk-text-center uk-margin-top nome_sobrenome">...</h4>
        </div>
        <div class="uk-card uk-card-default uk-card-body uk-card-small uk-border-rounded">
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Status:</h5>
            <p class="uk-text-meta uk-margin-remove-top descricao_status">...</p>
            <h5 class="uk-h5 uk-margin-remove-top uk-margin-remove-bottom">Enviado há:</h5>
            <p class="uk-text-meta uk-margin-remove-top data_hora">...</p>
            <hr class="uk-divider-small" />
            <pre class="on-fields"></pre>
        </div>
    </div>
</div>