<div class="section login_section wf-section">
    <div class="registration_form_block w-form">
        <form data-name="Sign Up Form" name="wf-form-Sign-Up-Form" id="wf-form-Sign-Up-Form" method="get" class="registration-form" aria-label="Sign Up Form">
            <a href="/" class="home-link w-inline-block">
                    <img src="/public/assets/images/logotipo.png" width="200" alt="" class="login-logo-image" />
            </a>
            <div>
                <h3>Registre-se para explorar!</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
            </div>
            <div class="_50_percent_field_contain-2">
                <input type="text" class="text-field _50_percent w-input" maxlength="256" name="First-Name" data-name="First Name" placeholder="Nome*" id="First-Name" required="" />
                <input type="text" class="text-field _50_percent w-input" maxlength="256" name="Last-Name" data-name="Last Name" placeholder="Telefone*" id="Last-Name" required="" />
            </div>
            <div class="_50_percent_field_contain-2">
                <input type="email" class="text-field _50_percent w-input" maxlength="256" name="email" data-name="Email" placeholder="E-mail" id="field" required="" />
                <input type="password" class="text-field _50_percent w-input" maxlength="256" name="Password" data-name="Password" placeholder="Senha" id="Password" required="" />
            </div>
            <input type="submit" value="Registrar" data-wait="Please wait..." class="button sign-in-button w-button" />
            <div>
                <div class="already_have_account">Já tem uma conta? <a href="/sign-in" class="text_link">Faça login.</a></div>
            </div>
        </form>
        <div class="success-message w-form-done" tabindex="-1" role="region" aria-label="Sign Up Form success">
            <div>Welcome to TravelTell! Please check your email to verify your account.</div>
            <a href="/" class="button w-button">Home</a>
        </div>
        <div class="w-form-fail" tabindex="-1" role="region" aria-label="Sign Up Form failure"><div>Oops! Something went wrong while submitting the form.</div></div>
    </div>
    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg" width="313" alt="" class="confetti_hero_svg sign-up" />
</div>
