
<div class="uk-panel uk-margin-bottom">
    <ul class="uk-breadcrumb uk-light">
        <li><a href="/account/dashboard">Início</a></li>
        <li><span><?php echo $this->title_page ?></span></li>
    </ul>
</div>

<div class="uk-panel uk-margin-bottom">
    <button class="ui primary button on-button-insert">
        Novo Registro
    </button>
</div>

<div class="uk-card uk-card-body uk-card-muted uk-card-small">
    <table class="ui inverted very basic compact table on-table-cost-center">
        <thead>
            <tr>
                <th>ID</th>
                <th></th>
                <th>Descrição</th>
                <th>Opções</th>
            </tr>
        </thead>
    </table>
</div>

<div class="ui small modal on-modal-insert">
    <div class="header">Novo Registro</div>
    <div class="content">
        <form class="ui form on-form-insert">
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-1">
                    <div class="field required">
                        <label>Descrição</label>
                        <input type="text" name="name_cost_center" maxlength="128" />
                    </div>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Icon</label>
                        <div class="ui fluid selection dropdown on-icon-cost-dropdown">
                            <input type="hidden" name="icon_cost_center">
                            <i class="dropdown icon"></i>
                            <div class="default text">Selecione...</div>
                            <div class="menu">
                                <div class="item" data-value="clipboard check">
                                    <i class="clipboard check icon"></i>
                                </div>
                                <div class="item" data-value="utensils">
                                    <i class="utensils icon"></i>
                                </div>
                                <div class="item" data-value="pencil alternate">
                                    <i class="pencil alternate icon"></i>
                                </div>
                                <div class="item" data-value="minus">
                                    <i class="minus icon"></i>
                                </div>
                                <div class="item" data-value="file">
                                    <i class="file icon"></i>
                                </div>
                                <div class="item" data-value="chart line">
                                    <i class="chart line icon"></i>
                                </div>
                                <div class="item" data-value="gamepad">
                                    <i class="gamepad icon"></i>
                                </div>
                                <div class="item" data-value="shopping cart">
                                    <i class="shopping cart icon"></i>
                                </div>
                                <div class="item" data-value="home">
                                    <i class="home icon"></i>
                                </div>
                                <div class="item" data-value="ellipsis horizontal">
                                    <i class="ellipsis horizontal icon"></i>
                                </div>
                                <div class="item" data-value="paw">
                                    <i class="paw icon"></i>
                                </div>
                                <div class="item" data-value="gift">
                                    <i class="gift icon"></i>
                                </div>
                                <div class="item" data-value="shopping bag">
                                    <i class="shopping bag icon"></i>
                                </div>
                                <div class="item" data-value="stethoscope">
                                    <i class="stethoscope icon"></i>
                                </div>
                                <div class="item" data-value="briefcase">
                                    <i class="briefcase icon"></i>
                                </div>
                                <div class="item" data-value="car">
                                    <i class="car icon"></i>
                                </div>
                                <div class="item" data-value="plane">
                                    <i class="plane icon"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Cor</label>
                        <div class="ui fluid selection dropdown on-color-cost-dropdown">
                            <input type="hidden" name="color_cost_center">
                            <i class="dropdown icon"></i>
                            <div class="default text">Selecione...</div>
                            <div class="menu">
                                <div class="item" data-value="red">
                                    <div class="ui red empty circular label"></div>
                                    Vermelho
                                </div>
                                <div class="item" data-value="orange">
                                    <div class="ui orange empty circular label"></div>
                                    Laranja
                                </div>
                                <div class="item" data-value="yellow">
                                    <div class="ui yellow empty circular label"></div>
                                    Amarelo
                                </div>
                                <div class="item" data-value="olive">
                                    <div class="ui olive empty circular label"></div>
                                    Verde oliva
                                </div>
                                <div class="item" data-value="green">
                                    <div class="ui green empty circular label"></div>
                                    Verde escuro
                                </div>
                                <div class="item" data-value="teal">
                                    <div class="ui teal empty circular label"></div>
                                    Azul claro
                                </div>
                                <div class="item" data-value="blue">
                                    <div class="ui blue empty circular label"></div>
                                    Azul escuro
                                </div>
                                <div class="item" data-value="violet">
                                    <div class="ui violet empty circular label"></div>
                                    Violeta
                                </div>
                                <div class="item" data-value="purple">
                                    <div class="ui purple empty circular label"></div>
                                    Roxo
                                </div>
                                <div class="item" data-value="pink">
                                    <div class="ui pink empty circular label"></div>
                                    Rosa
                                </div>
                                <div class="item" data-value="brown">
                                    <div class="ui brown empty circular label"></div>
                                    Marron
                                </div>
                                <div class="item" data-value="grey">
                                    <div class="ui grey empty circular label"></div>
                                    Cinza
                                </div>
                                <div class="item" data-value="black">
                                    <div class="ui black empty circular label"></div>
                                    Preto
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>

<div class="ui small modal on-modal-update">
    <div class="header">Atualizar Registro</div>
    <div class="content">
        <form class="ui form on-form-update">
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-1">
                    <div class="field required">
                        <label>Descrição</label>
                        <input type="text" name="name_cost_center" maxlength="128" />
                    </div>
                </div>
            </div>
            <div class="uk-grid-small" uk-grid>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Icon</label>
                        <div class="ui fluid selection dropdown on-icon-cost-dropdown">
                            <input type="hidden" name="icon_cost_center">
                            <i class="dropdown icon"></i>
                            <div class="default text">Selecione...</div>
                            <div class="menu">
                                <div class="item" data-value="clipboard check">
                                    <i class="clipboard check icon"></i>
                                </div>
                                <div class="item" data-value="utensils">
                                    <i class="utensils icon"></i>
                                </div>
                                <div class="item" data-value="pencil alternate">
                                    <i class="pencil alternate icon"></i>
                                </div>
                                <div class="item" data-value="minus">
                                    <i class="minus icon"></i>
                                </div>
                                <div class="item" data-value="file">
                                    <i class="file icon"></i>
                                </div>
                                <div class="item" data-value="chart line">
                                    <i class="chart line icon"></i>
                                </div>
                                <div class="item" data-value="gamepad">
                                    <i class="gamepad icon"></i>
                                </div>
                                <div class="item" data-value="shopping cart">
                                    <i class="shopping cart icon"></i>
                                </div>
                                <div class="item" data-value="home">
                                    <i class="home icon"></i>
                                </div>
                                <div class="item" data-value="ellipsis horizontal">
                                    <i class="ellipsis horizontal icon"></i>
                                </div>
                                <div class="item" data-value="paw">
                                    <i class="paw icon"></i>
                                </div>
                                <div class="item" data-value="gift">
                                    <i class="gift icon"></i>
                                </div>
                                <div class="item" data-value="shopping bag">
                                    <i class="shopping bag icon"></i>
                                </div>
                                <div class="item" data-value="stethoscope">
                                    <i class="stethoscope icon"></i>
                                </div>
                                <div class="item" data-value="briefcase">
                                    <i class="briefcase icon"></i>
                                </div>
                                <div class="item" data-value="car">
                                    <i class="car icon"></i>
                                </div>
                                <div class="item" data-value="plane">
                                    <i class="plane icon"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-width-1-2@s">
                    <div class="field required">
                        <label>Cor</label>
                        <div class="ui fluid selection dropdown on-color-cost-dropdown">
                            <input type="hidden" name="color_cost_center">
                            <i class="dropdown icon"></i>
                            <div class="default text">Selecione...</div>
                            <div class="menu">
                                <div class="item" data-value="red">
                                    <div class="ui red empty circular label"></div>
                                    Vermelho
                                </div>
                                <div class="item" data-value="orange">
                                    <div class="ui orange empty circular label"></div>
                                    Laranja
                                </div>
                                <div class="item" data-value="yellow">
                                    <div class="ui yellow empty circular label"></div>
                                    Amarelo
                                </div>
                                <div class="item" data-value="olive">
                                    <div class="ui olive empty circular label"></div>
                                    Verde oliva
                                </div>
                                <div class="item" data-value="green">
                                    <div class="ui green empty circular label"></div>
                                    Verde escuro
                                </div>
                                <div class="item" data-value="teal">
                                    <div class="ui teal empty circular label"></div>
                                    Azul claro
                                </div>
                                <div class="item" data-value="blue">
                                    <div class="ui blue empty circular label"></div>
                                    Azul escuro
                                </div>
                                <div class="item" data-value="violet">
                                    <div class="ui violet empty circular label"></div>
                                    Violeta
                                </div>
                                <div class="item" data-value="purple">
                                    <div class="ui purple empty circular label"></div>
                                    Roxo
                                </div>
                                <div class="item" data-value="pink">
                                    <div class="ui pink empty circular label"></div>
                                    Rosa
                                </div>
                                <div class="item" data-value="brown">
                                    <div class="ui brown empty circular label"></div>
                                    Marron
                                </div>
                                <div class="item" data-value="grey">
                                    <div class="ui grey empty circular label"></div>
                                    Cinza
                                </div>
                                <div class="item" data-value="black">
                                    <div class="ui black empty circular label"></div>
                                    Preto
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>

<div class="ui small modal on-modal-delete">
    <div class="header">Confirmar Exclusão</div>
    <div class="content uk-text-center">
        <p class="uk-text-meta">Você tem certeza que deseja excluir o registro?</p>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Confirmar</button>
    </div>
</div>