<div class="section login_section wf-section">
    <div class="log_in_side">
        <div class="sign_in_form_block w-form">
            <form id="Sign-In-Email-Form" name="wf-form-Sign-In-Email-Form" data-name="Sign In Email Form" method="get" class="signin_form" aria-label="Sign In Email Form">
                <a href="/" class="home_link login_home_link w-inline-block">
                    <img src="/public/assets/images/logotipo.png" width="111" alt="" class="login-logo-image" />
                </a>
                <div class="div-block-11">
                    <h3 class="align_center">Bem vindo!</h3>
                    <p class="align_center">Não tem um conta? <a href="/sign-up" class="text_link">Cadastre-se agora.</a></p>
                </div>
                <input type="email" class="text-field w-input" maxlength="256" name="Email" data-name="Email" placeholder="E-mail" id="Email" required="" />
                <input type="password" class="text-field w-input" maxlength="256" name="Password" data-name="Password" placeholder="Senha" id="Password" required="" />
                <input type="submit" value="Entrar" data-wait="Please wait..." class="button sign-in-button w-button" />
                <div>
                    <div class="forgot_password"><a href="#" class="text_link">Esqueceu sua senha?</a><a href="#" class="log_in_here_link"></a></div>
                </div>
            </form>
            <div class="success-message w-form-done" tabindex="-1" role="region" aria-label="Sign In Email Form success"><div>Thank you! You are now logged-in.</div></div>
            <div class="w-form-fail" tabindex="-1" role="region" aria-label="Sign In Email Form failure"><div>Oops! Something went wrong while submitting the form.</div></div>
        </div>
        <div class="copy_rights">
            <strong class="normal_size"><?php echo date('Y') ?> &copy; Intercâmbio 360º - Todos os direitos reservados.</strong>
            <a href="#" class="link_span"><strong class="normal_size">Política de Privacidade</strong></a>
        </div>
    </div>
    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg" width="313" alt="" class="confetti_hero_svg sign-in" />
</div>
