<div class="uk-section">
    <div class="uk-flex uk-flex-center" uk-grid>
        <div class="uk-width-2-3@s">
            <h1 class="uk-h1 uk-text-uppercase uk-text-primary uk-margin-remove-bottom">
                Bloqueios
            </h1>
            <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-text-center">BLOQUEIO DISCOVER UK</p>
            <h2 class="uk-h2 uk-text-uppercase uk-text-primary uk-text-center uk-margin-remove-bottom">20</h2>
            <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-text-center uk-margin-remove-top">VAGAS</p>
            
            <a class="uk-link uk-text-primary">Adicionar Venda</p>
        </div>
    </div>
</div>