<div class="uk-section">
    <div class="uk-flex uk-flex-center" uk-grid>
        <div class="uk-width-1-2@s">
            <h1 class="uk-h1 uk-text-uppercase uk-text-primary uk-margin-remove-bottom">
                Bloqueios
            </h1>
            <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-margin-remove-bottom">BLOQUEIO DISCOVER UK</p>

            <div uk-grid>
                <div class="uk-width-1-2@s">
                    <h2 class="uk-h2 uk-text-uppercase uk-text-primary uk-margin-remove">20</h2>
                    <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-margin-remove-top">TOTAL DE VAGAS</p>
                </div>
                <div class="uk-width-1-2@s">
                    <h2 class="uk-h2 uk-text-uppercase uk-text-primary uk-margin-remove">5</h2>
                    <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-margin-remove-top">VAGAS RESTANTES</p>
                </div>
            </div>

            <a class="uk-button uk-button-primary">Adicionar Venda</a>
            <hr class="uk-divider-small" />
            <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-margin-remove-bottom">BLOQUEIO Vancouver</p>

            <div uk-grid>
                <div class="uk-width-1-2@s">
                    <h2 class="uk-h2 uk-text-uppercase uk-text-primary uk-margin-remove">20</h2>
                    <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-margin-remove-top">TOTAL DE VAGAS</p>
                </div>
                <div class="uk-width-1-2@s">
                    <h2 class="uk-h2 uk-text-uppercase uk-text-primary uk-margin-remove">5</h2>
                    <p class="uk-text-meta uk-text-uppercase uk-text-primary uk-margin-remove-top">VAGAS RESTANTES</p>
                </div>
            </div>

            <a class="uk-button uk-button-primary">Adicionar Venda</a>
        </div>
        <div class="uk-width-1-2@s">
            <div class="uk-card">
                Prezados Franqueados,
                <br />
                Se você tem algum participante inscrito no programa Discover Vancouver favor dar atenção a este email e preencher o formulário informado. Atenção: não temos confirmação de valores para este grupo em 2023.
                <br />
                Hoje iniciamos as emissões das passagens aéreas do grupo Discover Vancouver de Julho/2022. E a Air Canada reduziu o prazo para garantir vaga no bloqueio, devido à alta demanda procura no período. Data limite para garantir vaga no bloqueio: 7/Março/2022.
                <br />
                Para garantir a vaga no bloqueio deve ser feito o pagamento (via depósito bancário ou pix) no valor de R$ 1244 (até 7/Março/2022).
                <br />
                O saldo restante USD 1499 + taxa de embarque será pago no dia 10/Maio/2022, conforme o câmbio IATA do dia da emissão. Forma de pagamento: até 10X sem juros com cartão de crédito ou à vista.
                <br />
                Observações:<br />
                Esta data de quitação foi definida pela cia aérea, não sendo possível fazer antes.<br />
                Todo o grupo deverá ser emitido no mesmo dia.<br />
                Não é possível usar mais de um cartão de crédito.
                <br />
                Destacamos que os passageiros que não confirmarem o pagamento de R$ 1244 até o dia 7/Março, estarão fora do bloqueio. E a partir desta data as emissões serão avulsas, conforme a disponibilidade.
                <br />
                Comissão da franquia: R$ 518 (será paga no relatório 3C)<br />
                Preencha o formulário até 04/Março/2022: https://forms.gle/UvYXYHsth4fiJm3w7
                <br />
                Alguma dúvida? Por favor entre em contato conosco<br />
                Obrigado!
            </div>
        </div>
    </div>
</div>