
      
        <div class="section traveltellers wf-section">
            <div style="opacity: 1;" class="container">
                <h2>All TravelTellers</h2>
                <p class="max_550">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean
                    faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.
                </p>
                <form action="/search" class="search w-form">
                    <input type="search" class="search-input traveltellers w-input" maxlength="256" name="query" placeholder="Find a TravelTeller…" id="search" required="" /><input type="submit" value="⌕" class="search-button w-button" />
                </form>
                <div class="w-dyn-list">
                    <div role="list" class="traveltellers-collection-list w-dyn-items">
                        <div role="listitem" class="traveltellers-collection-item w-dyn-item">
                            <a href="/traveltellers/rachelle-mindy" class="author_card w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="author_circle_img"></div>
                                <h5>Rachelle Mindy</h5>
                                <p>New York, USA</p>
                            </a>
                        </div>
                        <div role="listitem" class="traveltellers-collection-item w-dyn-item">
                            <a href="/traveltellers/mason-miller" class="author_card w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="author_circle_img"></div>
                                <h5>Mason Miller</h5>
                                <p>Amsterdam, Netherlands</p>
                            </a>
                        </div>
                        <div role="listitem" class="traveltellers-collection-item w-dyn-item">
                            <a href="/traveltellers/natasha-miles" class="author_card w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="author_circle_img"></div>
                                <h5>Natasha Miles</h5>
                                <p>Paris, France</p>
                            </a>
                        </div>
                        <div role="listitem" class="traveltellers-collection-item w-dyn-item">
                            <a href="/traveltellers/michelle-worthy" class="author_card w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="author_circle_img"></div>
                                <h5>Michelle Worthy</h5>
                                <p>Melbourne, Australia</p>
                            </a>
                        </div>
                        <div role="listitem" class="traveltellers-collection-item w-dyn-item">
                            <a href="/traveltellers/jason-maddock" class="author_card w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');" class="author_circle_img"></div>
                                <h5>Jason Maddock</h5>
                                <p>Chicago, USA</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <img
                src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg"
                alt=""
                class="confetti_hero_svg traveltellers"
                style="transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d; opacity: 1;"
            />
        </div>