<div class="section traveltellers_template wf-section">
    <div class="container travelteller_template" style="opacity: 1;">
        <div class="author_content_contain">
            <h2>Rachelle Mindy</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus
                nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.
            </p>
            <div class="travelteller-collection-list-wrapper w-dyn-list">
                <div role="list" class="w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <a href="/blog/post" class="story_wrap w-inline-block">
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg');" class="story_image on_author_page">
                                <div style="background-color: #ff0149;" class="category"><div>Categoria</div></div>
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg');" class="card_image_hover_expand"></div>
                            </div>
                            <div class="story_content">
                                <h4>Japan Like You've Never Seen It</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Lorem ipsum dolor sit amet.</p>
                            </div>
                        </a>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <a href="/blog/post" class="story_wrap w-inline-block">
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededea55249ae5802f851ca_colton-duke-UExx0KnnkjY-unsplash.jpg');" class="story_image on_author_page">
                                <div style="background-color: hsla(342.99212598425197, 100%, 50.2%, 1);" class="category"><div>Categoria</div></div>
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededea55249ae5802f851ca_colton-duke-UExx0KnnkjY-unsplash.jpg');" class="card_image_hover_expand"></div>
                            </div>
                            <div class="story_content">
                                <h4>New York City Views</h4>
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="sticky-nav-contain">
            <div class="sticky">
                <div class="blog_categories_contain">
                    <div class="author_card">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="author_circle_img-2"></div>
                        <h4>Rachelle Mindy</h4>
                        <p>New York, USA</p>
                        <div class="social_links_wrapper">
                            <a href="#" target="_blank" class="social_link w-inline-block">
                                <img
                                    src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adad6ffd4a19d_5e1ed0b824ceb838fadfa9b7_linkedin-icon-png-transparent-background-5.png"
                                    width="18"
                                    srcset="
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adad6ffd4a19d_5e1ed0b824ceb838fadfa9b7_linkedin-icon-png-transparent-background-5-p-500.png 500w,
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adad6ffd4a19d_5e1ed0b824ceb838fadfa9b7_linkedin-icon-png-transparent-background-5.png       609w
                                    "
                                    sizes="(max-width: 767px) 18px, (max-width: 991px) 2vw, 18px"
                                    alt=""
                                />
                            </a>
                            <a href="#" target="_blank" class="social_link w-inline-block">
                                <img
                                    src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adae251d4a199_twitter1.png"
                                    width="18"
                                    srcset="
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adae251d4a199_twitter1-p-500.png 500w,
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adae251d4a199_twitter1-p-800.png 800w,
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed82144f18adae251d4a199_twitter1.png       827w
                                    "
                                    sizes="(max-width: 767px) 18px, (max-width: 991px) 2vw, 18px"
                                    alt=""
                                />
                            </a>
                        </div>
                    </div>
                    <div class="_30px-div"></div>
                    <h4>Categorias</h4>
                    <div class="line div"></div>
                    <div class="w-dyn-list">
                        <div role="list" class="category-tags-collection-list w-dyn-items">
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #faaa04;" href="/blog/category" class="category with-margin w-inline-block"><div>Lugares</div></a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #03c1d6;" href="/blog/category" class="category with-margin w-inline-block"><div>Inspiração</div></a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #9502f3;" href="/blog/category" class="category with-margin w-inline-block"><div>Cultura</div></a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #ff0149;" href="/blog/category" class="category with-margin w-inline-block"><div>Experiência</div></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container other_traveltellers" style="opacity: 1;">
        <h3 class="_10px_left">Outros Viajantes</h3>
        <div class="w-dyn-list">
            <div role="list" class="traveltellers-collection-list other w-dyn-items">
                <div role="listitem" class="traveltellers-collection-item _25_percent w-dyn-item">
                    <a href="/traveltellers/travelteller" class="author_card w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="author_circle_img"></div>
                        <h5>Mason Miller</h5>
                        <p>Amsterdam, Netherlands</p>
                    </a>
                </div>
                <div role="listitem" class="traveltellers-collection-item _25_percent w-dyn-item">
                    <a href="/traveltellers/travelteller" class="author_card w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="author_circle_img"></div>
                        <h5>Natasha Miles</h5>
                        <p>Paris, France</p>
                    </a>
                </div>
                <div role="listitem" class="traveltellers-collection-item _25_percent w-dyn-item">
                    <a href="/traveltellers/travelteller" class="author_card w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="author_circle_img"></div>
                        <h5>Michelle Worthy</h5>
                        <p>Melbourne, Australia</p>
                    </a>
                </div>
                <div role="listitem" class="traveltellers-collection-item _25_percent w-dyn-item">
                    <a href="/traveltellers/travelteller" class="author_card w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');" class="author_circle_img"></div>
                        <h5>Jason Maddock</h5>
                        <p>Chicago, USA</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
