<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR">

<head>

    <?php
    echo $this->headTitle($this->title_page);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('language', 'pt-BR')
        ->appendName('robots', 'noindex, nofollow')
        ->appendName('title', $this->title)
        ->appendName('description', $this->description_page);

    echo $this->headLink()
        ->appendStylesheet('/public/assets/addons/semantic/semantic.min.css')
        ->appendStylesheet('/public/assets/addons/uikit/css/uikit.min.css')
        ->appendStylesheet('/public/assets/css/style.default.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.light.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.dark.css?v=' . time())
    ;
    ?>
    <!-- Search Engine -->
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="<?php echo $this->title_page ?>" />
    <meta itemprop="description" content="<?php echo $this->description_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="<?php echo $this->title_page ?>" />
    <meta name="og:description" content="<?php echo $this->title_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <meta name="og:url" content="https://onds.com.br" />
    <meta name="og:site_name" content="<?php echo $this->title_page ?>" />
    <meta name="og:locale" content="pt_BR" />
    <meta name="fb:admins" content="onds.agenciadigital" />
    <meta name="og:type" content="website" />
    <link rel="icon" href="/public/assets/images/logo.webp" />


    <!-- Google Tag Manager -->
    <script>
        (function(w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start': new Date().getTime(),
                event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s),
                dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-PKQ6Q8M');
    </script>
    <!-- End Google Tag Manager -->
</head>

<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PKQ6Q8M" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "Organization",
            "name": "ONDS - Agência Digital",
            "url": "https://onds.com.br/",
            "address": "Rua Elias Antonio Zogbi, 150. Santo Amaro. São Paulo - SP. 04746-115",
            "sameAs": [
                "https://www.facebook.com/onds.agenciadigital/",
                "https://www.instagram.com/onds.agenciadigital/",
                "https://www.linkedin.com/company/onds-agenciadigital"
            ]
        }
    </script>


    <div id="on-offcanvas-menu" uk-offcanvas="flip: true">
        <div class="uk-offcanvas-bar">

            <button class="uk-offcanvas-close" type="button" uk-close></button>

            <a class="uk-navbar-item uk-logo">
                <img width="50" height="50" src="/public/assets/images/logo.webp" alt="Logotipo" />
            </a>

            <ul class="uk-nav uk-nav-primary uk-nav-center uk-margin-large">
                <li><a href="/">Início</a></li>
                <li><a href="/sobre">Sobre</a></li>
                <li class="uk-parent">
                    <a href="/servicos">Serviços</a>
                    <ul class="uk-nav-sub">
                        <li><a href="/servicos/automacao-360">Automação 360</a></li>
                        <li><a href="/servicos/criacao-de-sites">Criação de Sites</a></li>
                        <li><a href="/servicos/gestao-de-trafego-pago">Gestão de Tráfego Pago</a></li>
                    </ul>
                </li>
                <li><a href="/portfolio">Portfólio</a></li>
                <li><a href="/contato">Contato</a></li>
            </ul>
            <ul class="uk-iconnav uk-flex-center uk-margin-large">
                <li>
                    <a target="_blank" class="uk-icon-button" href="https://www.instagram.com/onds.agenciadigital/" target="_blank">
                        <span uk-icon="icon: instagram; ratio: .5"></span>
                    </a>
                </li>
                <li>
                    <a target="_blank" class="uk-icon-button" href="https://www.facebook.com/onds.agenciadigital/" target="_blank">
                        <span uk-icon="icon: facebook; ratio: .5"></span>
                    </a>
                </li>
                <li>
                    <a target="_blank" class="uk-icon-button" href="https://www.linkedin.com/company/onds-agenciadigital/" target="_blank">
                        <span uk-icon="icon: linkedin; ratio: .5"></span>
                    </a>
                </li>
            </ul>

        </div>
    </div>



    <nav class="uk-navbar-container uk-navbar-transparent uk-position-absolute uk-position-top">
        <div class="uk-container uk-container-large">
            <div uk-navbar>
                <div class="uk-navbar-center">
                    <ul class="uk-navbar-nav">
                        <li><a target="_blank" href="https://www.instagram.com/onds.agenciadigital/"><span class="uk-icon-button" uk-icon="icon: instagram; ratio: .5"></span></a></li>
                        <li><a target="_blank" href="https://www.facebook.com/onds.agenciadigital/"><span class="uk-icon-button" uk-icon="icon: facebook; ratio: .5"></span></a></li>
                        <li><a target="_blank" href="https://www.linkedin.com/company/onds-agenciadigital/"><span class="uk-icon-button" uk-icon="icon: linkedin; ratio: .5"></span></a></li>
                    </ul>
                </div>
            </div>
            <div uk-navbar>
                <div class="uk-navbar-left">
                    <a class="uk-navbar-item uk-logo" href="/">
                        <img width="50" height="50" src="/public/assets/images/logo.webp" alt="Logotipo" />
                    </a>
                </div>
                <div class="uk-navbar-center uk-visible@s">
                    <ul class="uk-navbar-nav">
                        <li class="<?php echo ($this->page_id == '1' ? 'uk-active' : '') ?>"><a href="/">Início</a></li>
                        <li class="<?php echo ($this->page_id == '2' ? 'uk-active' : '') ?>"><a href="/sobre">Sobre</a></li>
                        <li class="<?php echo ($this->page_id == '3' ? 'uk-active' : '') ?>">
                            <a href="/servicos">Serviços</a>
                            <div class="uk-navbar-dropdown uk-border-rounded">
                                <ul class="uk-nav uk-navbar-dropdown-nav">
                                    <li class="<?php echo ($this->subpage_id == '3.1' ? 'uk-active' : '') ?>"><a href="/servicos/automacao-360">Automação 360</a></li>
                                    <li class="<?php echo ($this->subpage_id == '3.2' ? 'uk-active' : '') ?>"><a href="/servicos/criacao-de-sites">Criação de Sites</a></li>
                                    <li class="<?php echo ($this->subpage_id == '3.3' ? 'uk-active' : '') ?>"><a href="/servicos/gestao-de-trafego-pago">Gestão de Tráfego Pago</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="<?php echo ($this->page_id == '4' ? 'uk-active' : '') ?>"><a href="/portfolio">Portfólio</a></li>
                        <li class="<?php echo ($this->page_id == '5' ? 'uk-active' : '') ?>"><a href="/contato">Contato</a></li>
                    </ul>
                </div>
                <div class="uk-navbar-right">
                    <ul class="uk-navbar-nav">
                        <li class="mode">
                            <div class="toggle-switch">
                                <span class="switch"></span>
                            </div>
                        </li>
                        <li class="uk-visible@s">
                            <a target="_blank">
                                <button class="uk-button uk-button-primary"><span uk-icon="icon: bolt"></span> Iniciar atendimento</button>
                            </a>
                        </li>
                    </ul>
                    <div class="uk-navbar-item uk-hidden@s">
                        <button class="uk-icon-button" uk-toggle="target: #on-offcanvas-menu" type="button">
                            <span uk-icon="icon: menu; ratio: .5"></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </nav>

    <?php echo $this->layout()->content; ?>

    <footer class="uk-section">
        <div class="uk-container">
            <div class="uk-child-width-1-4@s" uk-grid>
                <div>
                    <a class="uk-logo uk-display-inline-block">
                        <img width="50" height="50" src="/public/assets/images/logo.webp" alt="Logotipo" />
                    </a>
                    <!--<p class="uk-text-lead">Somos uma <strong>Agência Digital</strong> especializada em <strong>Criar e Gerenciar Sites</strong> que ajudam no processo de coleta, organização, análise, compartilhamento e monitoramento de informações para divulgação e venda de produtos ou serviços.</p>-->
                    <hr class="uk-divider-small" />
                    <ul class="uk-iconnav">
                        <li>
                            <a target="_blank" class="uk-icon-button" href="https://www.instagram.com/onds.agenciadigital/" target="_blank">
                                <span uk-icon="icon: instagram; ratio: .5"></span>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" class="uk-icon-button" href="https://www.facebook.com/onds.agenciadigital/" target="_blank">
                                <span uk-icon="icon: facebook; ratio: .5"></span>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" class="uk-icon-button" href="https://www.linkedin.com/company/onds-agenciadigital/" target="_blank">
                                <span uk-icon="icon: linkedin; ratio: .5"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h4 class="uk-h4">Interno</h4>
                    <ul class="uk-nav">
                        <li><a target="_blank" href="https://onds.dev/account/access/">Painel de Cliente</a></li>
                        <li><a target="_blank" href="http://webmail.onds.com.br/">Webmail</a></li>
                    </ul>
                </div>
                <div>
                    <h4 class="uk-h4">Úteis</h4>
                    <ul class="uk-nav">
                        <li><a target="_blank" href="https://registro.br/2/whois">Consultar Domínio</a></li>
                        <li><a target="_blank" href="https://github.com/">Repositório</a></li>
                    </ul>
                </div>
                <div>
                    <h4 class="uk-h4">Parceiros</h4>
                    <ul class="uk-nav">
                        <li><a target="_blank" href="https://goo.gl/KDikMN">G Suite</a></li>
                        <li><a target="_blank" href="https://www.jivochat.com.br/?partner_id=25512&pricelist_id=114&lang=pt">JivoChat</a></li>
                        <li><a target="_blank" href="https://king.host?ref=59664DC81CAC5">Kinghost</a></li>
                    </ul>
                </div>
            </div>

            <div uk-grid>
                <div class="uk-width-1-1 uk-text-center">
                    <p class="uk-text-meta"><?php echo date('Y') ?> © ONDS - Agência Digital. Todos os direitos reservados.</p>
                </div>
            </div>
        </div>
    </footer>


    <?php
    echo $this->headScript()
        ->prependFile('/public/assets/addons/semantic/semantic.min.js')
        ->prependFile('/public/assets/addons/uikit/js/uikit-icons.min.js')
        ->prependFile('/public/assets/addons/uikit/js/uikit.min.js')
        ->prependFile('/public/config/default.js')
        ->prependFile('/public/assets/addons/mask/mask.min.js')
        ->prependFile('/public/assets/addons/jquery/jquery.min.js');
    ?>

    <script>
        const body = document.querySelector('html'),
            modeSwitch = body.querySelector(".toggle-switch"),
            modeText = body.querySelector(".mode-text");


        if (getCookie('mode') == 'dark') {
            body.classList.toggle("dark");
        }

        modeSwitch.addEventListener("click", () => {
            body.classList.toggle("dark");

            if (body.classList.contains("dark")) {
                //                    modeText.innerText = "Light mode";
                setCookie('mode', 'dark', 365);
            } else {
                //                    modeText.innerText = "Dark mode";
                setCookie('mode', 'light', 365);

            }
        });
    </script>

</body>

</html>