<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-BR">
    <head>
        <?php
        echo $this->headTitle($this->title_page);

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1')
                ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('language', 'pt-BR')
                ->appendName('robots', 'noindex, nofollow')
                ->appendName('title', $this->title)
                ->appendName('description', $this->description);

        echo $this->headLink()
                ->appendStylesheet('/public/assets/addons/semantic/semantic.min.css')
                ->appendStylesheet('/public/assets/addons/uikit/uikit.min.css')
                ->appendStylesheet('/public/assets/css/style.default.css')
                ->appendStylesheet('/public/library/contextmenu/default.css')
                ->appendStylesheet('/public/library/datatables/complement.semantic.css')
                ->appendStylesheet('/public/library/datatables/select.css');
        ?>

    </head>
    <body class="uk-background-secondary uk-light">

        <div id="offcanvas-push-left" uk-offcanvas="mode: push; overlay: true;" class="uk-offcanvas">
            <div class="uk-offcanvas-bar uk-background-secondary">
                <button class="uk-offcanvas-close uk-close uk-icon" type="button" uk-close></button>

                <div class="uk-padding-small">
                    <div class="ui secondary vertical fluid menu">
                        <div class="header item">Principal</div>
                        <a class="<?php echo ($this->id_module == 0 ? 'active' : '') ?> item" href="/account/dashboard"><i class="home icon"></i> Visão Geral</a>
                        <a class="<?php echo ($this->id_module == 1 ? 'active' : '') ?> item" href="/account/contact"><i class="users icon"></i> Contatos</a>
                        <div class="header item">Projetos</div>
                        <a class="<?php echo ($this->id_module == 2 ? 'active' : '') ?> item" href="/project/project-task"><i class="tasks icon"></i> Tarefas</a>
                        <a class="<?php echo ($this->id_module == 3 ? 'active' : '') ?> item" href="/project"><i class="lightbulb icon"></i> Projetos</a>
                        <div class="header item">Financeiro</div>
                        <a class="<?php echo ($this->id_module == 4 ? 'active' : '') ?> item" href="/finance/order-in"><i class="plus icon"></i> Receitas</a>
                        <a class="<?php echo ($this->id_module == 5 ? 'active' : '') ?> item" href="/finance/order-out"><i class="minus icon"></i> Despesas</a>
                        <!--<a class="<?php echo ($this->id_module == 6 ? 'active' : '') ?> item" href="/finance/transfer"><i class="exchange icon"></i> Transferências</a>-->
                        <?php if (Zend_Auth::getInstance()->getIdentity()->id_user == 1) : ?>
                            <div class="header item">Acesso restrito</div>
                            <a class="<?php echo ($this->id_module == 99 ? 'active' : '') ?> item" href="/admin/company"><span class="material-icons">admin_panel_settings</span> Config. do Sistema</a>
                        <?php endif; ?>
                    </div>

                </div>
            </div>
        </div>

        <div id="offcanvas-push" uk-offcanvas="mode: push; overlay: true; flip: true" class="uk-offcanvas">
            <div class="uk-offcanvas-bar uk-background-secondary">
                <button class="uk-offcanvas-close uk-close uk-icon" type="button" uk-close></button>

                <div class="ui secondary vertical fluid menu">
                    <div class="header item">Config. Geral</div>
                    <a class="<?php echo ($this->id_module == 100 ? 'active' : '') ?> item" href="/account/user">
                        <i class="address card outline icon"></i> Info. da Pessoal
                    </a>
                    <a class="<?php echo ($this->id_module == 101 ? 'active' : '') ?> item" href="/account/company">
                        <i class="building outline icon"></i> Info. da Empresa
                    </a>
                    <a class="<?php echo ($this->id_module == 7 ? 'active' : '') ?> item" href="/account/users">
                        <i class="users icon"></i> Controle de Usuários
                    </a>

                    <div class="header item">Config. de Projetos</div>
                    <a class="<?php echo ($this->id_module == 8 ? 'active' : '') ?> item" href="/project/project-task-status">
                        <i class="bookmark icon"></i> Status da Tarefa
                    </a>

                    <div class="header item">Config. do Financeiro</div>
                    <a class="<?php echo ($this->id_module == 9 ? 'active' : '') ?> item" href="/finance/account">
                        <i class="credit card icon"></i> Contas
                    </a>
                    <a class="<?php echo ($this->id_module == 10 ? 'active' : '') ?> item" href="/finance/cost-center">
                        <i class="tags icon"></i> Categorias
                    </a>

                    <div class="header item">Outros</div>
                    <a class="item" href="/account/access/out"><i class="sign-out icon"></i> Encerrar Sessão</a>

                </div>
            </div>
        </div>


        <nav class="uk-navbar-container uk-navbar-transparent uk-background-secondary uk-light on-border-bottom" uk-navbar>
            <div class="uk-navbar-left">
                <a class="uk-navbar-item uk-logo">
                    <img src="/public/assets/images/logotipo/logotipo.svg" width="96" height="96" alt="" />
                </a>
                <ul class="uk-navbar-nav">
                    <li class="uk-hidden@m">
                        <a>
                            <button class="ui icon circular primary button" type="button" uk-toggle="target: #offcanvas-push-left">
                                <i class="bars icon"></i>
                            </button>
                        </a>
                    </li>
                    <li class="uk-visible@s">
                        <a>
                            <div>
                                <?php echo $this->title_page ?>
                                <div class="uk-navbar-subtitle">
                                    <?php echo $this->description_page ?>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <li class="uk-visible@s">
                        <a>
                            <!--<img class="uk-border-circle uk-margin-right" src="<?php echo Zend_Auth::getInstance()->getIdentity()->image_user ?>" alt="Image profile" width="32" height="32" />-->
                            <div>
                                <?php echo Zend_Auth::getInstance()->getIdentity()->name_user ?>
                                <div class="uk-navbar-subtitle">
                                    <?php echo Zend_Auth::getInstance()->getIdentity()->email_user ?>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a>
                            <button class="circular ui icon basic button" type="button" uk-toggle="target: #offcanvas-push">
                                <i class="cog icon"></i>
                            </button>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="uk-grid-collapse" uk-grid>
            <div class="uk-width-medium uk-background-secondary uk-visible@m on-border-right" uk-height-viewport>
                <div class="uk-padding-small">
                    <div class="ui secondary vertical fluid menu">
                        <div class="header item">Principal</div>
                        <a class="<?php echo ($this->id_module == 0 ? 'active' : '') ?> item" href="/account/dashboard"><i class="home icon"></i> Visão Geral</a>
                        <div class="header item">Site</div>
                            <a class="<?php echo ($this->id_module == 99 ? 'active' : '') ?> item" href="/admin/company"><i class="settings icon"></i> Info. do Site</a>
                        <a class="<?php echo ($this->id_module == 1 ? 'active' : '') ?> item" href="/account/contact"><i class="users icon"></i> Clientes</a>
                        <a class="<?php echo ($this->id_module == 3 ? 'active' : '') ?> item" href="/project"><i class="lightbulb icon"></i> Portfólio</a>
                        <a class="<?php echo ($this->id_module == 2 ? 'active' : '') ?> item" href="/project/project-task"><i class="tasks icon"></i> Serviços</a>
                        <div class="header item">Conversões</div>
                        <a class="<?php echo ($this->id_module == 5 ? 'active' : '') ?> item" href="/finance/order-out"><i class="minus icon"></i> Formulários</a>
                        <a class="<?php echo ($this->id_module == 4 ? 'active' : '') ?> item" href="/finance/order-in"><i class="plus icon"></i> Leads</a>
                        <div class="header item">Financeiro</div>
                        <a class="<?php echo ($this->id_module == 5 ? 'active' : '') ?> item" href="/finance/order"><i class="minus icon"></i> Lançamentos</a>
                        <a class="<?php echo ($this->id_module == 4 ? 'active' : '') ?> item" href="/finance/category"><i class="plus icon"></i> Categorias</a>
                        <div class="header item">Blog</div>
                        <a class="<?php echo ($this->id_module == 5 ? 'active' : '') ?> item" href="/website/post"><i class="post icon"></i> Equipe</a>
                        <a class="<?php echo ($this->id_module == 6 ? 'active' : '') ?> item" href="/website/post"><i class="post icon"></i> Tags</a>
                        <a class="<?php echo ($this->id_module == 6 ? 'active' : '') ?> item" href="/website/post"><i class="post icon"></i> Post</a>
                        
                    </div>

                </div>
            </div>
            <div class="uk-width-expand@s uk-background-secondary">

                <div class="uk-padding-small">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>


        <?php
        echo $this->headScript()
                ->prependFile('/public/assets/addons/datatables/datatables.sorting.js')
                ->prependFile('/public/assets/addons/datatables/datatables.semanticui.min.js')
                ->prependFile('/public/assets/addons/datatables/datatables.min.js')
                ->prependFile('/public/assets/addons/contextmenu/contextmenu.min.js')
                ->prependFile('/public/assets/addons/numeral/numeral-locales.js')
                ->prependFile('/public/assets/addons/numeral/numeral.min.js')
                ->prependFile('/public/assets/addons/moment/moment-locales.js')
                ->prependFile('/public/assets/addons/moment/moment.min.js')
                ->prependFile('/public/config/default.js')
                ->prependFile('/public/assets/addons/uikit/uikit-icons.min.js')
                ->prependFile('/public/assets/addons/uikit/uikit.min.js')
                ->prependFile('/public/assets/addons/semantic/semantic.min.js')
                ->prependFile('/public/assets/addons/mask/mask.min.js')
                ->prependFile('/public/assets/addons/jquery/jquery.min.js');
        ?>
        
    </body>
</html>