<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR">

<head>

    <?php
    echo $this->headTitle($this->title_page);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('language', 'pt-BR')
        ->appendName('robots', 'noindex, nofollow')
        ->appendName('title', $this->title)
        ->appendName('description', $this->description_page);

    echo $this->headLink()
        // ->appendStylesheet('/public/assets/addons/semantic/semantic.min.css')
        // ->appendStylesheet('/public/assets/addons/uikit/css/uikit.min.css')
        ->appendStylesheet('/public/assets/css/style.default.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.light.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.dark.css?v=' . time())
    ;
    ?>
    <!-- Search Engine -->
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="<?php echo $this->title_page ?>" />
    <meta itemprop="description" content="<?php echo $this->description_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="<?php echo $this->title_page ?>" />
    <meta name="og:description" content="<?php echo $this->title_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <meta name="og:url" content="https://onds.com.br" />
    <meta name="og:site_name" content="<?php echo $this->title_page ?>" />
    <meta name="og:locale" content="pt_BR" />
    <meta name="fb:admins" content="onds.agenciadigital" />
    <meta name="og:type" content="website" />
    <link rel="icon" href="/public/assets/images/logo.webp" />


</head>

<body>
    <?php echo $this->layout()->content; ?>

    <?php
    echo $this->headScript()
        // ->prependFile('/public/assets/addons/semantic/semantic.min.js')
        // ->prependFile('/public/assets/addons/uikit/js/uikit-icons.min.js')
        // ->prependFile('/public/assets/addons/uikit/js/uikit.min.js')
        // ->prependFile('/public/config/default.js')
        // ->prependFile('/public/assets/addons/mask/mask.min.js')
        // ->prependFile('/public/assets/addons/jquery/jquery.min.js')
        ;
    ?>

</body>

</html>