<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR">

<head>

    <?php
    echo $this->headTitle($this->title_page);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('language', 'pt-BR')
        ->appendName('robots', 'noindex, nofollow')
        ->appendName('title', $this->title)
        ->appendName('description', $this->description_page);

    echo $this->headLink()
        // ->appendStylesheet('/public/assets/addons/semantic/semantic.min.css')
        // ->appendStylesheet('/public/assets/addons/uikit/css/uikit.min.css')
        ->appendStylesheet('/public/assets/css/style.default.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.light.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.dark.css?v=' . time())
    ;
    ?>
    <!-- Search Engine -->
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="<?php echo $this->title_page ?>" />
    <meta itemprop="description" content="<?php echo $this->description_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="<?php echo $this->title_page ?>" />
    <meta name="og:description" content="<?php echo $this->title_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <meta name="og:url" content="https://onds.com.br" />
    <meta name="og:site_name" content="<?php echo $this->title_page ?>" />
    <meta name="og:locale" content="pt_BR" />
    <meta name="fb:admins" content="onds.agenciadigital" />
    <meta name="og:type" content="website" />
    <link rel="icon" href="/public/assets/images/logo.webp" />


</head>

<body>
    <?php echo $this->layout()->content; ?>

    <div class="section footer_section wf-section">
            <div class="footer">
                <div class="container">
                    <div class="footer_content_wrapper">
                        <div class="logo_and_subscribe_wrap">
                            <a data-w-id="822756f3-5bbb-c983-fef1-280c17673ddb" href="/" aria-current="page" class="link-block-2 w-inline-block w--current">
                                <img
                                    src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed472c3a90a9c93ed22d1e1_TravelTell_Dark_Logo.png"
                                    width="123"
                                    sizes="123px"
                                    srcset="
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed472c3a90a9c93ed22d1e1_TravelTell_Dark_Logo-p-500.png  500w,
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed472c3a90a9c93ed22d1e1_TravelTell_Dark_Logo-p-800.png  800w,
                                        https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed472c3a90a9c93ed22d1e1_TravelTell_Dark_Logo.png       1034w
                                    "
                                    alt=""
                                    class="footer_logo"
                                />
                            </a>
                            <div data-w-id="822756f3-5bbb-c983-fef1-280c17673ddd" class="footer_social_wrap">
                                <a href="https://www.facebook.com/" target="_blank" class="social_media_link first w-inline-block">
                                    <img
                                        src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32ff2f14dad_faceb.png"
                                        width="25"
                                        sizes="(max-width: 767px) 25px, (max-width: 991px) 3vw, 25px"
                                        srcset="
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32ff2f14dad_faceb-p-500.png 500w,
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32ff2f14dad_faceb.png       766w
                                        "
                                        alt=""
                                    />
                                </a>
                                <a href="https://twitter.com" target="_blank" class="social_media_link w-inline-block">
                                    <img
                                        src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32897f14db0_twitter1.png"
                                        width="25"
                                        sizes="(max-width: 767px) 25px, (max-width: 991px) 3vw, 25px"
                                        srcset="
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32897f14db0_twitter1-p-500.png 500w,
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32897f14db0_twitter1-p-800.png 800w,
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a32897f14db0_twitter1.png       827w
                                        "
                                        alt=""
                                    />
                                </a>
                                <a href="https://www.linkedin.com/" target="_blank" class="social_media_link w-inline-block">
                                    <img
                                        src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a30ad4f14daa_5e1ed0b824ceb838fadfa9b7_linkedin-icon-png-transparent-background-5.png"
                                        width="25"
                                        sizes="(max-width: 767px) 25px, (max-width: 991px) 3vw, 25px"
                                        srcset="
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a30ad4f14daa_5e1ed0b824ceb838fadfa9b7_linkedin-icon-png-transparent-background-5-p-500.png 500w,
                                            https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed4a4666103a30ad4f14daa_5e1ed0b824ceb838fadfa9b7_linkedin-icon-png-transparent-background-5.png       609w
                                        "
                                        alt=""
                                    />
                                </a>
                            </div>
                        </div>
                        <div class="footer_links_wrapper">
                            <div data-w-id="822756f3-5bbb-c983-fef1-280c17673de5" class="footer_nav_column">
                                <a href="/blog" class="footer_link">Publicações</a>
                                <a href="/places" class="footer_link">Lugares</a>
                                <a href="/traveltellers" class="footer_link">Viajantes</a>
                            </div>
                            <div data-w-id="822756f3-5bbb-c983-fef1-280c17673dee" class="footer_nav_column">
                                <a href="/contact" class="footer_link">Contato</a>
                                <a href="#" class="footer_link">Política de privacidade</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyrights_contain">
                <div>
                    <div data-w-id="822756f3-5bbb-c983-fef1-280c17673df7" class="copyrights">
                        <?php echo date('Y') ?> &copy; Intercâmbio 360º - Todos os direitos reservados.
                    </div>
                </div>
            </div>
            <div class="footer_svg_wrap"><img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ef2f47927222dce7e47157b_footer%20svg.svg" width="304" alt="" class="footer_svg" /></div>
        </div>
        <!-- <script
            src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ed1cf34bf802c5f339f8167"
            type="text/javascript"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"
        ></script> -->
    <?php
    echo $this->headScript()
        // ->prependFile('/public/assets/addons/semantic/semantic.min.js')
        // ->prependFile('/public/assets/addons/uikit/js/uikit-icons.min.js')
        // ->prependFile('/public/assets/addons/uikit/js/uikit.min.js')
        // ->prependFile('/public/config/default.js')
        // ->prependFile('/public/assets/addons/mask/mask.min.js')
        ->prependFile('/public/assets/addons/jquery/jquery.min.js')
        ;
    ?>
    <script src="/public/assets/js/webflow.2f7557476.js" type="text/javascript"></script>
        <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
    
</body>

</html>