<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" data-wf-page="<?php echo $this->page_id ?>" data-wf-site="5ed1cf34bf802c5f339f8167">

<head>

    <!-- Search Engine -->
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="<?php echo $this->title_page ?>" />
    <meta itemprop="description" content="<?php echo $this->description_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="<?php echo $this->title_page ?>" />
    <meta name="og:description" content="<?php echo $this->title_page ?>" />
    <meta name="image" content="/public/assets/images/logo.webp" />
    <meta name="og:url" content="https://onds.com.br" />
    <meta name="og:site_name" content="<?php echo $this->title_page ?>" />
    <meta name="og:locale" content="pt_BR" />
    <meta name="fb:admins" content="onds.agenciadigital" />
    <meta name="og:type" content="website" />
    <link rel="icon" href="/public/assets/images/logo.webp" />
    <link href="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/css/traveltell.webflow.8372c187c.css" rel="stylesheet" type="text/css" />
    <style>
        @media (min-width: 992px) {
            html.w-mod-js:not(.w-mod-ix) [data-w-id="1b062139-faad-fee2-c02a-b49d1260ff8f"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="63335641-77b7-2165-c2c2-35dd0df72ec7"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="c37d1e11-495d-e825-2cec-4af2927ec093"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="765215f1-1497-d971-58e3-e619476c727a"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="6f8a05ad-fbdc-08c0-7ff1-2a5ae3823967"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="4762d817-fbdf-2d04-25c4-4c577c7357b6"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="981020ba-d567-d915-cbd1-8a938b4b546d"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="39285704-a621-d710-7503-81cf37fd55dc"] {
                opacity: 0;
            }
        }

        @media (max-width: 991px) and (min-width: 768px) {
            html.w-mod-js:not(.w-mod-ix) [data-w-id="1b062139-faad-fee2-c02a-b49d1260ff8f"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="63335641-77b7-2165-c2c2-35dd0df72ec7"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="c37d1e11-495d-e825-2cec-4af2927ec093"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="765215f1-1497-d971-58e3-e619476c727a"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="6f8a05ad-fbdc-08c0-7ff1-2a5ae3823967"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="4762d817-fbdf-2d04-25c4-4c577c7357b6"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="981020ba-d567-d915-cbd1-8a938b4b546d"] {
                opacity: 0;
            }

            html.w-mod-js:not(.w-mod-ix) [data-w-id="39285704-a621-d710-7503-81cf37fd55dc"] {
                opacity: 0;
            }
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">
        WebFont.load({
            google: {
                families: ["Barlow:100,100italic,200,200italic,300,300italic,regular,italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"]
            }
        });
    </script>
    <script src="https://use.typekit.net/iyv4mdw.js" type="text/javascript"></script>
    <script type="text/javascript">
        try {
            Typekit.load();
        } catch (e) {}
    </script>
    <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif]-->
    <script type="text/javascript">
        !(function(o, c) {
            var n = c.documentElement,
                t = " w-mod-";
            (n.className += t + "js"), ("ontouchstart" in o || (o.DocumentTouch && c instanceof DocumentTouch)) && (n.className += t + "touch");
        })(window, document);
    </script>
    <link href="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee753847da456b068661c23_Travel%20tell%20favicon.png" rel="shortcut icon" type="image/x-icon" />
    <link href="https://assets.website-files.com/img/webclip.png" rel="apple-touch-icon" />
    <script type="text/javascript">
        window.__WEBFLOW_CURRENCY_SETTINGS = {
            currencyCode: "USD",
            $init: true,
            symbol: "$",
            decimal: ".",
            fractionDigits: 2,
            group: ",",
            template: '{{wf {"path":"symbol","type":"PlainText"} }} {{wf {"path":"amount","type":"CommercePrice"} }} {{wf {"path":"currencyCode","type":"PlainText"} }}',
            hideDecimalForWholeNumbers: false,
        };
    </script>

    <?php
    echo $this->headTitle($this->title_page);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->setHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendHttpEquiv('language', 'pt-BR')
        ->appendName('robots', 'noindex, nofollow')
        ->appendName('title', $this->title)
        ->appendName('description', $this->description_page);

    echo $this->headLink()
        // ->appendStylesheet('/public/assets/addons/semantic/semantic.min.css')
        // ->appendStylesheet('/public/assets/addons/uikit/css/uikit.min.css')
        ->appendStylesheet('/public/assets/css/style.default.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.light.css?v=' . time())
        //                ->appendStylesheet('/public/assets/css/style.dark.css?v=' . time())
    ;
    ?>
</head>

<body>

    <?php echo $this->layout()->content; ?>

    <!-- <script
            src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5ed1cf34bf802c5f339f8167"
            type="text/javascript"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"
        ></script> -->
    <?php
    echo $this->headScript()
        // ->prependFile('/public/assets/addons/semantic/semantic.min.js')
        // ->prependFile('/public/assets/addons/uikit/js/uikit-icons.min.js')
        // ->prependFile('/public/assets/addons/uikit/js/uikit.min.js')
        // ->prependFile('/public/config/default.js')
        // ->prependFile('/public/assets/addons/mask/mask.min.js')
        ->prependFile('/public/assets/addons/jquery/jquery.min.js');
    ?>
    <script src="/public/assets/js/webflow.2f7557476.js" type="text/javascript"></script>
    <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->

</body>

</html>