<section class="uk-section uk-section-secondary" uk-height-viewport>
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-large">
                <div class="uk-card uk-card-body uk-card-muted uk-text-center">
                    <img class="uk-width-1-2" src="/public/assets/images/logotipo.webp" alt="Logotipo" />
                    <p class="uk-text-meta uk-margin-remove-top"><?php echo $this->description ?></p>
                    <hr class="uk-divider-small" />
                    <form class="ui inverted form on-form-access" autocomplete="off">
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1">
                                <div class="field required">
                                    <label>Usuário</label>
                                    <input type="text" name="email_user" placeholder="Informe seu usuário" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1">
                                <div class="field required">
                                    <label>Senha</label>
                                    <input type="password" name="password_user" placeholder="Informe sua senha" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1">
                                <div class="field">
                                    <button class="ui primary button">Entrar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>