
        <div class="section places wf-section">
            <div style="opacity: 0;" class="container">
                <div>
                    <h1 class="places_h1">Lugares Incríveis</h1>
                    <p class="max_550">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.
                    </p>
                </div>
                <div class="w-dyn-list">
                    <div role="list" class="places-collection-list w-dyn-items">
                        <div role="listitem" class="w-dyn-item">
                            <div class="more-places-card">
                                <a
                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed607afba2aedb76aa630e4_david-gavi-AdIJ9S-kbrc-unsplash.jpg');"
                                    href="/places/place"
                                    class="card_image_hover_expand w-inline-block"
                                ></a>
                                <h5 class="card_title place">Siwa Oasis, Egito</h5>
                            </div>
                        </div>
                        <div role="listitem" class="w-dyn-item">
                            <div class="more-places-card">
                                <a
                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed608592e00bf84ef793a33_paul-carmona-5UHgm0Q3n4Y-unsplash.jpg');"
                                    href="/places/place"
                                    class="card_image_hover_expand w-inline-block"
                                ></a>
                                <h5 class="card_title place">Sydney, Austrália</h5>
                            </div>
                        </div>
                        <div role="listitem" class="w-dyn-item">
                            <div class="more-places-card">
                                <a
                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ee1e23130645f79e1439688_steven-lasry-8odmdG19pOY-unsplash.jpg');"
                                    href="/places/place"
                                    class="card_image_hover_expand w-inline-block"
                                ></a>
                                <h5 class="card_title place">Kashmir, Índia</h5>
                            </div>
                        </div>
                        <div role="listitem" class="w-dyn-item">
                            <div class="more-places-card">
                                <a
                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed44d9ea0977f84cc4cc79e_denys-nevozhai-guNIjIuUcgY-unsplash%20(1).jpg');"
                                    href="/places/place"
                                    class="card_image_hover_expand w-inline-block"
                                ></a>
                                <h5 class="card_title place">Ko Samui, Tailândia</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <img
                src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg"
                style="
                    -webkit-transform: translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                    -moz-transform: translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                    -ms-transform: translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                    transform: translate3d(0, 0, 0) scale3d(0, 0, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                    opacity: 0;
                "
                alt=""
                class="confetti_hero_svg"
            />
        </div>