<div class="row">
    <div class="column">
        <div class="ui breadcrumb">
            <a class="section" href="/account/dashboard">Início</a>
            <div class="divider"> / </div>
            <div class="active section"><?php echo $this->title_page ?></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
        <div class="ui segments" id="onCardFilter">
            <div class="ui right aligned segment">
                <button class="ui <?php echo Zend_Auth::getInstance()->getIdentity()->filter_toggle == 1 ? '' : 'black' ?> icon labeled button uk-float-right" id="onButtonFilter"><?php echo Zend_Auth::getInstance()->getIdentity()->filter_toggle == 1 ? '<i class="eye slash icon"></i> Ocultar' : '<i class="eye icon"></i> Mostrar' ?></button>
            </div>
            <div class="ui segment uk-card-body" <?php echo Zend_Auth::getInstance()->getIdentity()->filter_toggle == 1 ? '' : 'style="display:none"' ?>>
                <form class="ui equal width form" id="onFormFilter">
                    <div class="fields">
                        <div class="field">
                            <label>Contatos</label>
                            <div class="ui search selection fluid dropdown on-dropdown-contact">
                                <input type="hidden" name="filter_id_contact" value="<?php echo Zend_Auth::getInstance()->getIdentity()->filter_id_contact ?>" />
                                <i class="dropdown icon"></i>
                                <input type="text" class="search" tabindex="0" />
                                <span class="sizer"></span>
                                <div class="default text">Selecione...</div>
                                <div class="menu" tabindex="-1"></div>
                            </div>
                        </div>
                        <div class="field">
                            <label>Contas</label>
                            <div class="ui search selection fluid dropdown on-dropdown-account">
                                <input type="hidden" name="filter_id_account" value="<?php echo Zend_Auth::getInstance()->getIdentity()->filter_id_account ?>" />
                                <i class="dropdown icon"></i>
                                <input type="text" class="search" tabindex="0" />
                                <span class="sizer"></span>
                                <div class="default text">Selecione...</div>
                                <div class="menu" tabindex="-1"></div>
                            </div>
                        </div>
                    </div>
                    <div class="fields">
                        <div class="field">
                            <label>Período</label>
                            <div class="ui fluid selection dropdown on-dropdown-type-period">
                                <input type="hidden" name="filter_id_type_period" value="<?php echo Zend_Auth::getInstance()->getIdentity()->filter_id_type_period ?>" />
                                <i class="dropdown icon"></i>
                                <div class="default text">Selecione...</div>
                                <div class="menu">
                                    <div class="item" data-value="1">Hoje</div>
                                    <div class="item" data-value="2">Esta semana</div>
                                    <div class="item" data-value="3">Este mês</div>
                                    <div class="item" data-value="4">Este ano</div>
                                    <div class="item" data-value="9">Personalizado</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="fields" id="onColFilterPeriod" style="display: <?php echo Zend_Auth::getInstance()->getIdentity()->filter_id_type_period == 9 ? 'flex' : 'none' ?>">
                        <div class="field">
                            <label>De</label>
                            <input type="date" name="filter_period_min" value="<?php echo Zend_Auth::getInstance()->getIdentity()->filter_period_min ?>" />
                        </div>
                        <div class="field">
                            <label>Até</label>
                            <input type="date" name="filter_period_max" value="<?php echo Zend_Auth::getInstance()->getIdentity()->filter_period_max ?>" />
                        </div>
                    </div>
                    <div class="fields">
                        <div class="field">
                            <button class="ui primary button" type="submit">Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
        <div class="ui segment">
            <table class="ui very basic inverted selectable table" id="onTableOrder">
                <thead>
                    <tr>
                        <th></th>
                        <th>Descrição</th>
                        <th>Contato</th>
                        <th>Conta</th>
                        <th>Categoria</th>
                        <th>Data</th>
                        <th>Valor</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th> 
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th> 
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<div class="ui small modal" id="onModalCreate">
    <div class="header">Novo registro</div>
    <div class="content">
        <form class="ui equal width form">
            <div class="fields">
                <div class="four wide field required">
                    <label>Tipo</label>
                    <div class="ui fluid selection dropdown on-dropdown">
                        <input type="hidden" name="id_type_order">
                        <i class="dropdown icon"></i>
                        <div class="default text">Selecione...</div>
                        <div class="menu">
                            <div class="item" data-value="1">
                                <i class="circle green icon"></i> Entrada
                            </div>
                            <div class="item" data-value="2">
                                <i class="circle red icon"></i> Saída
                            </div>
                        </div>
                    </div>
                </div>
                <div class="six wide field required">
                    <label>Descrição</label>
                    <input type="text" name="description_order" maxlength="256" />
                </div>
                <div class="six wide field required">
                    <label>Cliente</label>
                    <div class="ui search selection dropdown on-dropdown-contact">
                        <input type="hidden" name="id_contact">
                        <i class="dropdown icon"></i>
                        <input type="text" class="search" tabindex="0" />
                        <span class="sizer"></span>
                        <div class="default text">Selecione...</div>
                        <div class="menu" tabindex="-1"></div>
                    </div>
                </div>
            </div>
            <div class="fields">
                <div class="four wide field required">
                    <label>Data</label>
                    <input type="date" name="date_due_order" />
                </div>
                <div class="six field required">
                    <label>Conta</label>
                    <div class="ui search selection dropdown on-dropdown-account">
                        <input type="hidden" name="id_account">
                        <i class="dropdown icon"></i>
                        <input type="text" class="search" tabindex="0" />
                        <span class="sizer"></span>
                        <div class="default text">Selecione...</div>
                        <div class="menu" tabindex="-1"></div>
                    </div>
                </div>
                <div class="six field required">
                    <label>Categoria</label>
                    <div class="ui search selection dropdown on-dropdown-category">
                        <input type="hidden" name="id_category">
                        <i class="dropdown icon"></i>
                        <input type="text" class="search" tabindex="0" />
                        <span class="sizer"></span>
                        <div class="default text">Selecione...</div>
                        <div class="menu" tabindex="-1"></div>
                    </div>
                </div>
            </div>
            <div class="fields">
                <div class="four wide field required">
                    <label>Valor</label>
                    <input type="text" name="price_order" class="on-mask-money" />
                </div>
                <div class="four wide field required">
                    <label>Status</label>
                    <div class="ui fluid selection dropdown on-dropdown">
                        <input type="hidden" name="situation_order">
                        <i class="dropdown icon"></i>
                        <div class="default text">Selecione...</div>
                        <div class="menu">
                            <div class="item" data-value="1">
                                <i class="circle green icon"></i> Baixado
                            </div>
                            <div class="item" data-value="0">
                                <i class="circle yellow icon"></i> Em aberto
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> Salvar</button>
    </div>
</div>

<div class="ui small modal" id="onModalUpdate">
    <div class="header">Atualizar registro</div>
    <div class="content">
        <form class="ui equal width form">
            <div class="fields">
                <div class="four wide field required">
                    <label>Tipo</label>
                    <div class="ui fluid selection dropdown on-dropdown">
                        <input type="hidden" name="id_type_order">
                        <i class="dropdown icon"></i>
                        <div class="default text">Selecione...</div>
                        <div class="menu">
                            <div class="item" data-value="1">
                                <i class="circle green icon"></i> Entrada
                            </div>
                            <div class="item" data-value="2">
                                <i class="circle red icon"></i> Saída
                            </div>
                        </div>
                    </div>
                </div>
                <div class="six wide field required">
                    <label>Descrição</label>
                    <input type="text" name="description_order" maxlength="256" />
                </div>
                <div class="six wide field required">
                    <label>Cliente</label>
                    <div class="ui search selection dropdown on-dropdown-contact">
                        <input type="hidden" name="id_contact">
                        <i class="dropdown icon"></i>
                        <input type="text" class="search" tabindex="0" />
                        <span class="sizer"></span>
                        <div class="default text">Selecione...</div>
                        <div class="menu" tabindex="-1"></div>
                    </div>
                </div>
            </div>
            <div class="fields">
                <div class="four wide field required">
                    <label>Data</label>
                    <input type="date" name="date_due_order" />
                </div>
                <div class="six field required">
                    <label>Conta</label>
                    <div class="ui search selection dropdown on-dropdown-account">
                        <input type="hidden" name="id_account">
                        <i class="dropdown icon"></i>
                        <input type="text" class="search" tabindex="0" />
                        <span class="sizer"></span>
                        <div class="default text">Selecione...</div>
                        <div class="menu" tabindex="-1"></div>
                    </div>
                </div>
                <div class="six field required">
                    <label>Categoria</label>
                    <div class="ui search selection dropdown on-dropdown-category">
                        <input type="hidden" name="id_category">
                        <i class="dropdown icon"></i>
                        <input type="text" class="search" tabindex="0" />
                        <span class="sizer"></span>
                        <div class="default text">Selecione...</div>
                        <div class="menu" tabindex="-1"></div>
                    </div>
                </div>
            </div>
            <div class="fields">
                <div class="four wide field required">
                    <label>Valor</label>
                    <input type="text" name="price_order" class="on-mask-money" />
                </div>
                <div class="four wide field required">
                    <label>Status</label>
                    <div class="ui fluid selection dropdown on-dropdown">
                        <input type="hidden" name="situation_order">
                        <i class="dropdown icon"></i>
                        <div class="default text">Selecione...</div>
                        <div class="menu">
                            <div class="item" data-value="1">
                                <i class="circle green icon"></i> Baixado
                            </div>
                            <div class="item" data-value="0">
                                <i class="circle yellow icon"></i> Em aberto
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <button class="ui labeled icon secondary deny button"><i class="close icon"></i> Cancelar</button>
        <button class="ui labeled icon primary ok button"><i class="check icon"></i> salvar</button>
    </div>
</div>