<section class="uk-section uk-section-secondary on-border-bottom">
    <div class="uk-container">
        <div class="uk-flex uk-flex-middle" uk-grid>
            <div class="uk-width-1-1@s uk-text-center">
                <h2 class="uk-h2"><?php echo $this->message ?></h2>
                <p class="uk-text-lead"><b>Mensagem:</b> <?php echo $this->exception->getMessage() ?></p>
            </div>
        </div>
    </div>
</section>
