
        <div class="uk-card uk-card-body uk-card-default uk-card-small">
            <form class="ui form on-form-company">
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-2@s">
                        <div class="field disabled">
                            <label>Documento (CNPJ)</label>
                            <input type="text" name="document_company" class="on-mask-cnpj" disabled />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-2@s">
                        <div class="field disabled">
                            <label>Razão social</label>
                            <input type="text" name="name_company" disabled />
                        </div>
                    </div>
                    <div class="uk-width-1-2@s">
                        <div class="field disabled">
                            <label>Nome fantasia</label>
                            <input type="text" name="nickname_company" disabled />
                        </div>
                    </div>
                </div>
                <hr class="uk-divider-small" />
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-2@s">
                        <div class="field disabled">
                            <label>CEP</label>
                            <input type="text" name="zipcode_company" disabled />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-2-3@s">
                        <div class="field disabled">
                            <label>Endereço</label>
                            <input type="text" name="public_place_company" disabled />
                        </div>
                    </div>
                    <div class="uk-width-1-3@s">
                        <div class="field disabled">
                            <label>Número</label>
                            <input type="text" name="number_company" disabled />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-1-1">
                        <div class="field disabled">
                            <label>Complemento</label>
                            <input type="text" name="complament_company" disabled />
                        </div>
                    </div>
                </div>
                <div class="uk-grid-small" uk-grid>
                    <div class="uk-width-expand@s">
                        <div class="field disabled">
                            <label>Bairro</label>
                            <input type="text" name="public_place_company" disabled />
                        </div>
                    </div>
                    <div class="uk-width-expand@s">
                        <div class="field disabled">
                            <label>Cidade</label>
                            <input type="text" name="city_company" disabled />
                        </div>
                    </div>
                    <div class="uk-width-small@s">
                        <div class="field disabled">
                            <label>UF</label>
                            <input type="text" name="state_company" disabled />
                        </div>
                    </div>
                </div>
            </form>
        </div>