<section class="uk-section uk-section-secondary on-border-bottom">

    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>

            <div class="uk-width-1-2@s">
                <p class="uk-text-meta"><span uk-icon="icon: calendar"></span> <?php echo date('d/m/Y', strtotime($this->post['date_post'])) ?></p>
                <h1 class="uk-h1"><?php echo $this->title_page ?></h1>
                <p class="uk-text-lead"><?php echo $this->description_page ?></p>
                <p class="uk-text-meta"><?php echo $this->post['name_team'] ?><br /><?php echo $this->post['job_role_team'] ?></p>
            </div>
        </div>
    </div>
</section>

<section class="uk-section on-border-bottom" id="projetos">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-2-3@s">
                <img src="<?php echo $this->post['image_post'] ?>" alt="Logotipo" />
                <hr class="uk-divider-small" />
                <div class="uk-text-meta"><?php echo $this->post['content_post'] ?></div>
            </div>
        </div>
    </div>
</section>

<section class="uk-section on-border-bottom" id="servicos">
    <div class="uk-container">
        <div class="uk-flex uk-flex-center" uk-grid>
            <div class="uk-width-2-3@s">
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                
            <h2 class="uk-h2">Solicite um orçamento</h2>
                <p class="uk-text-lead">Gostou do conteúdo? Deixe o trabalho pesado com profissionais que entendem de estratégias de marketing.</p>
                    
                <form class="ui form on-form-contact">
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field required">
                                    <label>Nome</label>
                                    <input type="text" name="name" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-2@s">
                                <div class="field required">
                                    <label>Telefone</label>
                                    <input type="text" name="phone" class="on-mask-phone" />
                                </div>
                            </div>
                            <div class="uk-width-1-2@s">
                                <div class="field required">
                                    <label>E-mail</label>
                                    <input type="text" name="email" />
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field">
                                    <label>Mensagem</label>
                                    <textarea name="message" rows="3"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="uk-grid-small" uk-grid>
                            <div class="uk-width-1-1@s">
                                <div class="field">
                                    <button class="uk-button uk-button-primary">Enviar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

        
<section class="uk-section on-border-bottom" id="servicos">
    <div class="uk-container">
        <div uk-grid>
            <div class="uk-width-1-2@s">
                <h2 class="uk-h2">Publicações relacionadas</h2>
            </div>
            <div class="uk-width-1-2@s uk-text-right">
                <button class="uk-button uk-button-default">Ver Todas</button>
            </div>
        </div>
        <div class="uk-child-width-1-2@s uk-grid-small uk-grid-match on-post-related" uk-grid>
            <div>
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <div uk-grid>
                        <div class="uk-width-1-3@s">
                            <div class="ui inverted placeholder">
                                <div class="square image"></div>
                            </div>
                        </div>
                        <div class="uk-width-2-3@s">
                            <div class="header">
                                <div class="line"></div>
                            </div>
                            <div class="paragraph">
                                <div class="line"></div>
                                <div class="line"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="uk-card uk-card-body uk-card-default uk-border-radius">
                    <div uk-grid>
                        <div class="uk-width-1-3@s">
                            <div class="ui inverted placeholder">
                                <div class="square image"></div>
                            </div>
                        </div>
                        <div class="uk-width-2-3@s">
                            <div class="header">
                                <div class="line"></div>
                            </div>
                            <div class="paragraph">
                                <div class="line"></div>
                                <div class="line"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>