
<div class="row">
    <div class="column">
        <div class="ui tall stacked segments">
            <div class="ui segment">
                <div class="ui equal width grid">
                    <div class="row">
                        <div class="column">
                            <div class="ui text menu" data-color="inverted white">
                                <a class="item">
                                    <img width="64" src="/public/assets/images/logotipo/logotipo.svg" alt="Logotipo" />
                                </a>
                                <a class="logo item">
                                    <div>
                                        ONDS
                                        <div class="uk-navbar-subtitle">Agência Digital</div>
                                    </div>
                                </a>
                                <a class="right item">
                                    <div>
                                        CNPJ: 33.068.382/0001-44
                                        <div class="uk-navbar-subtitle">suporte@onds.com.br</div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui violet inverted segment">
                <h1 class="ui aligned center header">Orçamento #<span id="reference_order_service">...</span></h1>
            </div>
            <div class="ui segment">
                <div class="ui grey segment">
                    <div class="ui equal width grid stackable">
                        <div class="row">
                            <div class="column">
                                <strong>Cliente:</strong><br />
                                <span id="name_contact">...</span>
                            </div>
                            <div class="column">
                                <strong>Telefone:</strong><br />
                                <span id="phone_primary_contact">...</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ui equal width grid stackable">
                    <div class="row">
                        <div class="six wide column">
                            <strong>Descrição:</strong><br />
                            <span id="description_order_service">...</span>
                        </div>
                        <div class="column">
                            <div class="ui equal width grid stackable">
                                <div class="row">
                                    <div class="column">
                                        <strong>Emissão:</strong><br />
                                        <span id="datetime_order_service">...</span>
                                    </div>
                                    <div class="column">
                                        <strong>Validade:</strong><br />
                                        <span id="date_validity_order_service">...</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="column">
                                        <strong>Prazo:</strong><br />
                                        <span id="deadline_order_service">...</span>
                                    </div>
                                    <div class="column">
                                        <strong>Forma de pagamento:</strong><br />
                                        <span id="payment_order_service">...</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="column">
                                        <strong>Responsável:</strong><br />
                                        <span id="name_user">...</span>
                                    </div>
                                    <div class="column">
                                        <strong>Situação:</strong><br />
                                        <span id="name_order_service_status">...</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui grey inverted segment">
                <h2 class="ui aligned center header">Serviços prestados</h2>
            </div>
            <div class="ui segment">
                <table class="ui very basic table" id="onTableOrderSeviceItem">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Quant.</th>
                            <th>Parcial</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Subtotal</th>
                            <th id="">à combinar</th>
                        </tr>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Desconto</th>
                            <th id="price_discount_order_service">0,00</th>
                        </tr>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Total</th>
                            <th id="">à combinar</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
