<div class="uk-section">
    <div class="uk-flex uk-flex-center" uk-grid>
        <div class="uk-width-1-2">
            <h1 class="uk-h1 uk-text-uppercase uk-text-primary uk-margin-remove-bottom">
                Promoções
            </h1>
            
            <div uk-slideshow="animation: push">
                <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1">
                    <ul class="uk-slideshow-items">
                        <li>
                            <img src="https://www.ie.com.br/wp-content/uploads/2022/03/banner.webp" alt="" uk-cover />
                        </li>
                    </ul>
                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>
                </div>
                <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>
            </div>

            <h2 class="uk-h2 uk-text-uppercase uk-text-primary">Regras</h2>
            
            <p class="uk-text-meta">
                1) Operação Especial de Abril: Orlando Soccer Camp<br />
                Missão: Salvar o Programa | Meta mínima de vendas: 10 matrículas<br />
                Data da missão: 1 a 30/Abril
            </p>

            <p class="uk-text-meta">
                Prêmio:<br />
                > bônus de R$ 1.000 (para as 3 primeiras matrículas com pagamento confirmado. Válido somente membros do SCM que estiveram na reunião do dia 12/Abril) <br />
                > R$ 750  (para as 7 matrículas seguintes. Válido somente membros do SCM que estiveram na reunião do dia 12/Abril) <br />
                > R$ 350 (bônus mínimo em Abril, para membros SCM) <br />
                > R$ 150 (bônus para quem não é do SCM)<br />
                * os prêmios de R$ 1000 e R$ 750 serão pagos somente se alcançarmos as 10 vendas por membros do SCM. Caso seja menor que 10, todos receberão o bônus de R$ 350.<br />
                * os prêmios maiores serão pagos somente para quem esteve presente na reunião virtual. Quem não esteve, receberá o bônus de R$ 350.<br />
            </p>
            <p class="uk-text-meta">
                Dúvidas e Dicas de vendas Orlando Soccer Camp<br />
                19/Abril (terça-feira) das 11:00 às 11:40<br />
                Caso tenha interesse de participar confirme sua presença através deste email. (exclusivo para membros SCM)<br />
            </p>
        </div>
    </div>
</div>