<div class="section contact wf-section">
    <div class="container contact_container" style="opacity: 1;">
        <div class="contact_left">
            <h6>Alguma dúvida?</h6>
            <h2>Envie sua mensagem.</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
        </div>
        <div class="form-block-2 w-form">
            <form id="wf-form-Contact-Form" name="wf-form-Contact-Form" data-name="Contact Form" method="get" class="form-2" aria-label="Contact Form">
                <div class="_50_percent_field_contain">
                    <input
                        type="text"
                        class="text-field _50_percent w-input"
                        maxlength="256"
                        name="First-Name-2"
                        data-name="First Name 2"
                        placeholder="Nome*"
                        data-w-id="0e6215dc-3b13-6dd5-7102-da84d7e264e4"
                        id="First-Name-2"
                        required=""
                        style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;"
                    />
                    <input
                        type="text"
                        class="text-field _50_percent w-input"
                        maxlength="256"
                        name="Last-Name-2"
                        data-name="Last Name 2"
                        placeholder="Sobrenome*"
                        data-w-id="0e6215dc-3b13-6dd5-7102-da84d7e264e5"
                        id="Last-Name-2"
                        required=""
                        style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;"
                    />
                </div>
                <div class="_50_percent_field_contain">
                    <input
                        type="email"
                        class="text-field _50_percent w-input"
                        maxlength="256"
                        name="Email-Address-2"
                        data-name="Email Address 2"
                        placeholder="E-mail*"
                        data-w-id="0e6215dc-3b13-6dd5-7102-da84d7e264e7"
                        id="Email-Address-2"
                        required=""
                        style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;"
                    />
                    <input
                        type="tel"
                        class="text-field _50_percent w-input"
                        maxlength="256"
                        name="Phone-Number-2"
                        data-name="Phone Number 2"
                        placeholder="Telefone"
                        data-w-id="0e6215dc-3b13-6dd5-7102-da84d7e264e8"
                        id="Phone-Number-2"
                        required=""
                        style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;"
                    />
                </div>
                <textarea
                    class="textarea w-input"
                    maxlength="5000"
                    name="Your-message-2"
                    data-name="Your Message 2"
                    placeholder="Sua mensagem..."
                    data-w-id="0e6215dc-3b13-6dd5-7102-da84d7e264e9"
                    id="Your-message-2"
                    style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg); transform-style: preserve-3d;"
                ></textarea>
                <input type="submit" value="Enviar" data-wait="Please wait..." data-w-id="0e6215dc-3b13-6dd5-7102-da84d7e264ea" class="submit-button _2 w-button" style="opacity: 1;" />
            </form>
            <div class="success-message w-form-done" tabindex="-1" role="region" aria-label="Contact Form success"><div>Thank you! Your submission has been received!</div></div>
            <div class="error-message w-form-fail" tabindex="-1" role="region" aria-label="Contact Form failure"><div class="text-block">Oops! Something went wrong while submitting the form.</div></div>
        </div>
    </div>
    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg" width="400" alt="" class="contact-confetti" />
</div>
