<div class="uk-section">
    <div uk-grid>
        <div class="uk-width-1-2" <h1 class="uk-h1">
            Bem vindo<br />
            <?php echo Zend_Auth::getInstance()->getIdentity()->name_user ?>
            </h1>
            <a class="uk-link" href="/account/user">Ficha completa</a>
        </div>
        <div class="uk-width-1-2">
            <div uk-slideshow="animation: push">
                <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1">
                    <ul class="uk-slideshow-items">
                        <li>
                            <img src="/public/assets/images/promo-1.jpg" alt="" uk-cover />
                        </li>
                        <li>
                            <img src="/public/assets/images/promo-1.jpg" alt="" uk-cover />
                        </li>
                        <li>
                            <img src="/public/assets/images/promo-1.jpg" alt="" uk-cover />
                        </li>
                    </ul>
                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>
                </div>
                <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <div class="ui segment">
                <h4 class="ui header">Promoções</h4>
                <div class="ui three column grid">
                    <div class="column">
                        <div class="ui segment">
                            <div class="ui inverted placeholder">
                                <div class="paragraph">
                                    <div class="medium line"></div>
                                    <div class="short line"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="ui segment">
                            <div class="ui inverted placeholder">
                                <div class="paragraph">
                                    <div class="medium line"></div>
                                    <div class="short line"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="ui segment">
                            <div class="ui inverted placeholder">
                                <div class="paragraph">
                                    <div class="medium line"></div>
                                    <div class="short line"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h4 class="ui header">Resumo de Vendas</h4>
    <div class="row">
        <div class="twelve wide column">
            <div class="ui three column grid">
                <div class="column">
                    <div class="ui segment">
                        <div class="ui inverted placeholder">
                            <div class="paragraph">
                                <div class="medium line"></div>
                                <div class="short line"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <div class="ui inverted placeholder">
                            <div class="paragraph">
                                <div class="medium line"></div>
                                <div class="short line"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <div class="ui inverted placeholder">
                            <div class="paragraph">
                                <div class="medium line"></div>
                                <div class="short line"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="twelve wide column">
            <div class="ui segment">
                <figure class="highcharts-figure">
                    <div id="on-container-in-out">
                        <h6 class="uk-h6 uk-margin-remove uk-text-center">Carregando...</h6>
                    </div>
                </figure>
            </div>
        </div>
    </div>

</div>