
<div class="row">
    <div class="column">
        <div class="ui segment">
            <h4 class="ui header">Promoções</h4>
            <div class="ui seven column grid">
                <div class="column">
                    <div class="ui segment">
                        <div class="ui inverted placeholder">
                            <div class="paragraph">
                                <div class="medium line"></div>
                                <div class="short line"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <div class="ui inverted placeholder">
                            <div class="paragraph">
                                <div class="medium line"></div>
                                <div class="short line"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="ui segment">
                        <div class="ui inverted placeholder">
                            <div class="paragraph">
                                <div class="medium line"></div>
                                <div class="short line"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<h4 class="ui header">Resumo de Vendas</h4>
<div class="row">
    <div class="four wide column">
        <div class="ui segment">
            <div class="ui inverted placeholder">
                <div class="paragraph">
                    <div class="medium line"></div>
                    <div class="short line"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="twelve wide column">
        <div class="ui three column grid on-slider-accounts">
            <div class="column">
                <div class="ui segment">
                    <div class="ui inverted placeholder">
                        <div class="paragraph">
                            <div class="medium line"></div>
                            <div class="short line"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="ui segment">
                    <div class="ui inverted placeholder">
                        <div class="paragraph">
                            <div class="medium line"></div>
                            <div class="short line"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="ui segment">
                    <div class="ui inverted placeholder">
                        <div class="paragraph">
                            <div class="medium line"></div>
                            <div class="short line"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="twelve wide column">
        <div class="ui segment">
            <figure class="highcharts-figure">
                <div id="on-container-in-out">
                    <h6 class="uk-h6 uk-margin-remove uk-text-center">Carregando...</h6>
                </div>
            </figure>
        </div>
    </div>
</div>
