<div class="uk-section">
    <div uk-grid>
        <div class="uk-width-1-2">
            <h1 class="uk-h1 uk-text-uppercase uk-text-primary uk-margin-remove-bottom">
                Bem vindo
            </h1>
            <p class="uk-text-lead uk-text-uppercase uk-text-primary uk-margin-remove-top">
                <?php echo Zend_Auth::getInstance()->getIdentity()->name_user ?>
            </p>
            <a class="uk-text-lead uk-link uk-text-primary" href="/account/user">
                GOLD - TOP SELLER<br />
                <small>VALIDO ATÉ 08/05/2022</small>
            </a>
            <h2 class="uk-h2 uk-text-uppercase uk-text-primary">Conquistas</h2>
            <ul class="uk-list uk-text-primary">
                <li>TOP SELLER JANEIRO</li>
                <li>CAMPANHA BLACK WEEK</li>
                <li>TOP SELLER DEZEMBRO</li>
            </ul>
            <h2 class="uk-h2 uk-text-uppercase uk-text-primary">Prêmios Obtidos</h2>
            <ul class="uk-list uk-text-primary">
                <li>BÔNUS NO CARTÃO R$ 500</li>
                <li>VIAGEM FLORIANOPOLIS</li>
                <li>KIT SCM GOLD</li>
            </ul>
        </div>
        <div class="uk-width-1-2 uk-text-center">
            <div uk-slideshow="animation: push">
                <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1">
                    <ul class="uk-slideshow-items">
                        <li>
                            <img src="https://www.ie.com.br/wp-content/uploads/2022/03/banner.webp" alt="" uk-cover />
                        </li>
                    </ul>
                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>
                </div>
                <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>
            </div>
            <a class="uk-link uk-text-primary" href="/account/promotion">CLIQUE SAIBA AS REGRAS E SE INSCREVA</a>
        </div>
    </div>
</div>