<div class="section blog-category wf-section">
    <div class="container tags_heading" style="opacity: 1;"><h2>Categoria</h2></div>
    <div class="container blog_posts" style="opacity: 1;">
        <div class="blog-collection-list-wrapper on-category-template w-dyn-list">
            <div role="list" class="blog-collection-list w-dyn-items">
                <div role="listitem" class="w-dyn-item">
                    <a href="/blog/post" class="story_wrap w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede4ee313bfb8d870b0b7_ammie-ngo-vcu-OZBxxRk-unsplash.jpg');" class="story_image on_blog_page">
                            <div style="background-color: hsla(40.48780487804878, 96.85%, 49.8%, 1);" class="category"><div>Categoria</div></div>
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede4ee313bfb8d870b0b7_ammie-ngo-vcu-OZBxxRk-unsplash.jpg');" class="card_image_hover_expand"></div>
                        </div>
                        <div class="story_content">
                            <h4>Minha viagem ao Vietnã</h4>
                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae</p>
                            <div class="travelteller_wrap">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle"></div>
                                <h6>Natasha Miles</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div role="listitem" class="w-dyn-item">
                    <a href="/blog/post" class="story_wrap w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');" class="story_image on_blog_page">
                            <div style="background-color: #faaa04;" class="category"><div>Places</div></div>
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');" class="card_image_hover_expand"></div>
                        </div>
                        <div class="story_content">
                            <h4>Os melhores lugares do Peru para visitar</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum.</p>
                            <div class="travelteller_wrap">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="travelteller_circle"></div>
                                <h6>Michelle Worthy</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div role="listitem" class="w-dyn-item">
                    <a href="/blog/post" class="story_wrap w-inline-block">
                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');" class="story_image on_blog_page">
                            <div style="background-color: #faaa04;" class="category"><div>Places</div></div>
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');" class="card_image_hover_expand"></div>
                        </div>
                        <div class="story_content">
                            <h4>As diversas ilhas da Tailândia</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <div class="travelteller_wrap">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle"></div>
                                <h6>Mason Miller</h6>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="sticky-nav-contain">
            <div class="sticky">
                <h4>Outras Categorias</h4>
                <div class="line div"></div>
                <div class="blog_categories_contain">
                    <div class="w-dyn-list">
                        <div role="list" class="category-tags-collection-list w-dyn-items">
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #03c1d6;" href="/blog/category" class="category with-margin w-inline-block"><div>Inspiration</div></a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #9502f3;" href="/blog/category" class="category with-margin w-inline-block"><div>Culture</div></a>
                            </div>
                            <div role="listitem" class="w-dyn-item">
                                <a style="background-color: #ff0149;" href="/blog/category" class="category with-margin w-inline-block"><div>Experience</div></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="_30px-div"></div>
                <h4>Viajantes</h4>
                <div class="line div"></div>
                <div class="top_traveltellers_collection-list-wrapper on-blog w-dyn-list">
                    <div role="list" class="w-dyn-items">
                        <div role="listitem" class="w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Rachelle Mindy</h5>
                                    <div class="text_block">New York, USA</div>
                                </div>
                            </a>
                        </div>
                        <div role="listitem" class="w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Mason Miller</h5>
                                    <div class="text_block">Amsterdam, Netherlands</div>
                                </div>
                            </a>
                        </div>
                        <div role="listitem" class="w-dyn-item">
                            <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div>
                                    <h5>Natasha Miles</h5>
                                    <div class="text_block">Paris, France</div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
