
        <!-- <div class="newsletter_popup">
            <div class="newsletter">
                <div class="newsletter-title-and-image-wrap">
                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg" alt="" class="image-8" />
                    <div class="form-wrap">
                        <h2 class="align_center">Join the community</h2>
                        <p class="center">Subscribe to our newsletter to stay informed and connected.</p>
                        <div class="w-form">
                            <form id="email-form" name="email-form" data-name="Email Form" method="get">
                                <input type="email" class="text-field newsletter-form w-input" maxlength="256" name="email-2" data-name="Email 2" placeholder="Enter your email..." id="email-2" required="" />
                                <input type="submit" value="Submit" data-wait="Please wait..." class="submit-button newsletter-button w-button" />
                            </form>
                            <div class="success-message newsletter-success-message w-form-done"><div>Thank you! Your submission has been received!</div></div>
                            <div class="w-form-fail"><div>Oops! Something went wrong while submitting the form.</div></div>
                        </div>
                    </div>
                </div>
                <div data-w-id="98e59693-2cfb-f947-5375-5e08d59b729f" class="close-wrapper">
                    <div class="close-line"></div>
                    <div class="close-line line-2"></div>
                </div>
            </div>
        </div> -->
        <div class="section blog_hero wf-section">
            <div class="container blog_hero_content">
                <h1 class="white_h1 max_700">Celebrando experiências juntos</h1>
                <p class="blog_subtitle">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.
                </p>
                <a href="#Blog" class="button w-button">Explore</a>
            </div>
            <div class="search-and-slider_contain">
                <form action="/search" class="search blog_page w-form">
                    <input type="search" class="search-input on_blog_page w-input" maxlength="256" name="query" placeholder="Search stories…" id="search" required="" />
                    <input type="submit" value="⌕" class="search-button on_blog_pag w-button" />
                </form>
                <div
                    data-delay="4000"
                    data-animation="fade"
                    class="testimonial-slider w-slider"
                    data-autoplay="true"
                    data-easing="ease"
                    data-hide-arrows="false"
                    data-disable-swipe="false"
                    data-autoplay-limit="0"
                    data-nav-spacing="3"
                    data-duration="800"
                    data-infinite="true"
                >
                    <div class="slider_nav"><h6 class="white_h6">Depoimentos</h6></div>
                    <div class="w-slider-mask">
                        <div class="testimonial-slide w-slide">
                            <img
                                src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfc490df1c488f0e75a4_ray-berry-k89o-pl3sm0-unsplash%20(1).jpg"
                                width="394"
                                sizes="(max-width: 479px) 100vw, (max-width: 767px) 62vw, (max-width: 991px) 45vw, 40vw"
                                srcset="
                                    https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfc490df1c488f0e75a4_ray-berry-k89o-pl3sm0-unsplash%20(1)-p-1080.jpeg 1080w,
                                    https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfc490df1c488f0e75a4_ray-berry-k89o-pl3sm0-unsplash%20(1).jpg         1290w
                                "
                                alt=""
                                class="testimonial-image"
                            />
                            <p class="quote">
                                O imtercâmbio me permitiu me conectar com outros viajantes com quem posso compartilhar minhas experiências. Eu amo esta comunidade e todas as pessoas incríveis que conheci!<br />
                                <span class="bold">-Matt Ryan</span>
                            </p>
                        </div>
                        <div class="testimonial-slide w-slide">
                            <img
                                src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfd6c8b6a11089ec02db_neora-aylon-YCTUXuXsSu8-unsplash%20(1).jpg"
                                width="222"
                                sizes="(max-width: 479px) 99vw, (max-width: 767px) 54vw, (max-width: 991px) 36vw, 31vw"
                                srcset="
                                    https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfd6c8b6a11089ec02db_neora-aylon-YCTUXuXsSu8-unsplash%20(1)-p-500.jpeg   500w,
                                    https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfd6c8b6a11089ec02db_neora-aylon-YCTUXuXsSu8-unsplash%20(1)-p-1080.jpeg 1080w,
                                    https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ee2cfd6c8b6a11089ec02db_neora-aylon-YCTUXuXsSu8-unsplash%20(1).jpg         1227w
                                "
                                alt=""
                                class="testimonial-image _2"
                            />
                            <p class="quote">
                                O imtercâmbio me permitiu me conectar com outros viajantes com quem posso compartilhar minhas experiências. Eu amo esta comunidade e todas as pessoas incríveis que conheci!<br />
                                <span class="bold">-Jess Rasher</span>
                            </p>
                        </div>
                    </div>
                    <div class="left-arrow-2 w-slider-arrow-left"><h6 class="arrow left">➜</h6></div>
                    <div class="right-arrow-2 w-slider-arrow-right"><h6 class="arrow">➜</h6></div>
                    <div class="slide-nav-2 w-slider-nav w-round"></div>
                </div>
            </div>
            <div
                data-delay="5000"
                data-animation="fade"
                class="blog_hero_bg_slider w-slider"
                data-autoplay="true"
                data-easing="ease"
                data-hide-arrows="false"
                data-disable-swipe="false"
                data-autoplay-limit="0"
                data-nav-spacing="3"
                data-duration="800"
                data-infinite="true"
            >
                <div class="w-slider-mask">
                    <div data-w-id="84f633af-5f86-faf7-ec35-8c7f2f702552" class="blog_hero_slide w-slide">
                        <div
                            style="
                                -webkit-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                -moz-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                -ms-transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                                transform: translate3d(0, 0, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);
                            "
                            class="blog_hero_slide_image"
                        ></div>
                    </div>
                    <div data-w-id="84f633af-5f86-faf7-ec35-8c7f2f702553" class="blog_hero_slide _2 w-slide"><div class="blog_hero_slide_image _2"></div></div>
                    <div data-w-id="847e4bbc-fc5a-d13a-77be-d81dd05d0c96" class="blog_hero_slide w-slide"><div class="blog_hero_slide_image _3"></div></div>
                </div>
                <div class="blog-hero-left-arrow w-slider-arrow-left"><div class="w-icon-slider-left"></div></div>
                <div class="blog-hero-right-arrow w-slider-arrow-right"><div class="w-icon-slider-right"></div></div>
                <div class="blog-hero-slide-nav w-slider-nav w-round"></div>
            </div>
            <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed719559d85627f1a1f8492_travel%20Tell%20stencil%202.svg" alt="" class="confetti_hero_svg blog" />
        </div>
        <div id="Blog" class="section blog wf-section">
            <div class="container blog_posts">
                <div data-duration-in="300" data-duration-out="100" data-current="Tab 1" data-easing="ease" class="tabs on-blog w-tabs">
                    <div class="tabs-menu w-tab-menu">
                        <a data-w-tab="Tab 1" class="tab-link w-inline-block w-tab-link w--current"><div>Lugares</div></a>
                        <a data-w-tab="Tab 2" class="tab-link w-inline-block w-tab-link"><div>Cultura</div></a>
                        <a data-w-tab="Tab 3" class="tab-link w-inline-block w-tab-link"><div>Inspiração</div></a><a data-w-tab="Tab 4" class="tab-link w-inline-block w-tab-link"><div>Experience</div></a>
                        <a data-w-tab="Tab 5" class="tab-link w-inline-block w-tab-link"><div>Outros</div></a>
                    </div>
                    <div class="tabs-content w-tab-content">
                        <div data-w-tab="Tab 1" class="tab-pane-tab-1 w-tab-pane w--tab-active">
                            <div class="w-layout-grid grid">
                                <div class="blog-collection-list-wrapper w-dyn-list">
                                    <div role="list" class="blog-collection-list w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/posts" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede4ee313bfb8d870b0b7_ammie-ngo-vcu-OZBxxRk-unsplash.jpg');" class="story_image on_blog_page">
                                                    <div style="background-color: hsla(40.48780487804878, 96.85%, 49.8%, 1);" class="category"><div>Places</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede4ee313bfb8d870b0b7_ammie-ngo-vcu-OZBxxRk-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Minha viagem ao Vietnã</h4>
                                                    <p>
                                                        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto
                                                        beatae
                                                    </p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Natasha Miles</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/posts" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: #faaa04;" class="category"><div>Lugares</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Os melhores lugares do Peru para visitar</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Michelle Worthy</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/posts" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: #faaa04;" class="category"><div>Lugares</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>As diversas ilhas da Tailândia</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Mason Miller</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div data-w-tab="Tab 2" class="w-tab-pane">
                            <div class="w-layout-grid grid">
                                <div class="blog-collection-list-wrapper w-dyn-list">
                                    <div role="list" class="blog-collection-list w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/posts" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4643dec5df2a40dfcf30b_c-rayban-CIXoFys3gsw-unsplash.jpg');" class="story_image on_blog_page">
                                                    <div style="background-color: #9502f3;" class="category"><div>Cultura</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4643dec5df2a40dfcf30b_c-rayban-CIXoFys3gsw-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Pessoas, lugares e eventos da Índia</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique antih.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Jason Maddock</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog/posts" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4663410bcbadf855ca173_antonio-sessa-v5wggpHk8_Q-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: hsla(276.597510373444, 98.37%, 48.04%, 1);" class="category"><div>Cultura</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed4663410bcbadf855ca173_antonio-sessa-v5wggpHk8_Q-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>O que aprendi na Holanda</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Natasha Miles</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div data-w-tab="Tab 3" class="w-tab-pane">
                            <div class="w-layout-grid grid">
                                <div class="blog-collection-list-wrapper w-dyn-list">
                                    <div role="list" class="blog-collection-list w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/a-castle-on-an-island" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede21446658d49be91ba5_castle-on-mountain-near-sea-2347766.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: hsla(186, 97.36%, 42.56%, 1);" class="category"><div>Inspiration</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede21446658d49be91ba5_castle-on-mountain-near-sea-2347766.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Um castelo em uma ilha</h4>
                                                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Jason Maddock</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/new-zealands-vast-land" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede32a317f1bfcc08b29b_omer-faruk-bekdemir-5BuxuWIJF1Q-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: hsla(186, 97.36%, 42.56%, 1);" class="category"><div>Inspiration</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede32a317f1bfcc08b29b_omer-faruk-bekdemir-5BuxuWIJF1Q-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Vasta Terra da Nova Zelândia</h4>
                                                    <p>
                                                        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto
                                                        beatae
                                                    </p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Rachelle Mindy</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/my-journey-across-india" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466af4b317b9b577e3264_david-marcu-78A265wPiO4-unsplash.jpg');" class="story_image on_blog_page">
                                                    <div style="background-color: hsla(186, 97.36%, 42.56%, 1);" class="category"><div>Inspiration</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466af4b317b9b577e3264_david-marcu-78A265wPiO4-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Minha viagem pela Índia</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47e09c6c9789e41e50f94_brooke-cagle-Nm70URdtf3c-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Jason Maddock</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/africas-people-and-culture" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed463e64b317b48197e2448_annie-spratt-cVEOh_JJmEE-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: hsla(186, 97.36%, 42.56%, 1);" class="category"><div>Inspiration</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed463e64b317b48197e2448_annie-spratt-cVEOh_JJmEE-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Povo e Cultura da África</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Natasha Miles</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div data-w-tab="Tab 4" class="w-tab-pane">
                            <div class="w-layout-grid grid">
                                <div class="blog-collection-list-wrapper w-dyn-list">
                                    <div role="list" class="blog-collection-list w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/discovering-greece" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededeb9a317f1455c08b326_ryan-spencer-XGKaRnWjv1c-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: hsla(342.99212598425197, 100%, 50.2%, 1);" class="category"><div>Experience</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededeb9a317f1455c08b326_ryan-spencer-XGKaRnWjv1c-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Descobrindo a Grécia</h4>
                                                    <p>
                                                        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto
                                                        beatae
                                                    </p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Michelle Worthy</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/the-most-beautiful-island-in-the-world" class="story_wrap w-inline-block">
                                                <div
                                                    style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede958181415866b49452_rolands-varsbergs-miKmVyq3qhE-unsplash.jpg');"
                                                    class="story_image on_blog_page"
                                                >
                                                    <div style="background-color: hsla(342.99212598425197, 100%, 50.2%, 1);" class="category"><div>Experience</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede958181415866b49452_rolands-varsbergs-miKmVyq3qhE-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>A ilha mais bonita do mundo</h4>
                                                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Mason Miller</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/new-york-city-views" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededea55249ae5802f851ca_colton-duke-UExx0KnnkjY-unsplash.jpg');" class="story_image on_blog_page">
                                                    <div style="background-color: hsla(342.99212598425197, 100%, 50.2%, 1);" class="category"><div>Experience</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededea55249ae5802f851ca_colton-duke-UExx0KnnkjY-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Vistas da cidade de Nova York</h4>
                                                    <p>
                                                        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto
                                                        beatae
                                                    </p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Rachelle Mindy</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <a href="/blog-posts/japan-like-youve-never-seen-it" class="story_wrap w-inline-block">
                                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg');" class="story_image on_blog_page">
                                                    <div style="background-color: #ff0149;" class="category"><div>Experience</div></div>
                                                    <div
                                                        style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46653412d2b6239b5779d_sorasak-_UIN-pFfJ7c-unsplash.jpg');"
                                                        class="card_image_hover_expand"
                                                    ></div>
                                                </div>
                                                <div class="story_content">
                                                    <h4>Japão como você nunca viu</h4>
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Lorem ipsum dolor sit amet.</p>
                                                    <div class="travelteller_wrap">
                                                        <div
                                                            style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');"
                                                            class="travelteller_circle"
                                                        ></div>
                                                        <h6>Rachelle Mindy</h6>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div data-w-tab="Tab 5" class="w-tab-pane">
                            <div class="w-layout-grid videos_display_grid no_top_padding">
                                <div class="w-dyn-list">
                                    <div role="list" class="videos-collection-list w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede32a317f1bfcc08b29b_omer-faruk-bekdemir-5BuxuWIJF1Q-unsplash.jpg');" class="story_image video">
                                                <h5 class="card_title">Vasta Terra da Nova Zelândia</h5>
                                                <a href="#" class="video_play_link w-inline-block w-lightbox">
                                                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                                    <script type="application/json" class="w-json">
                                                        {
                                                            "items": [
                                                                {
                                                                    "url": "https://www.youtube.com/watch?v=HIsdr8oeG8M&feature=youtu.be/autoplay=1",
                                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FHIsdr8oeG8M%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHIsdr8oeG8M&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FHIsdr8oeG8M%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                                    "height": 480,
                                                                    "width": 854,
                                                                    "thumbnailUrl": "https://i.ytimg.com/vi/HIsdr8oeG8M/hqdefault.jpg",
                                                                    "type": "video"
                                                                }
                                                            ],
                                                            "group": ""
                                                        }
                                                    </script>
                                                </a>
                                            </div>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededea55249ae5802f851ca_colton-duke-UExx0KnnkjY-unsplash.jpg');" class="story_image video">
                                                <h5 class="card_title">Vistas da cidade de Nova York</h5>
                                                <a href="#" class="video_play_link w-inline-block w-lightbox">
                                                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                                    <script type="application/json" class="w-json">
                                                        {
                                                            "items": [
                                                                {
                                                                    "url": "https://www.youtube.com/watch?v=PjEmOU9drw8&feature=youtu.be/autoplay=1",
                                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FPjEmOU9drw8%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPjEmOU9drw8&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FPjEmOU9drw8%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                                    "height": 480,
                                                                    "width": 854,
                                                                    "thumbnailUrl": "https://i.ytimg.com/vi/PjEmOU9drw8/hqdefault.jpg",
                                                                    "type": "video"
                                                                }
                                                            ],
                                                            "group": ""
                                                        }
                                                    </script>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="w-dyn-list">
                                    <div role="list" class="videos-collection-list row_2 w-dyn-items">
                                        <div role="listitem" class="w-dyn-item">
                                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ededeb9a317f1455c08b326_ryan-spencer-XGKaRnWjv1c-unsplash.jpg');" class="story_image video">
                                                <h5 class="card_title">Descobrindo a Grécia</h5>
                                                <a href="#" class="video_play_link w-inline-block w-lightbox">
                                                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                                    <script type="application/json" class="w-json">
                                                        {
                                                            "items": [
                                                                {
                                                                    "url": "https://www.youtube.com/watch?v=Ybremc433a8&feature=youtu.be/autoplay=1",
                                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FYbremc433a8%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DYbremc433a8&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FYbremc433a8%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                                    "height": 480,
                                                                    "width": 854,
                                                                    "thumbnailUrl": "https://i.ytimg.com/vi/Ybremc433a8/hqdefault.jpg",
                                                                    "type": "video"
                                                                }
                                                            ],
                                                            "group": ""
                                                        }
                                                    </script>
                                                </a>
                                            </div>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede958181415866b49452_rolands-varsbergs-miKmVyq3qhE-unsplash.jpg');" class="story_image video">
                                                <h5 class="card_title">A ilha mais bonita do mundo</h5>
                                                <a href="#" class="video_play_link w-inline-block w-lightbox">
                                                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                                    <script type="application/json" class="w-json">
                                                        {
                                                            "items": [
                                                                {
                                                                    "url": "https://www.youtube.com/watch?v=xPsjlPMK5i4&feature=youtu.be/autoplay=1",
                                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FxPsjlPMK5i4%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DxPsjlPMK5i4&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FxPsjlPMK5i4%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                                    "height": 480,
                                                                    "width": 854,
                                                                    "thumbnailUrl": "https://i.ytimg.com/vi/xPsjlPMK5i4/hqdefault.jpg",
                                                                    "type": "video"
                                                                }
                                                            ],
                                                            "group": ""
                                                        }
                                                    </script>
                                                </a>
                                            </div>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede4ee313bfb8d870b0b7_ammie-ngo-vcu-OZBxxRk-unsplash.jpg');" class="story_image video">
                                                <h5 class="card_title">Minha viagem ao Vietnã</h5>
                                                <a href="#" class="video_play_link w-inline-block w-lightbox">
                                                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                                    <script type="application/json" class="w-json">
                                                        {
                                                            "items": [
                                                                {
                                                                    "url": "https://www.youtube.com/watch?v=zAeCE6YYCIs&feature=youtu.be/autoplay=1",
                                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FzAeCE6YYCIs%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzAeCE6YYCIs&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FzAeCE6YYCIs%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                                    "height": 480,
                                                                    "width": 854,
                                                                    "thumbnailUrl": "https://i.ytimg.com/vi/zAeCE6YYCIs/hqdefault.jpg",
                                                                    "type": "video"
                                                                }
                                                            ],
                                                            "group": ""
                                                        }
                                                    </script>
                                                </a>
                                            </div>
                                        </div>
                                        <div role="listitem" class="w-dyn-item">
                                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede21446658d49be91ba5_castle-on-mountain-near-sea-2347766.jpg');" class="story_image video">
                                                <h5 class="card_title">Um castelo em uma ilha</h5>
                                                <a href="#" class="video_play_link w-inline-block w-lightbox">
                                                    <img src="https://assets.website-files.com/5ed1cf34bf802c5f339f8167/5ed453b8412d2b4e20b51dea_Play.svg" width="16" alt="" />
                                                    <script type="application/json" class="w-json">
                                                        {
                                                            "items": [
                                                                {
                                                                    "url": "https://www.youtube.com/watch?v=1m_-_NSbVgE&feature=youtu.be/autoplay=1",
                                                                    "html": "<iframe class=\"embedly-embed\" src=\"//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F1m_-_NSbVgE%3Fautoplay%3D1%26feature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1m_-_NSbVgE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F1m_-_NSbVgE%2Fhqdefault.jpg&args=autoplay%3D1&key=96f1f04c5f4143bcb0f2e68c87d65feb&autoplay=1&type=text%2Fhtml&schema=youtube\" width=\"854\" height=\"480\" scrolling=\"no\" title=\"YouTube embed\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen=\"true\"></iframe>",
                                                                    "height": 480,
                                                                    "width": 854,
                                                                    "thumbnailUrl": "https://i.ytimg.com/vi/1m_-_NSbVgE/hqdefault.jpg",
                                                                    "type": "video"
                                                                }
                                                            ],
                                                            "group": ""
                                                        }
                                                    </script>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sticky-nav-contain">
                    <div class="sticky">
                        <h4>Categorias</h4>
                        <div class="line div"></div>
                        <div class="blog_categories_contain">
                            <div class="w-dyn-list">
                                <div role="list" class="category-tags-collection-list w-dyn-items">
                                    <div role="listitem" class="w-dyn-item">
                                        <a style="background-color: #faaa04;" href="/blog/category" class="category with-margin w-inline-block"><div>Lugares</div></a>
                                    </div>
                                    <div role="listitem" class="w-dyn-item">
                                        <a style="background-color: #03c1d6;" href="/blog/category" class="category with-margin w-inline-block"><div>Inspiração</div></a>
                                    </div>
                                    <div role="listitem" class="w-dyn-item">
                                        <a style="background-color: #9502f3;" href="/blog/category" class="category with-margin w-inline-block"><div>Cultura</div></a>
                                    </div>
                                    <div role="listitem" class="w-dyn-item">
                                        <a style="background-color: #ff0149;" href="/blog/category" class="category with-margin w-inline-block"><div>Experiência</div></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="_30px-div"></div>
                        <h4>Viajantes</h4>
                        <div class="line div"></div>
                        <div class="top_traveltellers_collection-list-wrapper on-blog w-dyn-list">
                            <div role="list" class="w-dyn-items">
                                <div role="listitem" class="w-dyn-item">
                                    <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47f6a78a1380738fac61c_dane-deaner-IfDfxUrJasI-unsplash.jpg');" class="travelteller_circle large"></div>
                                        <div>
                                            <h5>Rachelle Mindy</h5>
                                            <div class="text_block">New York, USA</div>
                                        </div>
                                    </a>
                                </div>
                                <div role="listitem" class="w-dyn-item">
                                    <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle large"></div>
                                        <div>
                                            <h5>Mason Miller</h5>
                                            <div class="text_block">Amsterdam, Netherlands</div>
                                        </div>
                                    </a>
                                </div>
                                <div role="listitem" class="w-dyn-item">
                                    <a href="/traveltellers/travelteller" class="top_travelteller w-inline-block">
                                        <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle large"></div>
                                        <div>
                                            <h5>Natasha Miles</h5>
                                            <div class="text_block">Paris, France</div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
