<div class="section blog_section wf-section">
    
    <div class="blog_post_hero_image_contain">
        <h2 class="blog-post-title">Os melhores lugares do Peru para visitar</h2>
        <div class="text_block blog-date">Janeiro 16, 2022</div>
        <div
            data-w-id="be3eb497-9b1b-8800-595f-4803158bd7a9"
            style="
                background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed466884b317b00b57e3175_scott-umstattd--6HgP_ekYC4-unsplash.jpg');
                will-change: transform;
                transform: translate3d(0px, 0px, 0px) scale3d(1.1, 1.1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg);
                transform-style: preserve-3d;
            "
            class="blog_post_image"
        ></div>
    </div>
    <div class="blog_content_contain">
        <div class="blog_title_contain">
            <div class="blog_title_and_date"></div>
            <div class="div-block-13">
                <div class="w-dyn-list">
                    <div role="list" class="w-dyn-items">
                        <div role="listitem" class="w-dyn-item">
                        <iframe width="100%" height="" src="https://www.youtube.com/embed/KZPN7Mlrczc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            <!-- <a href="/traveltellers/travelteller" class="travelteller_link w-inline-block">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47dfda90a9c8418230b18_candice-picard-MP0IUfwrn0A-unsplash.jpg');" class="travelteller_circle large"></div>
                                <div><h5>Michelle Worthy</h5></div>
                            </a> -->
                        </div>
                    </div>
                </div>
                <!-- <div style="color: #faaa04;">Lugares</div> -->
            </div>
        </div>
        <!-- <div class="blog-rich-text-block w-richtext">
            <h3>Iure dolorem cumque quae eius.</h3>
            <p>Consequatur quae molestias itaque totam optio tenetur. Sint ex sed. Et similique in aut iste quibusdam unde. Laboriosam et fugit natus quaerat libero aspernatur et consequatur. Rem ea a omnis voluptatem est ut.</p>
            <h3>Alias molestiae non velit quis dignissimos voluptates.</h3>
            <blockquote>Iste quia voluptas laborum in et atque placeat rem. Sint itaque et. Eum quo aut harum atque nihil eius et est voluptates.</blockquote>
            <p>
                A eum consequuntur quia qui aspernatur quia. Quia corrupti quaerat omnis odio enim voluptatem et ea repudiandae. Officia numquam voluptatem in. Ex natus dolore est hic et dolorem excepturi sapiente. Earum maxime nostrum
                dolor iure quasi eius dignissimos.
            </p>
            <p>Laborum nihil maiores. Ratione omnis officiis sit ut repellendus doloribus quas similique. Earum dolor velit quia dolorum. Beatae maiores dignissimos corrupti eveniet.</p>
            <p>‍</p>
            <h3>Autem commodi quasi nam sed.</h3>
            <p>Perspiciatis corrupti dolores voluptatum. Aperiam vel suscipit dicta ipsam non eligendi minus. Corporis ea distinctio quia vero saepe.</p>
            <h3>Iste sint numquam suscipit.</h3>
            <blockquote>Rerum sint aliquid perferendis soluta. Sunt itaque consequatur fuga non. Quia consequatur reiciendis autem quam est et sed.</blockquote>
            <p>Reiciendis occaecati distinctio qui dolorem nesciunt. Odit voluptas aut cum. Non in est et illo et et et voluptate. Unde excepturi quis hic omnis. Dolor natus omnis aut est repellendus officiis perspiciatis sunt aut.</p>
            <p>Sed explicabo aut reiciendis eaque quo. Illum numquam velit fuga optio magni ducimus. Voluptatem eos nulla eum. Ipsam officiis voluptatem ratione. Qui doloremque numquam iste eos vel qui.</p>
            <h4>Quia dolor rerum maxime voluptatem dolor debitis in.</h4>
            <p>Unde vitae et. In quia assumenda. Numquam et vel. Numquam earum ut praesentium et quia ducimus.</p>
            <h3>In in delectus voluptatibus eum sequi harum laudantium.</h3>
            <blockquote>Nihil ut quisquam. Eligendi rerum facere et. Voluptas beatae dolorem. Ab est in architecto adipisci quis corrupti. Quaerat eaque nobis repellendus ut est.</blockquote>
            <p>Qui ut voluptas ut ipsam et necessitatibus quo. Adipisci officiis qui sunt vel quia nemo et. Velit quod et sit quos a enim. Et praesentium itaque maxime reprehenderit nulla.</p>
            <p>
                Temporibus omnis ipsum aut rem sunt adipisci aut dolor aut. Enim optio eum mollitia culpa beatae omnis pariatur reiciendis. Distinctio numquam et molestiae aut facilis mollitia maxime reprehenderit. Recusandae et voluptate
                dolore in repellat modi accusantium et. Beatae occaecati dicta inventore sit deleniti et. Labore iusto non deleniti.
            </p>
            <p>
                <a href="https://remotethera.webflow.io/blog/how-students-are-coping-through-the-coronavirus-pandemic"><br /></a>
            </p>
            <h4>Iure dolorem cumque quae eius.</h4>
            <p>Consequatur quae molestias itaque totam optio tenetur. Sint ex sed. Et similique in aut iste quibusdam unde. Laboriosam et fugit natus quaerat libero aspernatur et consequatur. Rem ea a omnis voluptatem est ut.</p>
            <h3>Alias molestiae non velit quis dignissimos voluptates.</h3>
            <blockquote>Iste quia voluptas laborum in et atque placeat rem. Sint itaque et. Eum quo aut harum atque nihil eius et est voluptates.</blockquote>
            <p>
                A eum consequuntur quia qui aspernatur quia. Quia corrupti quaerat omnis odio enim voluptatem et ea repudiandae. Officia numquam voluptatem in. Ex natus dolore est hic et dolorem excepturi sapiente. Earum maxime nostrum
                dolor iure quasi eius dignissimos.
            </p>
            <p>Laborum nihil maiores. Ratione omnis officiis sit ut repellendus doloribus quas similique. Earum dolor velit quia dolorum. Beatae maiores dignissimos corrupti eveniet.</p>
            <p>‍</p>
            <h3>Autem commodi quasi nam sed.</h3>
            <p>Perspiciatis corrupti dolores voluptatum. Aperiam vel suscipit dicta ipsam non eligendi minus. Corporis ea distinctio quia vero saepe.</p>
            <h3>Iste sint numquam suscipit.</h3>
            <blockquote>Rerum sint aliquid perferendis soluta. Sunt itaque consequatur fuga non. Quia consequatur reiciendis autem quam est et sed.</blockquote>
            <p>Reiciendis occaecati distinctio qui dolorem nesciunt. Odit voluptas aut cum. Non in est et illo et et et voluptate. Unde excepturi quis hic omnis. Dolor natus omnis aut est repellendus officiis perspiciatis sunt aut.</p>
            <p>Sed explicabo aut reiciendis eaque quo. Illum numquam velit fuga optio magni ducimus. Voluptatem eos nulla eum. Ipsam officiis voluptatem ratione. Qui doloremque numquam iste eos vel qui.</p>
            <h3>Quia dolor rerum maxime voluptatem dolor debitis in.</h3>
            <p>Unde vitae et. In quia assumenda. Numquam et vel. Numquam earum ut praesentium et quia ducimus.</p>
            <h3>In in delectus voluptatibus eum sequi harum laudantium.</h3>
            <blockquote>Nihil ut quisquam. Eligendi rerum facere et. Voluptas beatae dolorem. Ab est in architecto adipisci quis corrupti. Quaerat eaque nobis repellendus ut est.</blockquote>
            <p>Qui ut voluptas ut ipsam et necessitatibus quo. Adipisci officiis qui sunt vel quia nemo et. Velit quod et sit quos a enim. Et praesentium itaque maxime reprehenderit nulla.</p>
            <p>
                Temporibus omnis ipsum aut rem sunt adipisci aut dolor aut. Enim optio eum mollitia culpa beatae omnis pariatur reiciendis. Distinctio numquam et molestiae aut facilis mollitia maxime reprehenderit. Recusandae et voluptate
                dolore in repellat modi accusantium et. Beatae occaecati dicta inventore sit deleniti et. Labore iusto non deleniti.
            </p>
            <h3>Iure dolorem cumque quae eius.</h3>
            <p>Consequatur quae molestias itaque totam optio tenetur. Sint ex sed. Et similique in aut iste quibusdam unde. Laboriosam et fugit natus quaerat libero aspernatur et consequatur. Rem ea a omnis voluptatem est ut.</p>
            <h3>Alias molestiae non velit quis dignissimos voluptates.</h3>
            <blockquote>Iste quia voluptas laborum in et atque placeat rem. Sint itaque et. Eum quo aut harum atque nihil eius et est voluptates.</blockquote>
            <p>
                A eum consequuntur quia qui aspernatur quia. Quia corrupti quaerat omnis odio enim voluptatem et ea repudiandae. Officia numquam voluptatem in. Ex natus dolore est hic et dolorem excepturi sapiente. Earum maxime nostrum
                dolor iure quasi eius dignissimos.
            </p>
            <p>Laborum nihil maiores. Ratione omnis officiis sit ut repellendus doloribus quas similique. Earum dolor velit quia dolorum. Beatae maiores dignissimos corrupti eveniet.</p>
            <p>‍</p>
            <h4>Autem commodi quasi nam sed.</h4>
            <p>Perspiciatis corrupti dolores voluptatum. Aperiam vel suscipit dicta ipsam non eligendi minus. Corporis ea distinctio quia vero saepe.</p>
            <h3>Iste sint numquam suscipit.</h3>
            <blockquote>Rerum sint aliquid perferendis soluta. Sunt itaque consequatur fuga non. Quia consequatur reiciendis autem quam est et sed.</blockquote>
            <p>Reiciendis occaecati distinctio qui dolorem nesciunt. Odit voluptas aut cum. Non in est et illo et et et voluptate. Unde excepturi quis hic omnis. Dolor natus omnis aut est repellendus officiis perspiciatis sunt aut.</p>
            <p>Sed explicabo aut reiciendis eaque quo. Illum numquam velit fuga optio magni ducimus. Voluptatem eos nulla eum. Ipsam officiis voluptatem ratione. Qui doloremque numquam iste eos vel qui.</p>
            <h4>Quia dolor rerum maxime voluptatem dolor debitis in.</h4>
            <p>Unde vitae et. In quia assumenda. Numquam et vel. Numquam earum ut praesentium et quia ducimus.</p>
            <h3>In in delectus voluptatibus eum sequi harum laudantium.</h3>
            <blockquote>Nihil ut quisquam. Eligendi rerum facere et. Voluptas beatae dolorem. Ab est in architecto adipisci quis corrupti. Quaerat eaque nobis repellendus ut est.</blockquote>
            <p>Qui ut voluptas ut ipsam et necessitatibus quo. Adipisci officiis qui sunt vel quia nemo et. Velit quod et sit quos a enim. Et praesentium itaque maxime reprehenderit nulla.</p>
            <p>
                Temporibus omnis ipsum aut rem sunt adipisci aut dolor aut. Enim optio eum mollitia culpa beatae omnis pariatur reiciendis. Distinctio numquam et molestiae aut facilis mollitia maxime reprehenderit. Recusandae et voluptate
                dolore in repellat modi accusantium et. Beatae occaecati dicta inventore sit deleniti et. Labore iusto non deleniti.
            </p>
            <h2>Iure dolorem cumque quae eius.</h2>
            <p>Consequatur quae molestias itaque totam optio tenetur. Sint ex sed. Et similique in aut iste quibusdam unde. Laboriosam et fugit natus quaerat libero aspernatur et consequatur. Rem ea a omnis voluptatem est ut.</p>
            <h3>Alias molestiae non velit quis dignissimos voluptates.</h3>
            <blockquote>Iste quia voluptas laborum in et atque placeat rem. Sint itaque et. Eum quo aut harum atque nihil eius et est voluptates.</blockquote>
            <p>
                A eum consequuntur quia qui aspernatur quia. Quia corrupti quaerat omnis odio enim voluptatem et ea repudiandae. Officia numquam voluptatem in. Ex natus dolore est hic et dolorem excepturi sapiente. Earum maxime nostrum
                dolor iure quasi eius dignissimos.
            </p>
            <p>Laborum nihil maiores. Ratione omnis officiis sit ut repellendus doloribus quas similique. Earum dolor velit quia dolorum. Beatae maiores dignissimos corrupti eveniet.</p>
            <p>‍</p>
            <h2>Autem commodi quasi nam sed.</h2>
            <p>Perspiciatis corrupti dolores voluptatum. Aperiam vel suscipit dicta ipsam non eligendi minus. Corporis ea distinctio quia vero saepe.</p>
            <h3>Iste sint numquam suscipit.</h3>
            <blockquote>Rerum sint aliquid perferendis soluta. Sunt itaque consequatur fuga non. Quia consequatur reiciendis autem quam est et sed.</blockquote>
            <p>Reiciendis occaecati distinctio qui dolorem nesciunt. Odit voluptas aut cum. Non in est et illo et et et voluptate. Unde excepturi quis hic omnis. Dolor natus omnis aut est repellendus officiis perspiciatis sunt aut.</p>
            <p>Sed explicabo aut reiciendis eaque quo. Illum numquam velit fuga optio magni ducimus. Voluptatem eos nulla eum. Ipsam officiis voluptatem ratione. Qui doloremque numquam iste eos vel qui.</p>
            <h2>Quia dolor rerum maxime voluptatem dolor debitis in.</h2>
            <p>Unde vitae et. In quia assumenda. Numquam et vel. Numquam earum ut praesentium et quia ducimus.</p>
            <h3>In in delectus voluptatibus eum sequi harum laudantium.</h3>
            <blockquote>Nihil ut quisquam. Eligendi rerum facere et. Voluptas beatae dolorem. Ab est in architecto adipisci quis corrupti. Quaerat eaque nobis repellendus ut est.</blockquote>
            <p>Qui ut voluptas ut ipsam et necessitatibus quo. Adipisci officiis qui sunt vel quia nemo et. Velit quod et sit quos a enim. Et praesentium itaque maxime reprehenderit nulla.</p>
            <p>
                Temporibus omnis ipsum aut rem sunt adipisci aut dolor aut. Enim optio eum mollitia culpa beatae omnis pariatur reiciendis. Distinctio numquam et molestiae aut facilis mollitia maxime reprehenderit. Recusandae et voluptate
                dolore in repellat modi accusantium et. Beatae occaecati dicta inventore sit deleniti et. Labore iusto non deleniti.
            </p>
            <p>
                <a href="https://remotethera.webflow.io/blog/how-students-are-coping-through-the-coronavirus-pandemic"><br /></a>
            </p>
            <h2>Iure dolorem cumque quae eius.</h2>
            <p>Consequatur quae molestias itaque totam optio tenetur. Sint ex sed. Et similique in aut iste quibusdam unde. Laboriosam et fugit natus quaerat libero aspernatur et consequatur. Rem ea a omnis voluptatem est ut.</p>
            <h3>Alias molestiae non velit quis dignissimos voluptates.</h3>
            <blockquote>Iste quia voluptas laborum in et atque placeat rem. Sint itaque et. Eum quo aut harum atque nihil eius et est voluptates.</blockquote>
            <p>
                A eum consequuntur quia qui aspernatur quia. Quia corrupti quaerat omnis odio enim voluptatem et ea repudiandae. Officia numquam voluptatem in. Ex natus dolore est hic et dolorem excepturi sapiente. Earum maxime nostrum
                dolor iure quasi eius dignissimos.
            </p>
            <p>Laborum nihil maiores. Ratione omnis officiis sit ut repellendus doloribus quas similique. Earum dolor velit quia dolorum. Beatae maiores dignissimos corrupti eveniet.</p>
            <p>‍</p>
            <h2>Autem commodi quasi nam sed.</h2>
            <p>Perspiciatis corrupti dolores voluptatum. Aperiam vel suscipit dicta ipsam non eligendi minus. Corporis ea distinctio quia vero saepe.</p>
            <h3>Iste sint numquam suscipit.</h3>
            <blockquote>Rerum sint aliquid perferendis soluta. Sunt itaque consequatur fuga non. Quia consequatur reiciendis autem quam est et sed.</blockquote>
            <p>Reiciendis occaecati distinctio qui dolorem nesciunt. Odit voluptas aut cum. Non in est et illo et et et voluptate. Unde excepturi quis hic omnis. Dolor natus omnis aut est repellendus officiis perspiciatis sunt aut.</p>
            <p>Sed explicabo aut reiciendis eaque quo. Illum numquam velit fuga optio magni ducimus. Voluptatem eos nulla eum. Ipsam officiis voluptatem ratione. Qui doloremque numquam iste eos vel qui.</p>
            <h2>Quia dolor rerum maxime voluptatem dolor debitis in.</h2>
            <p>Unde vitae et. In quia assumenda. Numquam et vel. Numquam earum ut praesentium et quia ducimus.</p>
            <h3>In in delectus voluptatibus eum sequi harum laudantium.</h3>
            <blockquote>Nihil ut quisquam. Eligendi rerum facere et. Voluptas beatae dolorem. Ab est in architecto adipisci quis corrupti. Quaerat eaque nobis repellendus ut est.</blockquote>
            <p>Qui ut voluptas ut ipsam et necessitatibus quo. Adipisci officiis qui sunt vel quia nemo et. Velit quod et sit quos a enim. Et praesentium itaque maxime reprehenderit nulla.</p>
            <p>
                Temporibus omnis ipsum aut rem sunt adipisci aut dolor aut. Enim optio eum mollitia culpa beatae omnis pariatur reiciendis. Distinctio numquam et molestiae aut facilis mollitia maxime reprehenderit. Recusandae et voluptate
                dolore in repellat modi accusantium et. Beatae occaecati dicta inventore sit deleniti et. Labore iusto non deleniti.
            </p>
            <h2>Iure dolorem cumque quae eius.</h2>
            <p>Consequatur quae molestias itaque totam optio tenetur. Sint ex sed. Et similique in aut iste quibusdam unde. Laboriosam et fugit natus quaerat libero aspernatur et consequatur. Rem ea a omnis voluptatem est ut.</p>
            <h3>Alias molestiae non velit quis dignissimos voluptates.</h3>
            <blockquote>Iste quia voluptas laborum in et atque placeat rem. Sint itaque et. Eum quo aut harum atque nihil eius et est voluptates.</blockquote>
            <p>
                A eum consequuntur quia qui aspernatur quia. Quia corrupti quaerat omnis odio enim voluptatem et ea repudiandae. Officia numquam voluptatem in. Ex natus dolore est hic et dolorem excepturi sapiente. Earum maxime nostrum
                dolor iure quasi eius dignissimos.
            </p>
            <p>Laborum nihil maiores. Ratione omnis officiis sit ut repellendus doloribus quas similique. Earum dolor velit quia dolorum. Beatae maiores dignissimos corrupti eveniet.</p>
            <p>‍</p>
            <h2>Autem commodi quasi nam sed.</h2>
            <p>Perspiciatis corrupti dolores voluptatum. Aperiam vel suscipit dicta ipsam non eligendi minus. Corporis ea distinctio quia vero saepe.</p>
            <h3>Iste sint numquam suscipit.</h3>
            <blockquote>Rerum sint aliquid perferendis soluta. Sunt itaque consequatur fuga non. Quia consequatur reiciendis autem quam est et sed.</blockquote>
            <p>Reiciendis occaecati distinctio qui dolorem nesciunt. Odit voluptas aut cum. Non in est et illo et et et voluptate. Unde excepturi quis hic omnis. Dolor natus omnis aut est repellendus officiis perspiciatis sunt aut.</p>
            <p>Sed explicabo aut reiciendis eaque quo. Illum numquam velit fuga optio magni ducimus. Voluptatem eos nulla eum. Ipsam officiis voluptatem ratione. Qui doloremque numquam iste eos vel qui.</p>
            <h2>Quia dolor rerum maxime voluptatem dolor debitis in.</h2>
            <p>Unde vitae et. In quia assumenda. Numquam et vel. Numquam earum ut praesentium et quia ducimus.</p>
            <h3>In in delectus voluptatibus eum sequi harum laudantium.</h3>
            <blockquote>Nihil ut quisquam. Eligendi rerum facere et. Voluptas beatae dolorem. Ab est in architecto adipisci quis corrupti. Quaerat eaque nobis repellendus ut est.</blockquote>
            <p>Qui ut voluptas ut ipsam et necessitatibus quo. Adipisci officiis qui sunt vel quia nemo et. Velit quod et sit quos a enim. Et praesentium itaque maxime reprehenderit nulla.</p>
            <p>
                Temporibus omnis ipsum aut rem sunt adipisci aut dolor aut. Enim optio eum mollitia culpa beatae omnis pariatur reiciendis. Distinctio numquam et molestiae aut facilis mollitia maxime reprehenderit. Recusandae et voluptate
                dolore in repellat modi accusantium et. Beatae occaecati dicta inventore sit deleniti et. Labore iusto non deleniti.
            </p>
            <p>‍</p>
        </div> -->
    </div>
    <div style="opacity: 1;" class="container">
        <h2>Relacionados</h2>
        <div class="blog-collection-list-wrapper w-dyn-list">
            <div role="list" class="other_post_collection_list w-dyn-items">
                <div role="listitem" class="other-posts-item w-dyn-item">
                    <a href="/blog/post" class="story_wrap flex_vertical w-inline-block">
                        <div class="story_image vertical">
                            <div style="background-color: hsla(40.48780487804878, 96.85%, 49.8%, 1);" class="category"><div>Categoria</div></div>
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5edede4ee313bfb8d870b0b7_ammie-ngo-vcu-OZBxxRk-unsplash.jpg');" class="card_image_hover_expand"></div>
                        </div>
                        <div class="story_content vertical">
                            <h4>Minha viagem ao Vietnã</h4>
                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae</p>
                            <div class="travelteller_wrap">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47de9c6c978a9cae50f5d_atikh-bana-Ycds6emp7BA-unsplash.jpg');" class="travelteller_circle"></div>
                                <h6>Natasha Miles</h6>
                            </div>
                        </div>
                    </a>
                </div>
                <div role="listitem" class="other-posts-item w-dyn-item">
                    <a href="/blog/post" class="story_wrap flex_vertical w-inline-block">
                        <div class="story_image vertical">
                            <div style="background-color: #faaa04;" class="category"><div>Categoria</div></div>
                            <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed46366a0977f06fc4d1c3e_federico-gutierrez-IqW8saasx0E-unsplash.jpg');" class="card_image_hover_expand"></div>
                        </div>
                        <div class="story_content vertical">
                            <h4>As diversas ilhas da Tailândia</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <div class="travelteller_wrap">
                                <div style="background-image: url('https://assets.website-files.com/5ed4430d97a20a41629058ab/5ed47ddea0977ff3794d9252_ben-parker-ym--mSBZ0ro-unsplash.jpg');" class="travelteller_circle"></div>
                                <h6>Mason Miller</h6>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
